### ISSUE TITLE
Feil skrivemåte av API i fane-tittel

### ISSUE THREAD

**Issue by stigbd** [Altinn/fdk#1235]
I fane-tittel er API skrevet "Api". Dette er ikkje i tråd med slik det er skrive i resten av katalogen. Og eg vil tru at korrekt er all-caps, slik: "API"

**Comment by sindresandvik2** [comment]
Fix klar i UT1 https://www.ut1.fellesdatakatalog.brreg.no/apis?sortfield=modified

**Comment by lillelars** [comment]
@stigbd @sindresandvik2  Må lukke hele issuen

**Comment by sindresandvik2** [comment]
Fikset!  Verifisert
