### ISSUE TITLE
Paginering fungerer ikkje på datasets-endepunktet

### ISSUE THREAD

**Issue by livarb** [Altinn/fdk#1289]
Får ikkje lenger paginering på API-et til å fungere.
Dvs. uansett kva verdi eg set på "from"-parameteret, så får eg samme data tilbake. Dermed er det ikkje mogleg å hente ut alle dataa.

Eg fekk problem med dette for eit par veker sidan.

http://fellesdatakatalog.brreg.no/datasets/ea9e2aa7-880c-4387-888e-77446acab279

Samme datasett er det første ein får opp på begge desse spørringane:
curl -H "Accept: application/json" http://fellesdatakatalog.brreg.no/api/datasets?size=3&from=5
curl -H "Accept: application/json" http://fellesdatakatalog.brreg.no/api/datasets?size=3&from=0

**Comment by markkopaas** [comment]
We have changed our search api. Page selection parameter is now "page" and it is 0-based. So the second page is page=1

**Comment by livarb** [comment]
Dokumentasjonen bør gjerne oppdaterast?
http://fellesdatakatalog.brreg.no/datasets/ea9e2aa7-880c-4387-888e-77446acab279

**Comment by livarb** [comment]
Får ikkje page til å fungere. Gjer eg noko feil?

Test:
diff <(curl -sH "Accept: application/json" http://fellesdatakatalog.brreg.no/api/datasets?size=100&page=5) <(curl -sH "Accept: application/json" http://fellesdatakatalog.brreg.no/api/datasets?size=100&page=0)

**Comment by livarb** [comment]
Tok ein rask titt på kjeldekoden, og det ser ut til å vere i orden der:
https://github.com/Informasjonsforvaltning/fdk/blob/develop/applications/search-api/src/main/java/no/dcat/portal/query/DatasetsQueryService.java

**Comment by markkopaas** [comment]
Interessant, når jeg leser ut id av den første svar fra forskjellige sider (samme som du prøvde) får jeg forskjell

```
diff <(curl -s 'http://fellesdatakatalog.brreg.no/api/datasets?size=100&page=5' | jq ".hits.hits[0]._id") <(curl -s 'http://fellesdatakatalog.brreg.no/api/datasets?size=100&page=0' | jq ".hits.hits[0]._id")
```

```
< "e0a9c6fb-6cc9-4cce-88e3-69357250704c"
---
> "68d08f28-a16d-4fab-a953-ed4ab08ce2e2"
```

**Comment by markkopaas** [comment]
du må bruke ' , ellers shell leser &
