### ISSUE TITLE
Registreringsløsningen:  API-Innhøsting fra katalog mangler timeout (API-953)

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1312]
Dersom innhøstingen fra en ttl fil av en eller annen grunn ikke fungerer så timer ikke spørringen ut.  Jobben henger selv om en logger ut  og avslutter nettleseren.

Her er en url som gir feil: 
https://raw.githubusercontent.com/Informasjonsforvaltning/fdk-testdata/master/testdata/APIkatalog3_Test.ttl

**Comment by lillelars** [comment]
Klarer ikke gjenskape denne lenger. Jobben "henger" ikke. jeg klarer å høste inn de APIene som skal fungere og får feilmelding på de som ikke fungerer.
