### ISSUE TITLE
Rapportsiden: Data mangler	(API-914)

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1314]
På oversikten nederst på rapportsiden vises en liste over virksomheter som leverer data. Øverst i denne lista finnet et tall som ikke har Navn foran seg. Dette vet vi er GeoNorge. 

Når en bruker https://www.ut1.fellesdatakatalog.brreg.no/catalogs listes alle katalogene opp. Heller ikke her finner en GeoNorge

![914](https://user-images.githubusercontent.com/42966644/53009329-90e2ac80-343b-11e9-8c55-a145375c3d56.png)

**Comment by bgrova** [comment]
Denne feilen skyldes at Geonorge/Kartverket representerer publisher på et annet format (en annen type RDF) enn DCAT-standarden foreskriver.
DCAT krever at den skal være en foaf:Agent, mens i Geonorge er den representert som skos:ConceptSchema.
Katalogen blir derfor ikke lagret i Fuseki fordi den ikke samsvarer med forventet rdf-struktur.

Alternative løsninger:
1. Få Kartverket til å endre til en representasjon som er i samsvar med dcat-standarden
2. Transformere til foaf:Agent før vi lagrer koden
3. I search-api: Hvis det ikke finnes noen verdi for navn på catalog (i /catalogs), erstatt dette med noe annet, for eksempel navn på publisher.
@joebrreg må avgjøre hvordan vi løser dette

**Comment by joachim-me** [comment]
@bgrova Vi ønsker ikke å rette opp i feil data, så alternativ 1 er løsningen her. Kan du sende en mail til Lars Inge i Kartverket?

**Comment by lillelars** [comment]
@bgrova du må følge opp denne nå

**Comment by bgrova** [comment]
Har vært i kontakt med Lars Inge Arnevik hos Statens Kartverk, og han skal se på hvordan dette kan fikses, altså alternativ 1.

**Comment by lillelars** [comment]
Venter nå på svar fra Statens Kartverk

**Comment by lillelars** [comment]
@bgrova Husk å purre på kartverket på nytt

**Comment by lillelars** [comment]
@bgrova fikk du purra på kartverket? :)

**Comment by lillelars** [comment]
Geonorge data fungerer som det skal og har gjort det lenge :) lukker denne.
