### ISSUE TITLE
Datasett Sammendragsboks:  Det mangler linjeskift mellom beskrivelse og formål (API-860)

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1318]
Ved registrering av datasett via vår registreringsløsning vises ikke feltene "Beskrivelse" og "Formål" adskilt. 2 stk Linjeskift mangler. 
Se fig
'
![860](https://user-images.githubusercontent.com/42966644/53010264-bec8f080-343d-11e9-9058-cd9025c45245.png)

**Comment by lillelars** [comment]
Dette var en duplikat og er fikset.
