### ISSUE TITLE
Registreringsløsning: Får ikke lov å klikke på høyre side av Begrep og Søkeord felter (API-855)

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1319]
Gjelder å fikse mouse-cursor OG at det faktisk går ann å klikke 
![855](https://user-images.githubusercontent.com/42966644/53011266-4f083500-3440-11e9-8523-d50f1a851e8c.png)
der.

**Comment by lillelars** [comment]
Duplikat - og er nå fikset.
