### ISSUE TITLE
Registreringsløsningen: Relasjoner vises ikke korrekt i dropdownlisten (API-755)

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1320]
I registreringsløsningen, i seksjon relasjoner, kan en sette opp en rekke relasjoner.  I Dropdownlisten der en velger datasett er det to utfordringer/feil: 

Listen bør være alfabetisk
Listen bør kunne vise forskjell på om datasett er publisert eller ikke
 

Problemet eksisterer i prod og er meldt inn av Roger Olsen, BRREG i mail til Joachim

Første step i eventuell utbedring er design.....

**Comment by lillelars** [comment]
Duplikat. Lukker denne.
Løses av ny Epic #2452 med tilhørende brukerhistorier
