### ISSUE TITLE
Registreringsløsningen: Unsanitized user input reflected in JSON (API-748)

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1321]
Sikkerhetstest 29. nov 2018 identifiserte svært mange funn med alvorlighetsgrad LOW.  24 funnn omhandler "Unsanitized user input reflected in JSON"  

Santitering er lagt inn i Søkeportalen, men det ser ikke ut som at dette er implementert i registreringsløsningen

Detaljer finnes i vedlagte rapport fra test mot registreringsløsningen i ST1
Planen er å kjøre ny sikkerhetstest etter at dette er vurdert/utbedret.

Se også std sjekkliste for gode sikker utviklingsmetodikk: https://confluence.brreg.no/display/FDK/Sjekkliste+for+sikker+utviklingsmetodikk

[29112018-datakatalogen-registreringsløsning-ST1-TEST1 Security Report.pdf](https://github.com/Informasjonsforvaltning/fdk/files/2879756/29112018-datakatalogen-registreringslosning-ST1-TEST1.Security.Report.pdf)

**Comment by lillelars** [comment]
utgått. Lukker denne.
