### ISSUE TITLE
Redusert sikkerhet knyttet til Sertifikatoppsett

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1322]
Sikkerhetstest 29. nov 2018 identifiserte svært mange funn med alvorlighetsgrad LOW 

Hypotesen er at en del funn her kan reduseres ved å se på konfigureringen av Sertifikatoppsett. 

Detaljer finnes i vedlagte rapport fra test mot søkeprotalen i Prod

Planen er å kjøre ny sikkerhetstest etter at dette er vurdert/utbedret.

 

Se også std sjekkliste for gode sikker utviklingsmetodikk: https://confluence.brreg.no/display/FDK/Sjekkliste+for+sikker+utviklingsmetodikk

[29112018-datakatalogen-PROD-TEST1 Security Report.pdf](https://github.com/Informasjonsforvaltning/fdk/files/2879763/29112018-datakatalogen-PROD-TEST1.Security.Report.pdf)

**Comment by lillelars** [comment]
utgått. Lukker saken.

**Comment by lillelars** [comment]
utgått. lukker saken.
