### ISSUE TITLE
Redusert sikkerhet knyttet til CallStack og misbruk av parametertype

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1323]
Sikkerhetstest 29. nov 2018 identifiserte svært mange funn med alvorlighetsgrad LOW 

Hypotesen er at antall funn her kan reduseres med konfigurering i SPRING knyttet til CallStack samt se på eventuell misbruk av parametertype (f.eks. STRING i en INTEGER eller store tall i INTEGRER)

Detaljer finnes i vedlagte rapport fra test mot søkeprotalen i Prod

Planen er å kjøre ny sikkerhetstest etter at dette er vurdert/utbedret.

 

Se også std sjekkliste for gode sikker utviklingsmetodikk: https://confluence.brreg.no/display/FDK/Sjekkliste+for+sikker+utviklingsmetodikk

 

[29112018-datakatalogen-PROD-TEST1 Security Report.pdf](https://github.com/Informasjonsforvaltning/fdk/files/2879765/29112018-datakatalogen-PROD-TEST1.Security.Report.pdf)

**Comment by lillelars** [comment]
utgått. lukker saken.
