### ISSUE TITLE
Registreringsløsningen: Missing Secure Attribute in Encrypted Session (SSL) Cookie (API-733)

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1325]
Sikkerhetstest 29 nov 2018 identifiserte et funn i Reg-løsningen 

Hypotesen er at konfigurering av SPRING kan utbedre problemet

Detaljer finnes i vedlagte rapport:
  Registreringsløsning, Side 13

[29112018-datakatalogen-PROD-TEST1 Security Report.pdf](https://github.com/Informasjonsforvaltning/fdk/files/2879790/29112018-datakatalogen-PROD-TEST1.Security.Report.pdf)
Se også std sjekkliste for gode sikker utviklingsmetodikk: https://confluence.brreg.no/display/FDK/Sjekkliste+for+sikker+utviklingsmetodikk

**Comment by lillelars** [comment]
utgått. lukker saken.
