### ISSUE TITLE
Registreringsløsningen: Cross-Site Request Forgery (API-732)

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1326]
Sikkerhetstest 29 nov 2018 identifiserte 3 funn i Reg-løsningen der to av dem også ble identifisert i Harvester.

Hypotesen er at konfigurering av SPRING kan utbedre problemet

Detaljer finnes i vedlagte rapporter:
  Registreringsløsning, Side 10

  Harvester side 8

 

Se også std sjekkliste for gode sikker utviklingsmetodikk: https://confluence.brreg.no/display/FDK/Sjekkliste+for+sikker+utviklingsmetodikk

[29112018-datakatalogen-PROD-TEST1 Security Report.pdf](https://github.com/Informasjonsforvaltning/fdk/files/2879799/29112018-datakatalogen-PROD-TEST1.Security.Report.pdf)

**Comment by KurtStian** [comment]
Ny adresse til "Sjekkliste for sikker utviklingsmetodikk": https://digdir-digitalisering.atlassian.net/wiki/spaces/INFFOR/pages/5247884/Sjekkliste+for+sikker+utviklingsmetodikk

Dokumentasjon angående CSRF:  https://docs.spring.io/spring-security/site/docs/3.2.0.CI-SNAPSHOT/reference/html/csrf.html#csrf-configure

**Comment by valosnah** [comment]
Vi burde bestille en ny sikkerhetstest, da flere av de berørte applikasjonene er endret, vi har et nytt cluster som benytter seg av cloud armor, og generelt har fjernet en rekke svakheter.

**Comment by KurtStian** [comment]
Spurte Raymond Hagen angående sikkerhetstest og om vi har vektøy for testing eller om det bør bestilles hos noen andre. Fikk følgende svar: 

«Ja, vi har verktøy, men eg trur det ville vært fornuftig å få noen eksterne å gjøre testen, siden dette er første gang etter store endringer . Det må vel ut med en anbudskonkurranse.»

**Comment by lillelars** [comment]
@valosnah jeg lukker denne saken. Vi følger opp dersom vi får bestilt ny sikkerhetstest.
