### ISSUE TITLE
Registreringsløsningen, Datasett: Validering av felt kan publiseres selv med feil url (API-710)

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1329]
ersom en legger inn feil verdi  i et felt (f.eks. ikke gyldig URL i et URL-felt) så får en opp en korrekt feilmelding om at feil utfylling. ;Men på autolagringslinja dukker det samtidig opp melding om at lagring er ok  (eller at endringen er publisert)   Denne kombinasjonen er forrvirrende for en bruker...

 

Fra Øyvind:

Et datasett validerer jo egentlig ikke hvis obligatorisk felt ikke er fylt ut, men vi må jo likevel lagre underveis i utfyllingen.
Så det er ikke rett frem å si at vi ikke skal lagre hvis det er valideringsfeil

![710](https://user-images.githubusercontent.com/42966644/53013195-6dbcfa80-3445-11e9-9079-44dfb2e0704f.png)

**Comment by sindresandvik2** [comment]
Haraldsen, Lars Martin Riiser lagt til en kommentar - 17/jan/19 14:52
Skavhaug, Terese Kunne du tatt deg tid til å se litt på dette? Og kanskej komme med noe forslag til måter vi kan håndtere dette på? Hadde også vært kjekt å vite hvor viktig du synes dette er


Skavhaug, Terese lagt til en kommentar - 22/jan/19 09:20
Når en beskrivelse ikke er publisert vil alt man gjør lagres som utkast uavhengig av om feltene validerer eller ikke. Derfor syns jeg det er ok at det står at lagring er ok. 

Når det gjelder en publisert beskrivelse som det gjøres endringer på, skal denne få ny status som "Under endring". Se skisse her: https://projects.invisionapp.com/share/FWBFRNSAM#/screens/337527418. I dag publiseres endringer på publiserte beskrivelser direkte, uten at man må trykke "publiser"-knappen først. Dette ønsker vi å unngå, men det har ikke blitt prioritert i utvikling enda. Når dette er på plass vil problemet med validering vs lagring også løses. Foreslår derfor at vi ikke lager en ny løsning på dette problemet nå.

**Comment by lillelars** [comment]
ikke gyldig lenge.r Lukker saken.
