### ISSUE TITLE
Brødsmulesti: Lenken på "Søk i Felles datakatalog" har ikke riktig design (API-467)

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1332]
Forrige steg i brødsmulestien skal være blå med understrek (lenke).

Se vedlegg
![467](https://user-images.githubusercontent.com/42966644/53019019-1b370a80-3454-11e9-9083-1ad31d8f8b51.png)
![467-2](https://user-images.githubusercontent.com/42966644/53019067-3275f800-3454-11e9-8d59-796ed7aacbf6.png)

**Comment by lillelars** [comment]
Klarer ikke gjenskape. Lukker denne
