### ISSUE TITLE
Registrere API: Feil design for melding over vellykket import av spesifikasjon

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1333]
Se design:
https://projects.invisionapp.com/share/HDMWYXXGUZ2#/screens/322308129_REGISTRERING-Import-Lenke-Success--D-

Design: https://invis.io/HDMWYXXGUZ2#/322308129_REGISTRERING-Import-Lenke-Success--D-

**Comment by lillelars** [comment]
Denne utgår ettersom vi har nytt design uten import av spesifikasjon.
