### ISSUE TITLE
Endre tekst i registreringsløsning - antall datasett / apier oversiktsside kataloger (API-460)

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1335]
Oversiktside kataloger: Nå står det "0" dersom det ikke er registrert noe i katalogene. det skal stå "Ingen [datasett/API-er]"

 
![460](https://user-images.githubusercontent.com/42966644/53020647-a4037580-3457-11e9-923e-795c5689381b.png)

02/nov/18 12:24
Fortsatt feil.

**Comment by lillelars** [comment]
Dette er fikset.
