### ISSUE TITLE
BUG REG: Opphav og ferskhet --> Opphav: Firkantene ser ut som checkboxer. Skal se ut som radioknapper. (API-426)

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1337]
Her er det viktig å huske at du skal kunne fjerne valget også (ettersom det ikke trenger å være obligatoriske valg).

Sundsbø, Lene lagt til en kommentar - 11/feb/19 11:36
Vi har radioknapper andre steder i løsningen, men hvis det skulle være ønskelig med skisser kan denne brukes. Her er løsningen forøvrig en litt annen, men radioknappene ser ut som før:
https://invis.io/N9Q9157SD3U#/343911179_DATA-REG-Opphav-ferskhet-Ikke-Utorativ--D-
<img width="419" alt="426" src="https://user-images.githubusercontent.com/42966644/53020990-779c2900-3458-11e9-8dfc-e4775e53a2ad.PNG">

**Comment by lillelars** [comment]
Dette håndteres som ny feature ettersom vi da også må opprette et eget valg dersom bruker "ikke vet opphav".

lukker derfor denne.
