### ISSUE TITLE
BUG REG: Begrep og søkeord --> Søkeord: Når man har skrevet ca 10 tegn forsvinner teksten til venstre. Lange ord kan dermed ikke leses før man trykker enter (API-424)

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1338]
Sundsbø, Lene lagt til en kommentar - 30/jan/19 16:00 - Redigert
Ser ikke helt at det er nødvendig med designskisse, siden dette skal oppføre seg som alle annen tekst  Men her er det likevel:
https://projects.invisionapp.com/share/7RQ8ZOGAUKF#/screens/342809831_REG-Api-Tilleggsinfo-Datasett-Ingen-Treff--D-
<img width="411" alt="424" src="https://user-images.githubusercontent.com/42966644/53021255-1759b700-3459-11e9-836f-2ee553315f55.PNG">

**Comment by lillelars** [comment]
Dette er fikset
