### ISSUE TITLE
Registreringsløsning - inngangsknapper - små designendringer (API-350)

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1340]
Etter gjennomgang av våre design/UX folk må disse detaljene justeres:
 # Teksten etter antall beskrivelser endres til  xx beskrivelser i stedet for xx Datasett eller xx API. Altså likt for både datasett-knappen og API-knappen. [ ]
 # Pass på at ordet "beskrivelser" da tilpasses entall og flertall. ( på ALLE språk - skildring/description) [ ]
 # Bruk "Ingen beskrivelser" i stedet for 0 beskrivelser [  ]

 # Pass på at font er lik for begge knappene  (Størrelse og farge) [X]
 # Når en forminsker størrelsen på skjermbildet slik at knappene listes opp under hverandre må det være mellomrom mellom knappene på samme måte som det er når knappene står ved siden av hverandre    Se screenshot [  ]

![350-1](https://user-images.githubusercontent.com/42966644/53021877-753ace80-345a-11e9-9ec5-c68d8ed45aa5.png)

![350-2](https://user-images.githubusercontent.com/42966644/53021914-8388ea80-345a-11e9-9ea4-85404028eda2.png)

**Comment by lillelars** [comment]
Fikset. Lukker denne.
