### ISSUE TITLE
Nasjonal Felleskomponent på ulike linjer (API-173)

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1342]
Nasjonal felleskomponent skal vises til høyre for tittel (uavhengig av lengde på tittel) - se bildet under:

![173-1](https://user-images.githubusercontent.com/42966644/53022939-8dabe880-345c-11e9-84df-4a9d04bebeb2.png)
![173-2](https://user-images.githubusercontent.com/42966644/53022945-900e4280-345c-11e9-935d-e32c4034d5e5.png)

**Comment by lillelars** [comment]
Denne ligger nå alltid på linje 2. Lukker derfor denne.
