### ISSUE TITLE
OIDC klient registrering hos ID-porten (op2)

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1357]
Registrere to OIDC klient fra idporten:
https://difi.github.io/idporten-oidc-dokumentasjon/oidc_func_clientreg.html

1.til prod, 
redirecturl = https://sso.fellesdatakatalog.brreg.no/auth/realms/fdk/broker/oidc/endpoint

2.til test,
redirecturlene: til alle testmiljøene vi har og i tillegg http://localhost:8084

Vi bruker ikke logout (for vi vil ha lengere sessionene enn difi har), logo kunne vært fint

Kontrakt og konfigurasjon av OIDC integrasjon med IdPorten

**Comment by markkopaas** [comment]
Idporten integration test with OIDC

https://difi.github.io/idporten-oidc-dokumentasjon/oidc_api_admin.html

https://difi.github.io/idporten-oidc-dokumentasjon//oidc_auth_server-to-server-oauth2.html

Vi trenger å registrere client. 
Hver klient har sitt eget tillatt listen av redirect-uri. Så vi må registrere to klient - en som er begrenset til prod-uris, og den andre som vi bruker til test og dev.

Vi har to valg til å autorisere en klient - nøkkelpar eller shared secret. Shared secret må utbyttes hver 180 dag.

**Comment by bgrova** [comment]
Må vi integrere alle testmiljøene mot idporten, eller holder det å kun integrere it1-miljøet, slik vi gjør for SAML?

**Comment by bgrova** [comment]
Bestilling for prod, ut1, st1, it1 og localhost sendt. dette er for integrasjon mot udportens testmiljø (VER2). Vi må senere lage en ny bestilling for prod-miljøet. Vi setter opp en oidc-integrasjon for prod nå mot idportens test for å prøve ut ting. SAML-integrasjonen for prod fortsetter jo å eksistere i parallell uansett.

**Comment by bgrova** [comment]
Tilgangene til idporten ver2 miljø (test) er bestilt og levert. Lager ny sak for bestilling av tilgang til prod,
