### ISSUE TITLE
Refaktorering av registrering API-bruk

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1365]
Dette går ut på å migrere hele registrerings-frontend.
Gå igjennom Registration-frontend og benytte nytt IDP
 - [x] implementere dependency injecton, så at tjenestene kan konfigureres før bruk
 - [x] implementere configuration som injectable 
 - [x] isolere ut referenceDataApi som selvstengig tjeneste og køble det til search backend instedet
 
--datasetregistrering
 - [x] dataset-registration-api modul
 - [x] delete, 
 - [x] patch
 - [x] post create (fra dataset-list-page/items-list/item-list.component.jsx)
 - [x] post import (fra dataset-list-page/items-list/item-list.component.jsx)
 - [x] put (fra dataset-list-page/form-catalog/async-catalog-dataset.js)
 --apiregistrering
 - [x] isolere ut api-registration-api 
 - [x] patch (fra api-registration-page/async-patch/async-patch.js)
 - [x] redux/modules/apiCatalog.js: fetchApiCatalogIfNeededAction, postApiCatalogAction
 - [x] delete (fra api-registration-page/api-registration-page-pure.jsx)

optional - skal utsettes, forventer ikke autoriseringsproblemer, selv om det går gjennom samme proxy:
search-api
publisher-api

**Comment by markkopaas** [comment]
Dependency injection I react. Som testbarhet prinsipp, alle stateful tjenestene skulle bruke dependency injection, så at i test, hele input kunne være gitt, uten å stole på globale variabler. 

Dependency injection I komponentene kan gjøres ved hjelp av React.Context og hooks. 

Akkurat nå bruker vi den teknikk bare til store (redux connect), men på samme måte skulle vi håndtere andre globale variabler: - lokalisering, api, autorisering, config.

Alternativløsning kunne være at alt lagres i redux. (localisation, config, auth). Her auth ligger I config, så api tjeneste kan være stateless.
