### ISSUE TITLE
Teknisk gjeld: ikke bruke maven til å build non-java prosjekter (API-445)

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1373]
Akkurat nå har vi allerede bygger javascript applikasjoner uten maven.

Andre non-java prosjekter skulle også bygget fra Dockerfile i stedet av maven.

 Jeg anbefaler å begynne fra ./runAll.sh skript å sjekke hva må endres.

**Comment by markkopaas** [comment]
under /applications vi har flere kataloger, men hovedstruktur er at alle der er bygget med maven. “maven clean install”. 
Vi har allerede endret byggeprosess til frontend, men de katalogene fortsett ligger der. Jeg anbefaler at /applications skal stå maven-bygget, mens vi flytter de andre typer  ut- frontend og docker-bygd. På den måte har vi 

/applications  - bygget ved maven og docker-maven-plugin
/applications-frontend/(2) - bygget ved dockerfile
/applications-external/(nginx*,fuseki, elastic). - bygget ved dockerfile

når de andre applikasjontyper er bevegd ut, vi kunne endre også  /applications til /applications-java

**Comment by markkopaas** [comment]
bestemte å gå videre med en katalog applications, men hver application selv bestemer byggemodus
