### ISSUE TITLE
Garantere at lagret data er sanitert mot html injection og xss attacks (API-834)

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1379]
Akkurat nå har vi implementert sanitering på et valg av feltene.

Problemet er, at server kan ikke garantere, at klientene skal bruke sikkere funksjone til å render, derfor skulle server uansett sanitere alle feltene.

Finn en løsning å garantere at alle feltene er sanitert.

**Comment by markkopaas** [comment]
Frontend kode garanterer at feltene ble rendret i sikker måte, det er evne til react.
