### ISSUE TITLE
Sonar: Fikse alle Blockers og Criticals (API-898)

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1382]
I FDK-løsningen i dag har vi ca 6 Blockers og 76 Criticals.

Se:
http://35.228.110.43/issues?resolved=false&severities=BLOCKER%2CCRITICAL

**Comment by thomasnokleby** [comment]
Har merget inn PR som skal gjøre dette.

**Comment by sindresandvik2** [comment]
Utgår fordi vi skal bytte til Sonar Cloud. Lukkes.
