### ISSUE TITLE
Sjekke deployinformasjon i tjeneste på en raskere måte (API-927)

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1386]
Grunn: Det er ofte litt vanskelig å sjekke hvilke version er faktisk i bruk i test eller i prod.

potensielle løsningere:

1) vise synlig byggenummer i GUI (det hjelper hvis bruker sender  inn screenshot)

2) frontend ha en hemmelig console command til å se byggeinformasjon

3) api-ene har health endepunkt, som skulle vise version

**Comment by markkopaas** [comment]
search har dette i env.json: "CONTAINER_IMAGE": "eu.gcr.io/fdk-infra/search:2688bcd3ed5264551eb58531e06b27dafe0ef1d8"

hvis det ser ut som fornyftig ide, kan vi gå videre med det.

I api, vi kan bruke spring health til å vise litt informasjoon blant ant miljøvariablene, som kan inneholde version info
