### ISSUE TITLE
Knytte APIer til Datasettbeskrivelser

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1390]
Som: datasetteier
Ønsker jeg å: legge til api-beskrivelser fra api-katalogen som distribusjoner til datasettet
Slik at: man unngår dobbelregistrering

Relatert til epos: #36

Design finnes her:
Registreringsløsning:
https://projects.invisionapp.com/share/HDMWYXXGUZ2#/screens/333599400

Visning i Portal:
https://projects.invisionapp.com/share/HDMWYXXGUZ2#/screens/321530319

- [x] Testdesign

- [x] Testgjennomføring  (Se vedlagte regneark)

[1390.xlsx](https://github.com/Informasjonsforvaltning/fdk/files/3029267/1390.xlsx)

**Comment by joachim-me** [comment]
Godkjent, men en feil må fikses #1656.
