### ISSUE TITLE
Registrere API > Oversiktsside: "Import OK"-melding på kataloghøsting bør ikke vises hele tiden

### ISSUE THREAD

**Issue by tereseskavhaug** [Altinn/fdk#1399]
![screen shot 2019-02-22 at 11 57 34](https://user-images.githubusercontent.com/46490475/53238259-2038cb80-3699-11e9-947b-92ee68024bb8.png)

At OK-meldingen vises hele tiden er forvirrende fordi:

1) man ikke automatisk forstår at det handler om kataloghøstingen
2) det er rart å få en OK-melding uten at man har gjort noe
3) man ikke vet når det ble høstet sist
4) meldingen er i konflikt med meldingen man får dersom man sletter et API:

![screen shot 2019-02-22 at 11 53 39](https://user-images.githubusercontent.com/46490475/53238029-86711e80-3698-11e9-9560-7455c587197b.png)

Forslag: Vi viser OK-meldingen kun første gang man høster fra katalog/har endret katalogURL-en. Etter det vises det kun feilmelding dersom noe går galt.

**Comment by lillelars** [comment]
Nytt design og implementasjon av datatjenesteregistrering. ikke gyldig lenger.
