### ISSUE TITLE
Utforsk om vi kan bruke "relasjons"-struktur fra dcat-standard dct:relation

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1409]

**Comment by bgrova** [comment]
Oppsummering:
* dct:relation tillater kobling til en vilkårlig RDF-ressurs
* den er i bruk i dag - til å peke til andre datasett
* Veildederen til registrering av datasett er strengere enn standarden: den sier at dct:relation skal peke til et datasett
Konklusjon: dct:relation er ikke egnet

**Comment by bgrova** [comment]
Bruk av dcat:Distrivbution, med lenke til API-katalog i attributtet dcat:AccessUrl:
* Denne kan allerede være i bruk i datasett vi høster, og vil ikke nødvendigvis peke til en ressutrs vi kan parse
* Hvis denne brukes, må vi detektere at dcat:AccessUrl peker til en oppføring i API-katalogen og spesialbehandle den, for å kunne trekke ut attributtene vi skal vise på detaljsiden for datasett.
Konklusjon: Dette er ikke en optimal løsning, og bør unngås hvis mulig.

**Comment by bgrova** [comment]
Øystein Åsnes ved Difi anbefaler oss å se på W3C sitt utkast til ny versjon av DCAT-standarden. Der er det tatt inn klasser for å representere API bedre. https://w3c.github.io/dxwg/dcat/#Class:Data_Distribution_Service

Det kan se ut som klassen Data Distribution Service  potensielt kan benyttes. Denne er ikke implementert i versjonen av DCAT som vi benytter i dag, men det er sannsynligvis mindre risikabelt å benytte W3C sitt forslag til implementasjon, enn å lage noe helt eget.

**Comment by bgrova** [comment]
Forslag til representasjon i henhold til ny versjon av DCAT-standarden: 
dcat:distribution   [ a dcat:Distribution ;
 dct:type         "API" ;
 dcat:accessUrl <https://fellesdatakatalog.brreg.no/apis/a6025ea0-7685-432e-86e7-bb59dce51192> ;
 dcat:accessService [ a dcat:DataDistributionService ;
    dct:title "Summert spesifisert skattegrunnlag API"@nb;
    dct:publisher <http://data.brreg.no/enhetsregisteret/enhet/974761076> ;
    dct:description "Spesifisert summert skattegrunnlag inneholder summert informasjon om en skatteyters inntekt, formue og fradrag og formuesfradrag, med spesifikasjoner"@nb;
    dcat:endpointDescription [ a foaf:Document, skos:Concept ;
      dct:source "https://fellesdatakatalog.brreg.no/apis/a6025ea0-7685-432e-86e7-bb59dce51192" ;
    ] ;
] ;

**Comment by bgrova** [comment]
Det later til at endelig utforming av denne beskrivelsen enda ikke er 100% spikret, men vi gjør det slik:
dcat:distribution   [ a dcat:Distribution ;
  dct:type         "API" ;
  dcat:accessService [ a dcat:DataDistributionService ;
	dct:title "Tittelen til API-et fra API-katalog"@nb;
	dct:publisher <peker til foaf:Agent som representerer utgiveren av API-et> ;
	dct:description "Beskrivelsen av API-et fra API-katalog"@nb;
	dcat:endpointDescription [ a foaf:Document, skos:Concept ;
	  dct:source "https://fellesdatakatalog.brreg.no/apis/<identifikatoren til API-et i API-katalog>" ;
	] ;
] ;
