### ISSUE TITLE
Backend: Implementer lookup for valg av APIer

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1410]

**Comment by bgrova** [comment]
Struktur for API lookup er implementert i datastore, med følgende struktur:
Ett nytt element er lagt til i distritbution: dcatapi:accessService.

dcat:distribution [ a dcat:Distribution ;
	dct:type "API" ;
	dcatapi:accessService [ a dcatapi:DataDistributionService ;
		dct:title "Tittelen til API-et fra API-katalog"@nb;
		dct:publisher ;
		dct:description "Beskrivelsen av API-et fra API-katalog"@nb;
		dcatapi:endpointDescription [ a foaf:Document, skos:Concept ;
			dct:source "https://fellesdatakatalog.brreg.no/apis/" ;
		] ;
	] ;
] ;
