### ISSUE TITLE
Backend: Datasett - verifiser at vi har statistikk som ønsket

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1414]

**Comment by thomasnokleby** [comment]
Førstepri: Å få opp tellingen av datasett, apier og begrep, uansett type og egenskaper:

Datasett:
https://www.ut1.fellesdatakatalog.brreg.no/datasets
Dra ut hits->total

Apier:
https://www.ut1.fellesdatakatalog.brreg.no/api/apis/
Dra ut "total"

Begrep:  https://www.ut1.fellesdatakatalog.brreg.no/api/concepts
Dra ut page -> totalElements
