### ISSUE TITLE
Backend: API -Implementer spørringer for statistikk om APIer

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1415]
Vi trenger liste over data (altså disse spørringene):
Se design for hvilke spørringer vi trenger:
https://projects.invisionapp.com/share/PWQNNOAQSUD#/screens/349784520

**Comment by thomasnokleby** [comment]
Vi må telle:
antall apier (totalt)
antall apier som er åpne for alle
antall apier som har åpen lisens
antall apier som er gratis å bruke
summary bøttet på format, med telling og sortering
summary bøttet på publisher
summary bøttet på api-kataloger (med telling på antall apier hentet fra hver)

**Comment by thomasnokleby** [comment]
Noen forslag til hvordan dette kan returneres til frontend:

Antall APIer med Åpen tilgang (apis/?aggregations=openAccess)
Der de med ikke åpen tilgang ligger bøttet under false
"aggregations": {
        "openAccess": {
            "buckets": [
                {
                    "key": "MISSING",
                    "count": 8
                },
                {
                    "key": "true",
                    "count": 3
                }
            ]
        }
    }
Antall apier med åpen lisens (/apis/?aggregations=openLicence)
Der de med ikke åpen lisens ligger bøttet under false
 "aggregations": {
        "openLicence": {
            "buckets": [
                {
                    "key": "MISSING",
                    "count": 8
                },
                {
                    "key": "true",
                    "count": 2
                },
                {
                    "key": "false",
                    "count": 1
                }
            ]
        }
    }

Antall apier som er gratis å bruke (/apis/?aggregations=freeUsage)
Der de som ikke er gratis å bruke ligger bøttet under false
 "aggregations": {
        "freeUsage": {
            "buckets": [
                {
                    "key": "MISSING",
                    "count": 8
                },
                {
                    "key": "true",
                    "count": 3
                }
            ]
        }
    }

Antall forskjellige virksomheter som har API-er i FDK:
 "aggregations": {
        "publisher": {
            "buckets": [
                {
                    "key": "count",
                    "count": 1
                }
            ]
        }
    }

**Comment by thomasnokleby** [comment]
Her er da alt utenom siste (summary bøttet på api-kataloger (med telling på antall apier hentet fra hver)) implementert og merget inn.

**Comment by thomasnokleby** [comment]
Siste spørring i PR nå
