### ISSUE TITLE
Backend: Begrep -Implementer spørringer for statistikk om Begreper

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1416]

**Comment by markkopaas** [comment]
Det var to del av statistikk som manglet.
1) antall av begrep per publisher (løst, i pr)
2) antall av begrep bruk i datasett (se videre)

Vår grunnlegende design av systemet er at begrepsøk og datasetsøk er frakoblet fra hverandre i separate mikrotjenester. Vi har et par løsningideer:
1 - frontend styrer spørringer - henter alle filtrerte begrepkoder og kjører spørring til.
2 - integrere api-ene (samme som 1, men server kjører spørring)
3 - endre datastruktur i dataset søketjeneste. så at slik spørring kunne gjørt der i stedet.
4 - dele datastrukur mellom tjenestene. no-no.

Bare 1 og 2 er praktiske. Jeg anbefaler at siden den funksjonalitet er ikke performance-kritisk (den nummer skal ta et par sekund til å spørre., vi gjør enkle 1 først. Hvis senere bedre performance trenges, vi kan gjøre 2).
