### ISSUE TITLE
Frontend: Rapporter - vise content for API 

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1418]

**Comment by oyvindis** [comment]
Foreløpig viser jeg ikke antall virksomheter som har API-er og heller ikke listen over virksomhetens API-kataloger.

Data fra backend er litt feil for api, blir gitt som orgPath, men må komme på katalognivå. F.eks. 'Fylke' er eget orgPath, men skal ikke regnes som virksomhet. Data må gis som for datasett.

**Comment by sindresandvik2** [comment]
Test ferdig. Ein feil rapportert!
