### ISSUE TITLE
Frontend: Rapporter Datasett - vise statistikk for rapporter

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1419]

**Comment by oyvindis** [comment]
For datasett mangler vi:
'begrensede datasett med distribusjoner'
'begrensede datasett uten distribusjoner'
'antall distribusjoner av type API'
'antall distribusjoner av type nedlastbar fil'
'antall distribusjoner av type feeds'
'autorative kilder'
'de 5 mest brukte begrep i datasett'

'antall ulike virksomheter' på en orgPath som har datasettbeskrivelser
