### ISSUE TITLE
Registreringsløsningen:  Etter en stund hopper siden til toppen  (API-972)

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1423]
"AvOgTilFeil"

Dersom en venter en liten stund og så gjør et valg i enten statusfeltet eller eller de andre vilkårsfeltene hopper hele siden til toppen UTEN at siste registrering er lagret.

**Comment by oyvindis** [comment]
Det er gjort refaktorering som jeg tror har fjernet dette problemet. Kan retestes og evt. lukkes.

**Comment by sindresandvik2** [comment]
Retestet OK I UT1
