### ISSUE TITLE
KRR API ikkje synleg

### ISSUE THREAD

**Issue by livarb** [Altinn/fdk#1433]
Oppføringa for API for Kontakt- og reservasjonsregisteret (KRR) er ikkje lenger synleg i FDK: https://fellesdatakatalog.brreg.no/apis
Ser ut til å vere ein bug. I registreringsløysinga så er API-et publisert.

**Comment by livarb** [comment]
Prøvde "Hent ny spesifikasjon" via registreringsløysinga og fekk ein feil:
![image](https://user-images.githubusercontent.com/3617256/53476388-901ccc80-3a72-11e9-8a7a-584cfea7de88.png)
URL til Swagger-spec: https://oidc.difi.no/kontaktinfo-oauth2-server/rest/apis

Har prøvd å validere fila via https://editor.swagger.io/ og det ser ut til å vere nokre feil.
Skal sjå på å rette feila.

**Comment by livarb** [comment]
Er det planar om å gje brukar meir tilbakemelding på kva som feila enn den meldinga eg fekk opp?
F.eks. om lenka ein oppgir ikkje er rett format (ikkje swagger/open api), eller om det feilar valideringar. Kanskje peike brukaren til editor.swagger.io for å sjekke kva som er feil.

**Comment by livarb** [comment]
I registreringsløysinga står API-beskrivinga som "Publisert", utan at det står nokon stad at det ikkje er med i katalogen. Foreslår at det kan få ny status. F.eks. "Import feila". Gjerne få fram at på grunn av dette så er ikkje oppføringa med i API-katalogen.

**Comment by joachim-me** [comment]
@livarb Vi har ingen planar om å gjere feilmeldingane her betre. Det er ein god ide å peike brukaren vidare til eigna valideringsverktøy.
Når det gjeld feilen om at API-skildringa er publisert, vil ikkje dette vere eit problem framover. Ei løysing for tilfellet ditt er å avpublisere, hente ein gyldig API-spesifikasjon og publisere på nytt
