### ISSUE TITLE
Informasjonsmodeller fra Tjeneste 3.0 - lagre og få inn modellene i vår løsning (API-881)

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1435]
- Utforsk hvor mye tid dette faktisk tar.....
- Laste opp informasjonsmodellene til "Bjørns Bucket"
- Sørge for at vi også får tilbyder og tittel på modellene
- Høst inn modeller til søkeløsning
- (mulig tilpasse frontend)

**Comment by sindresandvik2** [comment]
Sjekk feil #1490

**Comment by sindresandvik2** [comment]
Testet OK i UT1 ved å foreta en rekke stikkprøver.  2 feil rapportert.
