### ISSUE TITLE
Legg lenke til dokumentasjon i https://fellesdatakatalog.brreg.no/about

### ISSUE THREAD

**Issue by stigbd** [Altinn/fdk#1438]
Det fins mykje nyttig informasjon of Felles datakatalog i våre dokumentasjonssider på https://informasjonsforvaltning.github.io/
For at disse skal vere lettare å finne, bør det leggast inn ei lenke til dokumentasjonssidene under https://fellesdatakatalog.brreg.no/about

**Comment by sindresandvik2** [comment]
grei liten sak dette Lars!

**Comment by thomasnokleby** [comment]
Sindre, denne er merget nå, se etter link på about-siden, og en bitte liten tekst på norsk, nynorsk og engelsk.

**Comment by sindresandvik2** [comment]
Linken mangla!

**Comment by sindresandvik2** [comment]
OK i UT1,
