### ISSUE TITLE
Registreringsløsningen, API: Innhøsting fra katalog gir tomme enkelt-API-beskrivelser 

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1440]
Dersom en høster via katalog dukker det opp like mange tomme linjer i enkelt-API-oversikten som antall ulovlige API-beskrivelser forsøkthøstet via katalog.
Steg for gjenskapåing av feilen: 
1. Rydd bort alle enkeltstående API-beskrivelser uten tittel.
2. KJør innhøsting via katløaog og bruk denne katalogen:  https://raw.githubusercontent.com/Informasjonsforvaltning/fdk-testdata/master/testdata/APIkatalog3_Test.ttl
3. Da vil det dukke opp 2 enkelt-API-beskrivelser utyen data. 

Vedlagt er to skjermdumper
A:   Før innhøsting
![image](https://user-images.githubusercontent.com/42966644/53409747-0b727580-39c2-11e9-946b-744cd869d77c.png)

B: Etter innhøsting
![image](https://user-images.githubusercontent.com/42966644/53409927-9eabab00-39c2-11e9-827e-bef6a7e3f8f2.png)

**Comment by lillelars** [comment]
Helt ny løsning på dette nå. Lukker saken.
