### ISSUE TITLE
Begrep: Dataset skal vises på detaljsiden til Begrep (API-756)

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1449]
Se nederst på design:

https://projects.invisionapp.com/share/3SRCN149CQN#/screens/378074326

- [x] Testdesign

- [x] Testgjennomføring
[1449.xlsx](https://github.com/Informasjonsforvaltning/fdk/files/3540953/1449.xlsx)

**Comment by sindresandvik2** [comment]
Test ferdig,  Bug fixet!  Klar for review!
