### ISSUE TITLE
Feil i søk

### ISSUE THREAD

**Issue by henrikpaus** [Altinn/fdk#1455]
Feil i søk. Ved søk på "Brønnøysundregistrene" gis det 4 treff i API-katalogen. Dette ser ut til å stemme. Ved søk på "direktoratet for forvaltning og IKT" gis det 16 treff, noe som for øyeblikket (27.02.2019) er alle tilgengelige APIer, og ingen av dem leveres av Difi. 
Testet et par andre søk. Treff i API-katalogen: "hei" gir 0 treff som forventet, "Oslo kommune" gir 10 treff og "en tilfeldig søkestreng" gir 12.

**Comment by sindresandvik2** [comment]
@henrikpaus  Vi jobber kontinuerlig med å finstille søkesiden og vi tar gjerne imot ideer ang. hvordan søket best kan optimaliseres. Se forøvrig denne brukerhistorien i vårt behovsprosjekt:  https://github.com/Informasjonsforvaltning/behov/issues/54

Det du nevner i denne "issuen" kan forklares: 
Søk på "direktoratet for forvaltning og IKT" returnerer 16 treff for ordet "for" dukker opp i alle forekomstene. Dersom du legger til gåseøyne rundt hele søkesetningen skal du få null treff siden en da søker etter treff på hele strengen. 
Søk på Oslo kommune gir 10 treff fordi det ordet kommune går igjen i 10 beskrivelser. 

Denne issuen blir nå lukket.
