### ISSUE TITLE
Feil padding 

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1470]
Venstremenyen for teksten i TWITTER-visningen nederst på søkesidene er ikke på linje med venstremenyen i listen ovenfor  (Sammendragsboksene) 
I flg Lene bør det også benyttes samme padding som ovenfor!

**Comment by fheitmann** [comment]
Jeg forstod ikke beskrivelsen av feilen, og trenger en skjermdump (eller en reformulering!).

**Comment by lillelars** [comment]
@fheitmann mente du sa i går at denne ferdig var ferdig? Hvis det stemmer må du flytte oppgaven videre - så får Sindre testet skikkelig

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
