### ISSUE TITLE
Uødvendig lenke fjernes

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1471]
Under Twiitter informasjonen vises en lenke "innebygg". Denne bør fjernes fordi:
- Teksten sier lite 
- Hva skal bruker med denne funksjonen her? 
Dessuten fungerte ikke lenken i første runde (Dukket først opp på 3. forsøk.... ??)
Godkjent av Joachim

![image](https://user-images.githubusercontent.com/42966644/53635658-175a7380-3c1e-11e9-8597-77c881db7e0d.png)

**Comment by fheitmann** [comment]
Dette er ikke mulig å fjerne med Twitter sin iframe. Det er mulig dersom man bruker tid (flere dager) på å hente tweets til en backend, og deretter viser disse.

**Comment by sindresandvik2** [comment]
Won't fix.
