### ISSUE TITLE
Alias-URL til Felles begrepskatalog

### ISSUE THREAD

**Issue by OleVaage** [Altinn/fdk#1472]
Som bruker av felles begrepskatalog
Ønsker jeg en forståelig lenke til Felles begrepskatalog, f. eks begrepskatalog.brreg.no, eller et eget domenenavn, fellesbegrepskatalog.no
Og at Felles begrepskatalog blir mer synlig for omverdnenen gjennom metadata, titler og namedropping
Slik at: jeg kan lenke til Felles begrepskatalog ifm kommunikasjon og markedsføring 
Slik at: Felles begrepskatalog blir synlig i f. eks Google søk

**Comment by sindresandvik2** [comment]
Denne bør vurderast saman med https://github.com/Informasjonsforvaltning/fdk/issues/1457

**Comment by marittor** [comment]
@lillelars Hvis denne skal tas via behovsprosjektet er det vel best at jeg kloner den (move), slik at jeg får lagt på korrekte labels osv?

**Comment by lillelars** [comment]
Terje følger denne opp ved behov. Lukker saken fra vår side.
