### ISSUE TITLE
Feil publisert-dato for begreper

### ISSUE THREAD

**Issue by marittor** [Altinn/fdk#1475]
"Publisert i Felles datakatalog" dato xx.xx.xxxx gir ikke mening. Det står at begreper som er publisert for en tid tilbake også er publisert med dagens dato, 04.03.2019. Det vi bør kunne se er første publiseringsdato, og sist endret.

![publisert dato feil](https://user-images.githubusercontent.com/33412376/53717531-bc609080-3e58-11e9-90da-4307d93499d5.JPG)

**Comment by thomasnokleby** [comment]
Jeg ser at firstHarvested og lastHarvested alltid var lik. Det er nå korrigert, testet ok hos meg og i PR

**Comment by sindresandvik2** [comment]
Retestet OK i UT1.

Nåværende First harvested dato vil leve videre, men datoen vil heretter ikke bli endret ved nye høstinger
