### ISSUE TITLE
Opphavfilter virker ikke

### ISSUE THREAD

**Issue by joachim-me** [Altinn/fdk#1476]
Huker av et valg, ingen datasett vises.

**Comment by sindresandvik2** [comment]
Feilen er også gjenskapt i UT1.

**Comment by oyvindis** [comment]
Feilsøkt denne. Endepunkt for datasett ser ikke ut til å gi riktig når provenance gis som parameter, f.eks.:
/datasets?provenance=NASJONAL

**Comment by sindresandvik2** [comment]
Fikset i annen task!  Fungerer OK i IT1
