### ISSUE TITLE
Registreringsløsningen:  Feltet "Format" under Distribusjon har alt for dårlig brukergrensesnitt

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1477]
Dersom man skriver inn, eller kopierer inn, et gyldig format i feltet vises kun et kort utsnitt av teksten.  For at hele teksten skal vises og for at verdien til slutt skal bli lagret må bruker nå trykke TAB eller Enter.   Dette er ikke intuitivt for en bruker og må utbedres. 

Problemstillingen er nå også meldt inn av bruker Roger Olsen i Brreg: 
_Feltet hvor man kan legge inn format under Distribusjon Format har begrenset plass og utnytter ikke hele feltet.   Excel blir for eksempel EXCE. Om vi legger inn en L etter EXCE, forsvinner J i JSON._

Se #1341

**Comment by lillelars** [comment]
Denne er en duplikat og er nå løst. Lukkes.
