### ISSUE TITLE
Noen infromasjonsmodeller feiler

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1490]
Etter import av over 500 informasjonmodeller via Tjeneste 3.0 er det noen få informasjonmodeller som feiler når en prøver å gå inn på detaljbildet.  (Det er ekstra dumt at dette skjer med den informasjonmodellen som tilfeldigvis dukker opp øverst i usortert liste)
Feilmelding ser slik ut: 
![image](https://user-images.githubusercontent.com/42966644/54014272-62bfd500-417c-11e9-96f3-67f393ed0fc1.png)

Dette gjelder: 
RR-0004 Årsregnskap for skadeforsikring
RR-0007 Årsregnskap for verdipapirfond
RR-0006 Årsregnskap for pensjonsforetak
RR-0005 Årsregnskap for livsforsikring
... og sannsynligvis flere i serien RR fra Registerenheten i Brønnøysund

RF-1030PSA
RF-1030PSAN
Søknad om ferdigattest

Har sjekket ca 50 av de 515 som ble importert.

**Comment by dskogan** [comment]
Ikke mye å gå på Sindre. Kan ikke si hvorfor det er slik. Mener vi produserer gyldig jsonSchema. Burde ikke denne feilen bli funnet ved import og ikke ved åpning. Hva er detaljene. Når det er sagt så er det noen skjemaer som er spesielle og f.eks. bruker xsd:choice. Da bruker vi OneOf i jsonSchema. Arv håndeteres med AllOf. Så hvis dere ikke har støtte for å lese disse kan det være en årsak til feilen. 

Men fint om det kan registreres noe mer detaljer. Hva skjer hvis du trykker på Detaljer?

**Comment by sindresandvik2** [comment]
Nå mener Thomas at han fant en fellesnevner som han kanskje mener kan fikse det.  Jeg kommer tilbake med flere detaljer dersom det fortsatt er en utfordring.

Sindre

Fra: David Skogan <notifications@github.com>
Sendt: fredag 8. mars 2019 10:51
Til: Informasjonsforvaltning/fdk <fdk@noreply.github.com>
Kopi: Sandvik, Sindre <extssa@brreg.no>; Author <author@noreply.github.com>
Emne: Re: [Informasjonsforvaltning/fdk] Noen infromasjonsmodeller feiler (#1490)


Ikke mye å gå på Sindre. Kan ikke si hvorfor det er slik. Mener vi produserer gyldig jsonSchema. Burde ikke denne feilen bli funnet ved import og ikke ved åpning. Hva er detaljene. Når det er sagt så er det noen skjemaer som er spesielle og f.eks. bruker xsd:choice. Da bruker vi OneOf i jsonSchema. Arv håndeteres med AllOf. Så hvis dere ikke har støtte for å lese disse kan det være en årsak til feilen.

Men fint om det kan registreres noe mer detaljer. Hva skjer hvis du trykker på Detaljer?
