### ISSUE TITLE
Registrere tjenestetype på et API

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1492]
Som: tilbyder av et api
Ønsker jeg å: registrere at et api er av en viss type (standard)
Slik at: det er mulig å filtrere api'er på standarden

Realiserer: https://github.com/Informasjonsforvaltning/behov/issues/38

Lenke til design: https://projects.invisionapp.com/share/7RQ8ZOGAUKF#/screens/344401214
Lenke til overordna arkitektur: https://informasjonsforvaltning.github.io/SA_Informasjonsforvaltning/f4212a30-53d0-4c27-a682-4f88d6c692c8/views/6fc0f5aa-e7df-4765-b5bb-c0fd695c35dc.html

- [x] Testdesign

- [x] Test lagring av begge tjenestetypene

- [x] kontrollert av UX/Design

- [x] kontroller i Chrome, IE , Edge og Safari

Egenskap:
Brukerhistorie:
Som tilbyder av et api ønsker jeg å registrere at et api er av en viss type (standard) slik at det er mulig å filtrere api'er på standarden
Akseptansekriterier:
⦁	Som tilbyder av API-beskrivelsen må en kunne velge tjenestetype det vil si at den realiserer en standard når API-beskrivelsen registreres.

Dekkes ikke:

Referanser:

Scenario: Registrere tjenestetype for en API-beskrivelse
Når bruker redigerer en API-beskrivelse
Og bruker velger tjenestetype lik "Kundeforhold"
Så skal tjenestetype bli lagret på API-beskrivelsen

**Comment by sindresandvik2** [comment]
Bokmål | Nynorsk | Engelsk
-- | -- | --
Tjenestetype | Tenestetype | Type of Service
Tjenestetype (standard) | Tenestetype (standard) | Type of Service (standard)
Velg en type tjeneste | Vel ein type tjeneste | Select Type of Service
Kundeforhold | Kundeforhold | Customer relationship
Kontoopplysninger | Kontoopplysingar | Account details

**Comment by sindresandvik2** [comment]
@joebrreg  Klar for godkjenning.   Det er på dette tidspunktet me skal informere behovsdrivaren i Behovsprosjektet om at ein brukerhistorie er ferdig.  Eg informerar Stig!   Du må godkjenne som produkteigar i FDK prosjektet
