### ISSUE TITLE
Vise tjenestetype på et API

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1493]
Som: en bruker av et API
Ønsker jeg å: se om et API er av en viss type eller realiserer en standard
Slik at: jeg enkelt kan forstår hva slags informasjon jeg får av apiet

Realiserer: https://github.com/Informasjonsforvaltning/behov/issues/39

Lenke til design: https://projects.invisionapp.com/share/FWBFRNSAM#/screens/308321878
Lenke til løsningsarkitektur: N/A

- [x] Testdesign

- [x] Sjekk visning av begge tjenestetypene. Sjekk eventuelle lenker

- [x] Kontrollert av UX/Design inkl nettleserevariasjoner

- [x] Sjekk språkvariasjoner

Akseptansekriterier:

language: no
Egenskap:

Kriterier:
⦁	Leser av en publisert API-beskrivelse skal kunne finne informasjon om API-ets type og om den realiserer en standard.
⦁	Dersom tjenestetypen/standarden er dokumentert et annet sted på internett, skal det lenkes dit. Dersom slik referanse ikke finnes, skal Tjenestetype være ren tekst.

Dekkes ikke:
⦁	Filtersetting av tjenestetype

Referanser:

Scenario: Vise tjenestetype for en API-beskrivelse
Gitt at API-beskrivelse med tjenestetype lik "Kundeforhold" er registrert
Og bruker søker gitt API-beskrivelse
Når bruker åpner detaljsiden for gitt API-beskrivelse
Så skal bruker finne Tjestetype på venstremenyen
Og bruker skal finne seksjonen tjenestetype på detaljsiden
Og verdien tjenestetype skal være lik "Kundeforhold"

Scenario: Åpne lenke til dokumentasjon
Gitt at API-beskrivelse med tjenestetype lik "Kundeforhold" er registrert
Og tjenestetypen er dokumentert andre steder på internett
Når bruker åpner detaljsiden for gitt API-beskrivelse
Så skal bruker kunne klikke på lenken til dokumentasjonen
Og dokumentasjonsiden skal åpnes

**Comment by sindresandvik2** [comment]
@joebrreg    Klar for review.  Eg informerar Stig med tanke på Behovsprosessen
