### ISSUE TITLE
Filtrere på API av tjenestetype som tilhører en gitt virksomhet

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1494]
Som: en maskin-til-maskin konsument
Ønsker jeg å: få en liste over API som er av en viss type (standard)som tilhører en gitt virksomhet
Slik at: jeg kan gjøre forespørsler til dette api'et

Realiserer:
https://github.com/Informasjonsforvaltning/behov/issues/40
https://github.com/Informasjonsforvaltning/behov/issues/70

Lenke til design: N/A
Lenke til løsningsarkitektur: https://informasjonsforvaltning.github.io/SA_Informasjonsforvaltning/f4212a30-53d0-4c27-a682-4f88d6c692c8/views/6fc0f5aa-e7df-4765-b5bb-c0fd695c35dc.html

Egenskap:
Brukerhistorie: Oppslag på standardiserte API
OBS: Denne featurefila dekker både #40 og #70

Testes "manuelt" vha Postman inntil full automatisering av Gherkin-koden er på plass.

- [x] Test utført vha Postman

Som en maskin-til-maskin konsument, ønsker jeg å få en liste over API som er av en viss type (standard) og eventuelt som tilhører en gitt virksomhet slik at jeg kan gjøre forespørsler til disse apiene
Akseptansekriterier:
⦁	Løsningen skal kunne liste standardiserte API som har en gitt tjenestetype.
⦁	Løsningen skal kunne liste standardiserte API fra en bestemt virksomhet med gitt tjenestetype
⦁	Løsningen skal kunne gi fornuftig respons når data ikke finnes
Dekkes ikke:
⦁	Håndtering av feil spørringer
⦁	Håndtering ved kommunikasjonsbrudd når "vår" maskin er nede
⦁	Performance test
Referanser:
https://github.com/brreg/openAPI/blob/feature/standardiserte_API/specs/api-cat.yaml
#40
#70

Scenario: Liste standardiserte API med gitt tjenestetype
Når konsumenten gjør en GET mot /apis
Og setter et filter på tjenestetype lik "Kontoopplysning"
Så skal kun API som implementerer denne tjenestetypen returneres som en liste
Og endepunktet til APIet skal være en av opplysningene i listen

Scenario: Liste standardiserte API med gitt tjenestetype og gitt virksomhet
Når konsumenten gjør en GET mot /apis
Og setter et filter på tjenestetype lik "Kontoopplysning"
Og setter et filter på virksomhet lik ""
Så skal kun API som implementerer denne tjenestetypen returneres som en liste
Og listen skal kunne inneholde virksomhetens API
Og endepunktet til APIet skal være en av opplysningene i listen

Scenario: Ingen treff
Når konsumenten gjør en GET mot /apis
Og setter et filter på tjenestetype lik "Kontoopplysning"
og setter et filter på virksomhet lik ""
Så skal endepunktet returnere "ingen treff" / tom liste

**Comment by markkopaas** [comment]
Stig B. Dørmænen   [Today at 11:04 AM]
Versjon av openAPI-spesifikasjonen som har støtte for standardiserte API cc: @Markko Paas
https://github.com/brreg/openAPI/blob/feature/standardiserte_API/specs/api-cat.yaml

12 replies

Markko Paas   [22 hours ago]
ser ok ut. Det litt mer arbeid, som jeg først antok - nye endepunkte, nye response typ, men ikke så mye (edited)

Stig B. Dørmænen   [22 hours ago]
Enig. Forsøkte å unngå det. Men konsumenten insisterte....

Stig B. Dørmænen   [22 hours ago]
Er i møte med konsumenten no.

Markko Paas   [1 hour ago]
bruker vi noe standard? siste gang vi snakket at vi skulle holde oss med HAL

Markko Paas   [1 hour ago]
1) bruk HAL eller noa ant kjent standard is stedet av selv lagd format
2) typisk feltnavn i vårt system er orgNr
3) Vi skulle ikke bruke norsk i referencekoder. Vi har generert to koder nå “CustomerRelationship” og “AccountDetails”. De kodene er generert av oss. Bedre løsning kunne være hvis vi kunne bruke nåe ofisielle koder.  Er det ikke fra PSD2?

Markko Paas   [1 hour ago]
4) våre api-dokumenter er koblet til spec, ikke til endepunkter. så vi har granularitetmismatch.

Stig B. Dørmænen   [41 minutes ago]
1) Vi skal ikkje endre "standard" i api-cat API.
2) orgNr er ok viss nødvendig. Men eg foretrekker å skrive det ut.
3) Er visstnok ikkje PSD2. Men norsk DSOP "standard".
4) Dette spørsmålet skjønte eg ikkje.

Lars Haraldsen   [32 minutes ago]
Trenger avklaringen på #4 så fort som mulig

Markko Paas   [15 minutes ago]
1 og 2 er om hvem eies den API. Hvis det er oss, da skulle vi ta vare at vi holder det så konsistent til andre API som vi har, så mulig. Hvis noen ant eier dette API, da må de ta ansvar at api-ene er logiske og gode.

Markko Paas   [12 minutes ago]
4) en api-spec beskriver flere endepunkter og metoder. Når vi lagrer i database fakta at “api-spec følger standard X” da kan vi ikke si hvilke endepunkt det er. Vi kan si server.

Markko Paas   [8 minutes ago]
3) jeg har nå gravet nåkk i bits.no, og fant ingenting om de standardene, som “Kundeforhold” eller “Kontoopplysninger”. Har du noe dokumenter om dette? I behov sak er de npe lenker til konfluence, som jeg ikke ser (edited)

**Comment by markkopaas** [comment]
Åpne tema
1) vi har ikke tilsvarende data til "activationDate". Vi har status DEPRECATED som har planglegget dato, og vi har status "REMOVED". Så, filter "active" er nå implementert som: ```status!='REMOVED' and (expirationDate is not set or expirationDate is in future)```. 
2) transportProfile - vi har ikke tilsvarende data i modell.
3) vi har bestemt at "url" er egentlig server address fra api-spec. I OpenAPI spec, det er mulig å skrive flere server url. Skal vi ta først, eller skal vi bytte til array, som det er i OpenAPI?

**Comment by stigbd** [comment]
1. Din implementation av "active" er fin.
2. transportProfile kan inntil vidare settes til "eOppslag".
3. Viss flere server url, ta den første.

**Comment by sindresandvik2** [comment]
@stigbd @joebrreg   Klar for akseptansetest.    Det einaste som manglar no er ein dokumentoppdatering som Stig får tilsendt

**Comment by sindresandvik2** [comment]
Testet OK ved hjelp av Postmann.  Begge tjenestetypene og to virksomheter er brukt i testen.  Publisert /ikke publisert ble også testet.  Kun publiserte API.beskrivelser listes!
