### ISSUE TITLE
Informasjonsmodeller med flere elementer i array skal bare vise JSON

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1502]
Det er en større arkitekturisk oppgave å vise informasjonsmodeller som har flere modeller i en liste som hører sammen. 

Som en midlertidig løsning velger vi å filtrere vekk strukturen for disse og dermed bare vise JSON skjema.

**Comment by stigbd** [comment]
Er dette ein feil eller mangel, eller utvidelse? Viss det er ei større arkitekturoppgåve, må vi sjå nærmare på dette. Også fint om det fins eit eksempel på ein slik modell.

**Comment by sindresandvik2** [comment]
Testet i UT1.  Ting er bra for en MVP
