### ISSUE TITLE
Får ikke opp noen datasett ved valg under Opphav

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#1503]
I portalen kan man sortere på ulike kriterier, blant flere valg under "Opphav".
Når man klikker på et hvilket som helst av valgene under Opphav, for eksempel "Nasjonal" (her bør det stå "Nasjonal felleskomponent"), får man opp en side uten navn på datasett. Man får kun tallet 1.  

 

 

[Får ikke treff ved å søke på valg under Opphav.docx](https://github.com/Informasjonsforvaltning/docs/files/2946207/Far.ikke.treff.ved.a.soke.pa.valg.under.Opphav.docx)

**Comment by sindresandvik2** [comment]
Lukkes. Duplikat av kjent feil #1476
