### ISSUE TITLE
Frontend: Rapporter - vise content for Begrep

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1504]
https://projects.invisionapp.com/share/PWQNNOAQSUD#/screens/350029347

**Comment by oyvindis** [comment]
Ser ut som jeg mangler følgende aggregeringer:
 'begrep knyttet til datasett', 'mest brukte begrep', 'catalogCount'

**Comment by sindresandvik2** [comment]
Testet litt. Noen feil meldt.  Vil bli testet fullstendig når alle tasker for rapportsiden er ferdig utviklet/fikset
