### ISSUE TITLE
Populere testdata

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1511]
- Vi må lage testdata
- Vi må populere dette inn i miljøet
- Vi trenger en platform for å løse generelle testoppgaver
- Trenger vi å mocke API-registrering?
- Hver test bør ha kontroll på et eget test-data-set

- Vi trenger et API for å endre test-dataen - kan bruke Elastic API direkte

**Comment by thomasnokleby** [comment]
Hvilket av de forskjellige typene data vi har tenkes det? Datasett, APier, api-registreringer, begrep , informasjonsmodeller, eller alle?
Hvilke miljø tenker man? Lokalt for utvikler? ut1 ? it1?
Hva innebærer en generell testoppgave? Er dette en manuell test? en enhetstest?
