### ISSUE TITLE
Rapporter: Språkvalgene fungerer ikke optimalt

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1519]
Dersom en bytter språk (menyvalg) så oppdateres ikke siden før ein trykker Refresh  (Unntak: Venstremenyen - filtersettingstekstene)  
I tillegg så er **nynorsk** ikkje implementert i toppoversikten.   "Uke" må bytttes ut med "veke" 
og  teksten "API-er" byttes ut med kun "API"

**Comment by oyvindis** [comment]
Kan se ut som løst nå, gjør du en retest av denne?

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
