### ISSUE TITLE
Oppsett av utviklingsmiljø som beskrevet i readme fungerer ikke 

### ISSUE THREAD

**Issue by bgrova** [Altinn/fdk#1521]
Readme og/eller script må oppdateres

**Comment by thomasnokleby** [comment]
Bakgrunn: 
David S:En kollega av meg forsøkte å laste ned og bygge fellesdatakatalog ut fra README.md fila. Men fikk det ikke til. Da han kjørte buildAll.sh skriptet så stoppet det på at det skulle sende data til Coveralls. Når han til slutt fikk kompilert og bygd dokcer images med min hjelp så fikk han 502 på localhost:8080. Er det mulig å få oppdatert README sidene slik at andre enkelt kan bygge og teste løsningen lokalt?
Vi bør prioritere dette.

**Comment by thomasnokleby** [comment]
Har ryddet i filer i forbindelse med denne. PR: https://github.com/Informasjonsforvaltning/fdk/pull/1529
