### ISSUE TITLE
Flytte koden knytta til altinn-datamodel-harvester inn i fdk-kodebasen

### ISSUE THREAD

**Issue by stigbd** [Altinn/fdk#1527]
Sidan vi skal forvalte koden som konverterer Altinn modeller (xsd) til json schema, bør vi legge koden inn i vår eigen kodebase.
Denne koden er no her:
https://github.com/Altinn/altinn-datamodel-harvester

Vi legge koden inn i fdk-repo og automatisere (scripte) bygg og deploy på ein hensiktsmessig måte.

**Comment by thomasnokleby** [comment]
Delsteg:
Flytte kode over til fdk sitt mono-repo.
Få bygd koden (Visual Studio).
Få deployet ny versjon til vår sky (fra Visual Studio).
Dokumentere denne prosessen.
Teste prosess og dokumentasjon ved at en annen på teamet bruker dokumentasjonen til å faktisk deploye en marginal (dummy) endring.
Vurdere(men dette er mest sannsynlig for dyrt til at det er verd det):
Scripte deploy til sky til et slikt nivå at en bruker uten installert Visual Studio kan deploye med en eller et par få kommandoer uten å selv manuelt måtte installere noe.

**Comment by thomasnokleby** [comment]
Vi bør også vurdere, når vi har kontroll på denne koden, å legge inn funksjonalitet for å hente enkelt-schemaer, og listen over alle schema (eller en begrenset liste). Dette fordi det at det tar 5 min pr kall har sakket utvikling uakseptabelt ned, og forårsaker at deler av koden ikke er testbar lokalt for enkelte utviklere.

**Comment by thomasnokleby** [comment]
Vi bør også ha noe tester på denne modulen

**Comment by lillelars** [comment]
utdatert.
