### ISSUE TITLE
Informasjonsmodeller mangler XSD

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/fdk#1560]
Informasjonsmodell siden mangler mulighet for å laste ned modellen som XSD. 

Dette er det foretrukne formatet for mange og det som brukes f.eks i Altinn.

**Comment by sindresandvik2** [comment]
Dette kommer i vår andre leveranse av informasjosnmodeller som er tenkt levert til høsten

**Comment by stigbd** [comment]
Ref https://github.com/Informasjonsforvaltning/behov/issues/156
