### ISSUE TITLE
Linkene i toppen av rapportsiden fungerer ikke

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1561]
I toppen av rapportsiden vises 6 linker. KLikker en på linkene kommer en alltid til samme sted: Datasett.  Her er tre feil:   
1) Linkene for  total og siste uke  er SAMME link
2) Alle linkene går til DATASETT (også API og Begrepstallene) 
3) Linkene (for DATASETT)  sender alltid bruker til DATASETT med ufiltert liste selv om rapporttallet i linjen er redusert
![image](https://user-images.githubusercontent.com/42966644/54593822-a2fe3d80-4a2f-11e9-9954-90cbec5e3c8b.png)

deloppgaver
- [x] opprett firstHarvested filter i api
- [x] refaktorere concept kontroller lignende til hva vi har i api og dataset
- [x] opprett firstHarvested filter i concept

**Comment by oyvindis** [comment]
Avventer filter endepunkter.
Fra Markko:
riktig, api, og concept har ikke firstHarvested filter, men bare aggregering. Det er lett å la de inn til api, mens i consept, controller skulle refaktoreres først å ha lignende struktur som vi har nå i api og i dataset. Halv dag, kanskje. Jeg kan ta det etter DSOP endepunkte. (edited)

**Comment by sindresandvik2** [comment]
Det er fortsatt feil dersom det er satt filter på rapportsiden før en klikker på linken.  Dersom et filter er satt skal det vises like mange forekomster som filteret sier når en komme inn på selve søkeresultatet.

eks:  Setter filter på STAT. Da begrenses mine data fra 1150 datasett til 791 datasett. Når jeg så klikker på linken  vises fortsatt 1150 datasett på Datasettfanen!

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
