### ISSUE TITLE
Høste "eksempel"-felt for Begreper i Begrepskatalog

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1563]
Som: Felles datakatalog
Ønsker jeg å: kunne hente ut data som ligger i eksempel-feltet via begrepspublisereren, fra https://data.brreg.no/begrep/
Slik at: jeg kan tilgjengeliggjøre eksempler under begreps-fanen (detaljsiden) i Felles datakatalog

Krav:
eksempel-feltet skal representeres i SKOS, slik at dette kan gjenbrukes ved høsting fra andre som bruker SKOS, slik som angitt i kolonne 4: "Begrep.eksempel.tekst" på side 4. i SKOS-AP-NO-standarden(pdf s. 19): https://www.difi.no/sites/difino/files/vedl2_-_horingsnotat_med_forslag_til_forvaltningsstandarder_for_maskinell_tilgjengeliggjoring_av_begrepsbeskrivelser_2018-08-17.pdf

Relatert til behov:
https://github.com/Informasjonsforvaltning/behov/issues/130

Lenke til design: https://projects.invisionapp.com/share/HDMWYXXGUZ2#/screens/326837011
Lenke til løsningsarkitektur:

Akseptansekriterier
,# language: no
Egenskap:

Kriterier:
⦁	Alle begrep som har tilknyttet eksempel skal vise dette på begrep detaljside
⦁	Alle begrep som har ikke har tilknyttet eksempel skal ikke vise dette på begrep detaljside

Scenario: Vise eksempel for begrep
Gitt at publisert begrep har verdier i feltet eksempel
Så skal feltet eksempel vises på detaljsiden for gitt begrep
Og menyvalget "Eksempel" skal vises i venstremenyen

Scenario: Vise begrep som ikke har eksempel
Gitt at publisert begrep ikke har verdier i feltet eksempel
Så skal feltet eksempel ikke vises på detaljsiden for gitt begrep
Og menyvalget "Eksempel" skal ikke vises i venstremenyen

EKSEMPEL PÅ BEGREP SOM BENYTTER DETTE I DAG:
https://jira.brreg.no/issues/?jql=project%20%3D%2012400%20AND%20status%20%3D%20Godkjent%20ORDER%20BY%20cf%5B14900%5D%20ASC (lenke til intern Begrepskatalog), se eksempler i kolonnen engst til høyre.

Eksempel finnes ved:
Step 1: naviger til side:: https://data.brreg.no/begrep/
Step 2: ctrl+f søk etter: http://data.brreg.no/begrep/52060
Step 3: Se under core#example

- [x] TestDesign

- [x] Testgjennomføring:
   Sjekk i portal, begreper med og uten eksempel
   Ok for UX
   OK i forskjellige browsere
   OK 3 språk

**Comment by sindresandvik2** [comment]
Testet OK og klar for review!

**Comment by sindresandvik2** [comment]
@joebrreg   Klar for review
