### ISSUE TITLE
Rapportsiden:  Telling av åpne datasett er litt feil

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1565]
Gjelder åpne datasett på rapportsiden: 
![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/136085df-7b77-4425-b767-a38041fa2536)

For at et datasett skal kunne telles som"åpent" må følgende være oppfylt:

1. Datasettet må være offentlig
2. Datasettet må ha en distribusjon
3. Dersom distribusjonen er en API-beskrivelse må API-et som beskrives ha åpen lisens.

Punkt 3 ovenfor telles ikke korrekt på rapportsiden!   Dersom en legger til et Offentlig datasett med distribusjon = API-beskrivelse med åpne linsens. SÅ øker ikke teller over åpne datasett.

Eksempel på API-er som har åpne lisenser:  
National Data Directory Search API
National Concept Directory Search API

Obs: Issuen er registrert som en bug, men her er det nok spesifikasjonen som manglet i utgangspunktet

**Comment by thomasnokleby** [comment]
Hadde vært greit om du la inn hvilket dataset du brukte for å teste punkt 3

**Comment by thomasnokleby** [comment]
Når bruker legger til en API distribusjon på et datasett, så lagres dette i indexen "register". Strukturen for en api beskrivelse er:
"type": "API",
"accessService": {
"description": {
"nb": "National API Directory Search API"
},
"endpointDescription": [
{
"uri": "0ee3db25-2ea2-4bfc-ac68-926d825a008e",
"prefLabel": null,
"extraType": null
}
]
}
}
Denne inneholder ikke per i dag informasjon om den valgte APIen er åpen eller ikke.
Det viser seg at for å avgjøre om en API er åpen så, må man inn i api-specen for å observere om det finnes en lisens eller ei (det antas at alle lisenser som er oppgitt i en spec er åpne). Bruker som registrerer apien 

Deloppgaver som må utføres for å kunne ha spørringer mot dette med en akseptabel svartid:

Legge til feltet "APISpecIsOpen" på index for API som oppdateres når api høstes.Denne oppdateringen går ut på å gå inn i spesifikasjonen for å finne ut om det finnes en lisens eller ikke (**2d**)

Legge til feltet "APIDistributionIsOpen" på index for datasett, som oppdateres ved høsting av datasettet (som jeg forventer skjer når man publiserer). Denne oppdateringen består i å slå opp den tilhørende API i api-index, og lese av om apien selv er åpen, og om bruker for øyeblikket mener at apien er åpen eller ei (bruker overstyrer deteksjon)  (**2-4d**)

Dette resulterer i en del mer kompleksitet i høsting, men ikke veldig mye, vi samler dataene der de hører hjemme, og vi har eventual consistency: hver sjette time høstes det, og da blir alle api-distribusjons-linkene oppdatert med korrekt verdi. 
Spørringen ligger under isOpendataQuery i no.fdk.searchapi.controller.datasetssearch

**Comment by sindresandvik2** [comment]
@lillelars   Kva skal skje med denne i inneverande sprint?   Fix or not?

**Comment by lillelars** [comment]
Håndterer dette med ny funksjonalitet. Lukker saken.
