### ISSUE TITLE
189 ukjente tilbydere av informasjonsmodeller

### ISSUE THREAD

**Issue by joachim-me** [Altinn/fdk#1567]
189 av informasjonsmodellene mangler tilbyder. Finanstilsynet er en av de manglende tilbyderne. De skulle ha tilbudt 102 modeller.

**Comment by lillelars** [comment]
Må dyttes inn i "Publiser"-oppgaven.

**Comment by lillelars** [comment]
Denne håndteres i sak #1576 så jeg closer buggen.
