### ISSUE TITLE
Rapportsiden: Opptelling av Distribusjonstyper er helt feil

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1570]
![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/4e3daadf-adea-41ff-bed0-2df98bafcc3d)

Som bildet viser er opptellingsverdien 0 selv om det finnes datasett med gitt distribusjonstype. 
Klikker en på linken får en opp lister på søkesiden ulik null (0) men fortsatt alt for få sammenlignet med det som finnes.

**Comment by thomasnokleby** [comment]
Det viser seg at det underliggende problemet her er typedefinisjonene. For å korrigere dette må vi gjøre følgende:
Definere/velge rimelige merkelapper - Gjort
Endre høsting til å oversette fra orginale til rimelige merkelapper 1d (?)
Endre registrering til å legge inn rimelige merkelapper ?

**Comment by thomasnokleby** [comment]
Vi kan spare mye arbeid med å endre til å bruke merkelappene som datanorge bruker. Så vi går med det
