### ISSUE TITLE
Må kunne registrere API med Publisher

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1576]
Referanse:
API-237

Vi vil støtte alle virksomheter - ikke bare de som har datasett. Per nå mister vi tilbydere på f.eks Informasjonsmodeller grunnet at Publisher ikke er som egen modul.

"189 av informasjonsmodellene mangler tilbyder. Finanstilsynet er en av de manglende tilbyderne. De skulle ha tilbudt 102 modeller."

Splitte søkemodulen - ta alt som er publisherrelatert til ny modul.

For øyeblikket er Publisher Data høstet ved Datasett. Det betyr at vi ikke støtter API' beskrivelser fra tilbydere som bare gir oss API'er og ikke datasettbeskrivelser. Dette må håndteres.

Storbilde av publisher-api løsning er beskrevd her: https://confluence.brreg.no/pages/viewpage.action?pageId=113949565

Til å registrere API-er uten dataset, vi må minst implementere den første fase av PubliserAPI:

[ ] (4d) Købling til enhetregisteret api og preprocessing (normalisering og organisasjonstruktur bygge, grov tilnærming til å fikse virksomhetsnavn til lavercase, hardcoded navnfiks)
[ ] (2d) Købling til eksisterende katalog-api til få oppdatere navnene
[ ] (2d) standard cache module foran enhetsregisteret (viktig til strukturbygge performance, tilbyr offline development og test)
[ ] (2d) (kan utsettes) mock module (til offline development og integrasjonstest)
[ ] (3d) (kan utsettes) Migrasjon fra flerspråk til enspråk (det tar flere deploy-steg)

OptionsTest Coverage

#1567

**Comment by lillelars** [comment]
@stigbd tagget deg her så vi har noen til å kvalitetssikre... Dette med publisher kom opp igjen ettersom vi høster inn flere informasjonsmodeller direkte til søkeløsningen. Disse ender opp med å miste "Tilbyder" når disse virksomhetene ikke har datasett registrert.

Via Registreringsløsningen slipper vi denne utfordringen ettersom en datakatalog blir opprettet for virksomheten (med 0 datasett).

**Comment by stigbd** [comment]
Eg skal få sett på denne. Det som må gjerast er:
- å bestemme kvar kildekoden skal ligge
- å ta fram ein API-spesifikasjon for Publisher-tjenesten
- å lage akseptanse-kriteria

**Comment by sindresandvik2** [comment]
Denne blir fylgd opp av #1950
