### ISSUE TITLE
Rapportsiden: Opptelling av Distribusjonstyper er helt feil

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1606]
Registreringsløsning skal benytte referencedata til distribusjonstyper.

Se #1570

- [ ]

**Comment by thomasnokleby** [comment]
Vi bruker nå distribusjonstypene (som er URI i reference data)
http://publications.europa.eu/resource/authority/distribution-type/WEB_SERVICE
http://publications.europa.eu/resource/authority/distribution-type/FEED_INFO
http://publications.europa.eu/resource/authority/distribution-type/DOWNLOADABLE_FILE

Som grunnlag for aggregeringene distributionCountForTypeApi distributionCountForTypeFeed distributionCountForTypeFile.
Dette er nå i develop så denne er klar for at frontend jobber med den

**Comment by sindresandvik2** [comment]
Etter korrigering i dag er nok denne fortsatt feil.   
1.  I UT1 viser rapporten nå f.eks. 320 Nedlastbare filer. Klikker en på linken dukker det opp kun 3 datasett på søkesiden.   Det finnes Datasett med distribusjon = "Nedlastbar fil" som ikke vises ved denne filtersettingen  (eks:  BIBSYS,  Digital 3D-bymodell Trondheim)
Det er tilsvarende problemer dersom en klikker på linkene med API og Feed distribusjoner

2. Dersom en aktivt legger til et datasett til med distribusjon "Nedlastbar fil" så øker ikke telleren i rapporten, men det dukker helt korrekt opp en ekstra forekomst når en klikker på linken.

Om dette er feil i Frontend eller Backend vites ikke.....

![image](https://user-images.githubusercontent.com/42966644/55085692-61ad0400-50a7-11e9-89fa-1427a91407ac.png)

**Comment by oyvindis** [comment]
Verifisert at opptelling og filtrering ikke gir samme antall. Kan være feil i enten opptelling eller i filtrering for typen.

**Comment by lillelars** [comment]
#1570 Se også informasjon fra denne issuen

**Comment by lillelars** [comment]
Utgår.
