### ISSUE TITLE
Backend:  Forbedre data for å kunne trekke ut virksomheter med API

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1610]
Ref kommentar fra Øyvind: 
Foreløpig viser jeg ikke antall virksomheter som har API-er og heller ikke listen over virksomhetens API-kataloger.
Data fra backend er litt feil for api, blir gitt som orgPath, men må komme på katalognivå. F.eks. 'Fylke' er eget orgPath, men skal ikke regnes som virksomhet. Data må gis som for datasett.

**Comment by thomasnokleby** [comment]
Dette er nå avklart med Øyvind, og innebærer ingen kodeendringer.
