### ISSUE TITLE
Rapportsiden - Begrep.   Feil antall begrep vises når det er satt filter

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1620]
Når en setter et filter på rapportsiden slik at antall datasett i utvalget blir redusert må også tallet for antall begrep knyttet  til datasett tilpasses.  i UT1 vises nå tallet 8 selv om  det som er filtrert har 0 begrep.   Tallet som vises skal fortelle om hvor mange av begrepene til utvalgte virksomheter er benyttet i et eller annet datasett.   (Informasjon om antall begrep som er benyttet for de datatsettene som er filtrert vises på rapportsiden for datasett!) 

![image](https://user-images.githubusercontent.com/42966644/55076915-daf02b00-5096-11e9-93d1-ba759308c225.png)

**Comment by oyvindis** [comment]
F.eks. se rapportside med orgPath spesifisert: http://localhost:8080/reports?orgPath=/FYLKE

Feil kan trigges ved gjentatte reloads.

Ved bruk av lodash memoize så kjøres funksjonen første gang uten orgPath-parameter der memoized-funksjonen initialiseres. Deretter kjøres funksjonen på nytt med orgPath-parameter satt.

Bruker async/await, men virker som at 'datasetCountsByConceptUri' ender opp med å bli satt ut fra første gangs kjøring, selv om jeg velger å ikke gjøre kall til getDatasetCountsBySubjectUri.
