### ISSUE TITLE
Rapportsiden- Begrep:  Tallet for "Antall begrep knyttet til datasett" skal være en lenke

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1622]
På begrepsfanen vises tallet for antall begreper som er knyttet til et eller annet datasett. Dette tallet er i følge designskissene en lenke, og da forventes at ved å klikke på denne skal Søkesiden for begrep dukke opp med de utvlagte begrepene satt som filter.    Slik alle andre tilsvarende lenker fra rapportsiden fungerer. 

Dersom denne jobben blir uforholdsmessig stor ta det opp med Joachim. 

![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/42ad1b83-444b-4ffc-a239-cc874b624fb3)

**Comment by oyvindis** [comment]
Det må lages et filter i BE som gjør dette mulig, ikke like enkelt som andre filtre.
