### ISSUE TITLE
Registreringsløsningen:  Formatfeil ang API-tilknyttninger

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1641]
Liten formatendring for API-distribusjoner:    
a) Det skal være mer luft over heading 
![image](https://user-images.githubusercontent.com/42966644/55322107-b66fc680-547b-11e9-8b8b-995796690b0c.png)

**Comment by oyvindis** [comment]
3) a - rettet
b- ikke rettet. Må endre bruk av komponenter.

**Comment by sindresandvik2** [comment]
Retestet OK  i UT1
