### ISSUE TITLE
Frontend: vise tabell med tilknyttede datasettbeskrivelser

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1643]
Mangler denne liste-komponenten på API-registrering:

https://projects.invisionapp.com/share/HDMWYXXGUZ2#/screens/333175367

**Comment by sindresandvik2** [comment]
To problem dukket opp i testen:
1. Et tilkoplet datasett dukket opp som duplikat.  Det eksisterer kune en kopling for "Ola"  (Se skjermdump) https://registrering.ut1.fellesdatakatalog.brreg.no/catalogs/910244132/apis/ba6c9ba7-6fb4-4c44-b97b-bd324d5d1944

2. Klikker en på lenken kommer en ikke inn på valgt datasett
![image](https://user-images.githubusercontent.com/42966644/65518144-1ce21880-dee4-11e9-83d4-58f45fee58e9.png)

**Comment by sindresandvik2** [comment]
OK i UT1.    Testes litt mer i Brukerhistorien #1645
