### ISSUE TITLE
Søkeportal - Datasett:  Formatfeil API-distribusjoner

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1655]
Det må være mindre luft mellom tittel på API-beskrivelsen og tibyder rett under tittel. 
Se design skisser:  https://projects.invisionapp.com/share/HDMWYXXGUZ2#/screens/321530319

![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/c58de740-39fa-46e4-a5aa-29f53c5557b1)

**Comment by lillelars** [comment]
Nytt design. Lukker denne.
