### ISSUE TITLE
Detaljside datasett: Viser ikke alle API distribusjoner

### ISSUE THREAD

**Issue by joachim-me** [Altinn/fdk#1656]
- [ ] Analyse + graving (Max 2d)

- [ ] Gjøre selve oppgaven

Datasettet Bananer har fire API-distribusjoner:
![image.png](https://images.zenhubusercontent.com/5c6e939eab9efc3c63334546/7d67e7e2-c42e-4bdd-a23e-12498f9da739)

Det er bare tre distribusjoner som vises i portal:
![image.png](https://images.zenhubusercontent.com/5c6e939eab9efc3c63334546/a9e81d5b-7694-4596-89ac-48440b5f4f20)
Se https://www.ut1.fellesdatakatalog.brreg.no/datasets/9486a957-b548-4e83-a9af-44bb88c79a16

**Comment by oyvindis** [comment]
API-er som peker til et datasett må tas med i search-api under distribution på samme måte som en API-distribusjon (backend)

**Comment by oyvindis** [comment]
Etter litt feilsøking så tror jeg dette er en ren backend-oppgave i utgangspunktet, fjerner "frontend"-label inntil vi ser om det blir riktig når disse api-er blir tatt med i search-api, ref. forrige kommentar.

**Comment by markkopaas** [comment]
Hvis krav er at i utseende de relaterte api-ene er kombinert, da er enklere løsning å gjøre det i frontend.
Hvis kraven er at vårt rest api skulle inkludere det i /datasets/{id} endepunkte, da må vi gjøre det i api runtime eller i indeksering.

Jeg anbefaler frontend løsning, på grunn av det hjelper å holde vårt internt modell litt enklere, hvis mulig. Så implementere den som lookup i frontend.

**Comment by sindresandvik2** [comment]
[Retest 1656.xlsx](https://github.com/Informasjonsforvaltning/fdk/files/3261418/Retest.1656.xlsx)
Retestet i UT1.  En følgefeil oppdaget og registrert i ny issue
