### ISSUE TITLE
Implementere tabeller, spørringer og innfyll av data for en SQL database for å lage LOS tema og relasjonene mellom dem

### ISSUE THREAD

**Issue by thomasnokleby** [Altinn/fdk#1658]

**Comment by lillelars** [comment]
Venter nå på GCP - Michael/Anders

**Comment by thomasnokleby** [comment]
Anders skal jobbe noen timer på dette i morgen (29 mai). Jeg følger opp

**Comment by thomasnokleby** [comment]
Anders har satt opp en kubernetes pod som sql proxy koblet til tjenesten, ser bra ut, men jeg må teste. Når det er ok må Anders gjenta jobben for de andre testmiljø

**Comment by lillelars** [comment]
@thomasnokleby kan du skrive en kommentar på beslutningen på denne, så kan vi lukke den.

**Comment by thomasnokleby** [comment]
Denne koden har nå lagt og ventet i 6 uker, og det må gjøres en litt større merge-jobb og teste jobb for å få den på stell. Siden dette er en optimalisering, bør vi vente til vi eventuelt får performance problemer på dette før vi tar i bruk dette.

**Comment by lillelars** [comment]
@thomasnokleby  kan du skrive en kommentar på hvorfor vi ditcher SQL for LOS på dette tidspunktet? Også closer vi denne tasken.

**Comment by thomasnokleby** [comment]
Se min forrige kommentar
