### ISSUE TITLE
Triple data store / referenceDB som ikke er FUSEKI

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1665]
Fra Thomas:
"vi da har noe triple data store greier som IKKE er fuseki
ser ut til at denne bare blir brukt at reference data."

Bør ryddes opp i!

**Comment by sindresandvik2** [comment]
Denne skaper problemer fortsatt.  Bør fikses snarest  i følge Markko

**Comment by lillelars** [comment]
@markkopaas Vet vi noe om estimat på denne?

**Comment by stigbd** [comment]
Vi bør spesifisere denne litt meir presist. Kva er disse "greiene", kven eller kva bruker dei og kvifor blir dei brukte?

**Comment by bgrova** [comment]
Reference-data bruker triple-storen tdb, som er end-of-life.

Fuseki brukes av harvester-api, harvester og search-api.
Fuseki holder to typer informasjon i form av RDF:
* RDF-versjon av datasett
* Informasjon om høsting av datasett: Endepunkter som skal høstes og logg fra høstingene.
