### ISSUE TITLE
Hjelpetekst for hvilke filer API-registrering støtter

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1666]
Ser ut til at vi har mistet en hjelpetekst så API-tilbyderne vet hva vi støtter. Dette har vi hatt tidligere:

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/74cf41d9-0c17-4d64-975b-2a2e978bf4fc)

Se skisse: https://projects.invisionapp.com/share/7RQ8ZOGAUKF#/screens/342809818

NB!
Bør også stå at vi i øyeblikket bare støtter JSON format.
"Felles datakatalog støtter foreløpig Open API-Specification 2.0 og 3.0 og Swagger 2.0 i JSON format"

**Comment by sindresandvik2** [comment]
OK i UT1
