### ISSUE TITLE
Registreringsløsningen- API-katalogen:  Det er ikke mulig å hente datasett fra andre virksomheter

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1670]
I dag kan en bare knytte til seg datasett opprettet av egen virksomhet.  Dette skal nå endres til å gjlede alle datasett som finne si katalogen. 

Knyttingen andre vegen,  datasett som knytter til seg API-beskrivelser, lar bruker knytte til seg fra hele API-kaptalogen. 

![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/14a0e16a-3b5f-436d-bad5-a84795e0b829)

**Comment by lillelars** [comment]
Dette er fikset for en stund tilbake. Lukker denne.
