### ISSUE TITLE
Antall informasjonsmodeller minker og minker

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1671]
Vi får 522 informasjonsmodeller fra Altinn - men i produksjon viser det seg at vi bare har 374.

**Comment by bgrova** [comment]
Feil adresse for høsting lå inne i konfigurasjonsfila i Jenkins (prod-values.yml).
Har lagt inn riktig adresse: https://fdk-dev-altinn.appspot.com/api/v1/schemas
og i tillegg oppdatert kjørende konfig i Kubernetes med denne adressen.

Gammel adresse var til en midlertidig løsning som ble etablert som en reserveløsning mens Altinn-tjenesten ikke fungerte:
https://storage.googleapis.com/altinndata/altinn-service-schemas.json
