### ISSUE TITLE
Ta i bruk filter og implementer "mellomklasse" for å kunne vise datasett på begrep-detaljside

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1675]
- [x] Grave i fdk for å se hvor koblingen mellom dataset og begrep lagres
- [x] Vurdere om Begrep eller Dataset som entiteter trenger å utvides eller vi må lage noen flere broer mellom modulene

- [ ] Ta i bruk filter
- [ ] Implementer utvidelse av datasett-cat-client

**Comment by thomasnokleby** [comment]
Bruker enhetsregisteret som eksempel
https://fellesdatakatalog.brreg.no/datasets/68d08f28-a16d-4fab-a953-ed4ab08ce2e2

**Comment by thomasnokleby** [comment]
Fil for å begynne å nøste sammenhengene lokalisert : no.acat.service.ApiDocumentBuilderService, metode extractDatasetReference

**Comment by thomasnokleby** [comment]
Ved å kjøre postman på    (accept json)
https://fellesdatakatalog.brreg.no/datasets/68d08f28-a16d-4fab-a953-ed4ab08ce2e2
Så ser man at de begrepene som datasettet har er lagt inn i selve datasett-elementet

Og GUI i registrering har kontroller for å velge og legge til Begreper til datasettene.

**Comment by thomasnokleby** [comment]
Midlertidig løsningsforslag:
Lage en rest adresse for dataset /datasets/byBegrep og utvilde datasetcatclient med dette, og da implementere byBegrep som tar inn et begrep og retunerer urlene til alle datasett som referer til det nevnte begrep.

**Comment by stigbd** [comment]
Det midlertidige løsningsforslaget kan funke, men ser litt mykje ut. Eg skal ta ei runde med korleis dette er tenkt at det skal funke, eigentlig. Kjem attende med løsningsforslag i løpet av dagen.

**Comment by thomasnokleby** [comment]
Etter en gjennomgang med stig, så ser vi at løsningsforlaget nevnt over er beste måten å gjøre dette på.   Edit: Self. å bruke filter som nevnt under av stig.

**Comment by stigbd** [comment]
Ikkje heilt: Det vi vart enige om er å bruke eksisterande filter i api-et. Dermed treng vi ikkje lage ny rest-ressurs. Filteret eg pratar om går fram av følgande døme:
```
curl -H "Accept: application/json" "https://fellesdatakatalog.brreg.no/datasets?subject="https://fellesdatakatalog.brreg.no/api/concepts/60113aac-2dd4-4272-8ad2-c3ede5b4b096""
```
@ApiImplicitParam(name = "subject", dataType = "string", paramType = "query", value = "Filters on concept uri."), i DatasetsSearchController.java

**Comment by azaxarov** [comment]
Det virker best å implementere et eget kall i front end i stedet for å rote til i back end modellen.

**Comment by azaxarov** [comment]
Denne skal ikke jobbes mer på siden løsningen er i: https://app.zenhub.com/workspaces/fdk---felles-datakatalog-5c61461c801d5a1030316315/issues/informasjonsforvaltning/fdk/1674
