### ISSUE TITLE
Søke-api: Søk på publsisher.name ser ut til å gi feil resultat

### ISSUE THREAD

**Issue by bgrova** [Altinn/fdk#1677]
Søke-api: 
https://fellesdatakatalog.brreg.no/datasets?q=publisher.name: SAMFERDSELSDEPARTEMENTET 

Gir ett svar: Ett datasett der publisher er Entur AS, som ligger under samferdselsdepartementet.
Samferdselsdepartementet har 48 datasett, og Entur AS ligger under Annet.

Rapportert av Mats Jørgensen, KOR-prosjektet.

**Comment by sindresandvik2** [comment]
Gjenskapt.  Men Samferdselsdepartementet er ikkje eigar av eigne datasett.  Dei 48 som finnes er underlagt departementet i f.eks. SVV. 
Entur ligger faktisk under Privat.   

Dette er nok ikkje ein eigen feil, men me kan ta det med i vurderinga når me jobbar med Tune søket Sjå behov https://github.com/Informasjonsforvaltning/behov/issues/54.  @joebrreg må bestemme

**Comment by bgrova** [comment]
Har beskrevet alternativ bruk av API-ene for å finne datasett til hørende en organisasjon. Har bedt om tilbakemelding på hvorvidt dette dekker behovene.

**Comment by lillelars** [comment]
utått. lukker saken.
