### ISSUE TITLE
Ta i bruk SQL-tjeneste i testmiljøer

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1684]
@bgrova @stigbd  vi trenger lenke til dokumentasjon for lagring.
@thomasnokleby må skrive en linje i denne dokumentasjonen

**Comment by thomasnokleby** [comment]
Lage egen database i allerede eksistende instans.

**Comment by lillelars** [comment]
Venter nå på GCP - Michael/Anders

**Comment by thomasnokleby** [comment]
Anders har satt opp en kubernetes pod som sql proxy koblet til tjenesten, ser bra ut, men jeg må teste. Når det er ok må Anders gjenta jobben for de andre testmiljø
