### ISSUE TITLE
Ta i bruk SQL-tjeneste i PROD

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1685]
@bgrova @stigbd  vi trenger lenke til dokumentasjon for lagring.
@thomasnokleby må skrive en linje i denne dokumentasjonen

**Comment by thomasnokleby** [comment]
- [x] - Lage egen instans for prod database og tilhørende database. 

- [x] - Finne (lage?)  og dokumentere brukernavn/passord for adminbruker for db.

**Comment by lillelars** [comment]
Venter nå på GCP - Michael/Anders

**Comment by thomasnokleby** [comment]
Anders har satt opp en kubernetes pod som sql proxy koblet til tjenesten, ser bra ut, men jeg må teste. Når det er ok må Anders gjenta jobben for de andre testmiljø, og så lage egen instans for prod

**Comment by bgrova** [comment]
Skjema public ikke låst, sikkerhetsgjennomgang ikke gjennomført. Kun standardoppsett foreløpig. Foreslår å gjøre dette som egne aktiviteter.
