### ISSUE TITLE
sso.fellesdatakatalog.brreg.no (op1)

### ISSUE THREAD

**Issue by markkopaas** [Altinn/fdk#1688]
- [ ] bestille sertifikater til sso.fellesdatakatalog.brreg.no og tilsvarene i andre miljøene

- [ ] sette opp helm og kubernetes (Bjørn)

- [ ] sette opp jenkins og variabler (Bjørn)

https://github.com/helm/charts/tree/master/stable/keycloak

**Comment by sindresandvik2** [comment]
Verifisert i UT1 sammne med Bjørn!
