### ISSUE TITLE
Oppgradere spring-boot-starter-parent

### ISSUE THREAD

**Issue by bgrova** [Altinn/fdk#1717]
Spring boot bør oppdateres for å fjerne en security vulnerability. Vi bør gå til (minst) versjon 2.1.4. Denne endringen bryter bakoverkompatibilitet for org.elasticsearch.common.transport.InetSocketTransportAddress og medfører altså kodeendringer.

**Comment by lillelars** [comment]
@bgrova er dette gjort?

**Comment by markkopaas** [comment]
Jeg tror vi snakker om dette:
com.fasterxml.jackson.core:jackson-databind
critical severity
 23 May 2019 by GitHub
libraries/shared/pom.xml

det er ikke løst enda.
