### ISSUE TITLE
Portal: Sortere søketreff alfabetisk 

### ISSUE THREAD

**Issue by marittor** [Altinn/fdk#1719]
Som lesebruker i Portal
Ønsker jeg å kunne sortere alfabetisk på treffene mine, både på totallisten og når jeg har gjort et søk
Slik at jeg f. eks når jeg vil lese begreper, får oversikt over innholdet og slipper å lete.

**Comment by sindresandvik2** [comment]
@joebrreg Denne må flyttast over til Behovsprosjektet. You fix?

**Comment by marittor** [comment]
Lukkes da denne er opprettet som ny sak direkte fra behovsprosjektet.
