### ISSUE TITLE
Datasett registrering: Utvidet søk i felter og visning av flere felter i livesøk under bolken "Søkeord og begrep""

### ISSUE THREAD

**Issue by marittor** [Altinn/fdk#1721]
Som skrivebruker som skal registrere datasett
Ønsker jeg at tillatte og frarådde termer inngår i søket og at det gir et treff på riktig term når jeg skal koble begreper og datasett. Eksempel: Dokumentnummer (anbefalt term) skal dukke opp når man søker opp f. eks dagboknummer (som er en tillatt  term). 
OG at ansvarlig virksomhet for begrepet vises i treffene
OG at fagområde til begrepet vises i treffene
Slik at jeg kan velge riktig term til tross for at jeg har skrevet inn en tillatt eller frarådd term til begrepet 
OG slik at jeg får hjelp til å velge riktig begrep ut fra fagområde og ansvarlig virksomhet, når jeg får flere treff på termen.

**Comment by marittor** [comment]
Relatert til behov i Behovsprosjekt om å tune søket, nr. 54. Bør denne flyttes ut av pipeline på FDK her

**Comment by sindresandvik2** [comment]
@joebrreg Denne må flyttast over til Behovsprosjektet  You fix?

**Comment by RogerSOlsen** [comment]
Støtter behovet, særlig at ansvarlig virksomhet må vises. Nå ser vi ikke hvem som eier et begrep når vi skriver en term som gir treff på to begreper i registeringsløsningen for datasettbeskrivelser, for eksempel "organisasjonsnummer" som både Skatteetaten og Brønnøysundregistrene har registrert som begrep, med begrepsdefinisjoner som tilsynelatende ligner mye på hverandre, men som allikevel er ulike

**Comment by marittor** [comment]
Issue moved to [Informasjonsforvaltning/behov #291](https://github.com/Informasjonsforvaltning/behov/issues/291) via [**ZenHub**](https://www.zenhub.com/)
