### ISSUE TITLE
Forskjellig font i filtertag og selve filterteksten

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1724]
Når en velgher filter fra Virksomhet (øverste nivåer)  eller Opphav  dukker Filtertag'n opp med store bokstaver . Ulikt tekstformatet i selve filteret.    Dette bør være likt!

![image](https://user-images.githubusercontent.com/42966644/56658771-bdb17b00-669b-11e9-95da-b3595bfca133.png)

**Comment by oyvindis** [comment]
og rettet dette:

![image (1)](https://user-images.githubusercontent.com/6214701/56720227-a7aac580-6742-11e9-97cc-d8bd736ccef4.png)

**Comment by sindresandvik2** [comment]
Nesten i mål... Opphav er fortsatt med store bokstavar

**Comment by sindresandvik2** [comment]
Retestet OK i Ut1
