### ISSUE TITLE
Registreringsløsningen: Lange begrepsord brytes ikke 

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1740]
Når en skal plukke begrep i registreringsløsningen for datasett legges de lengste navnene over forklaringsteksten.  Se skjermdump

![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/804e5802-db47-4a3b-b111-1f81504c336a)

**Comment by lillelars** [comment]
ikke problem lenger. lukker denne.
