### ISSUE TITLE
Endre "Tilbyder"-string felt til "Ansvarlig" under informasjonsmodeller

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1743]
Se også #1742 

NB Gjelder også filter på informasjonsmodell-fanen

![image](https://user-images.githubusercontent.com/39513382/56943548-45760a00-6b20-11e9-9412-db709562cc6b.png)

**Comment by skobba** [comment]
Informasjonsmodell-detaljer inneholder også "Tilbyder", endret til "Ansvarlig"

![image](https://user-images.githubusercontent.com/16732769/57761392-b3fcbf80-76fd-11e9-9dc5-b88f79b48be0.png)

**Comment by sindresandvik2** [comment]
Testet OK i ST1
