### ISSUE TITLE
Filter: Designplukk på filter i søkeløsning

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1747]
- [x]  Mister kontekst når man aktiverer filter langt ned på siden - bruker blir scrollet til toppen (?)

**Comment by oyvindis** [comment]
Ønsker å sortere filter alfabetisk (Nå har vi mest treff øverst): Ser ut som enklest å endre sortering for alle aggregeringer i search-api (backend).

**Comment by oyvindis** [comment]
Mister kontekst når man aktiverer filter langt ned på siden - bruker blir scrollet til toppen (?): i dag scroller vi til topp konsekvent på alle url-endringer. Jeg kan ta bort det, men må samtidig legge inn scroll til topp alle andre steder "manuelt". Vi kan ikke basere oss på at url-endring skal trigge scroll!

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
