### ISSUE TITLE
Filter: Trenger ny "stor" pil pr filter-kategori for å lukke hver kategori

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1750]
Se design:
https://projects.invisionapp.com/share/N9Q9157SD3U#/screens/355699912

**Comment by oyvindis** [comment]
Husk også å endre farge på "vis fler" og å gjøre hovedkategori **bold** når den ekspanderes: iflg. Lene , ok å vente med denne. Må lage custom komponent for TreeView.

**Comment by sindresandvik2** [comment]
Ny-pil funksjonalitet fungerer fint i UT1
