### ISSUE TITLE
LOS-filter plukker datasett med ELLER(OR) - operator

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1754]
Når det blir kryssa av i flere filter checkbokser skal utvalget baseres på AND-operator.  Det er kun de datasetta som har matach på alle valgte tema som skal vises.    Nå vises alle datasett som har treff på et eller felre av de valgte tema.  (OR)

I skjermdumpen her vises korrekt de to datasetta som har TEMA = ARBEID
![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/f72b3a0d-4fff-49c0-8b57-da6fb2b23f9a)

Dersom en i tillegg krysser av for TEMA = HELSE skjer to ting:
a)  Tallet i parentes, 2 endres til 5
b)  Det listes opp 5 datasett totalt og det er kumn 2 av dem som har både ARBEID og HELSE

**Comment by thomasnokleby** [comment]
Denne er fikset i pull request  https://github.com/Informasjonsforvaltning/fdk/pull/1766

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
