### ISSUE TITLE
Søking mot LOS tema virker ikke

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1755]
Dersom en søker på et temaord så listes ikke datasett som er merket med gitt tema.   Gjelder uansett om tema er hovedkategori, underkategori eller et emneord (inkl synomymer) 

Eks:  Filter = ARBEID gir to datasett:
![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/b6a7e573-003d-4745-88c7-84508ef66844)

Dersom en nå søker på ordet Arbeid forsvinner datasettene fra listen selv om det da skulle være treff på temaord = Arbeid
![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/edb33e04-b4a2-42e3-88c1-437a3d48327d)

**Comment by thomasnokleby** [comment]
Etter er skikkelig DYPDYKK i hvordan spørringer er laget, satt opp og modifisert, munner det hele ut til at det var to separte feil: Manglende mapping i indexen, og store/små bokstaver. Jeg har endret høsting til å legge inn bare små bokstaver, og tilsvarende for alle LOS termer.

**Comment by sindresandvik2** [comment]
Testest i UT1 etter ny innhøsting.   Caset som er beskrevet er fortsatt feil.

**Comment by thomasnokleby** [comment]
Her var hovedproblemet at mapping for indexen som blir søkt ikke ble oppdatert. Etter 3 restarter og mye debugging oppdaterte den seg. Årsak ukjent, så dette må vi være obs på i it1, og prod også. Har lagt på mer logging

**Comment by sindresandvik2** [comment]
Retestet OKi UT1.    Fortsatt noen utfordringer igjen for LOS-søking.  (Rapportert i andre issues)
