### ISSUE TITLE
Registreringsløsning: Legge til Ansvarlig, tilbyder og eier ved søk

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1760]
PRIORITET 1: 
- [x] Registrere Datasett: Legge til ekstra kolonne ("Ansvarlig" /Publisher) i søkedropdown der bruker skal legge til Begrep og Søkeord

PRIORITET 2:
- [ ] Registrere Datasett: Legge til ekstra kolonne ("Tilbyder" /Publisher) i søkedropdown der bruker skal legge til API-distribusjon

- [ ] Registrere API: Legge til ekstra kolonne ("Eier" /Publisher) i søkedropdown der bruker skal legge til tilknyttet datasettbeskrivelse

Se design her:
https://projects.invisionapp.com/share/N9Q9157SD3U#/screens/343911175

**Comment by joebrreg** [comment]
Tredje punkt (begrep) prioriteres i første omgang.

**Comment by lillelars** [comment]
endret med riktig prioritet i beskrivelse nå.

**Comment by thomasnokleby** [comment]
Etter analyse så viser det seg at det ikke er nødvendig med backend arbeid på denne. Om man ser i ut1 på spørringen som henter data til nedtrekkslisten :
https://registrering.st1.fellesdatakatalog.brreg.no/api/concepts?preflabel=eple&returnfields=uri,definition.text
Så ser man at, for å legge til publisher i url:
https://registrering.st1.fellesdatakatalog.brreg.no/api/concepts?preflabel=eple&returnfields=uri,definition.text,publisher.name
Eller alternativt publisher (uten .name bak) for å få hele publisher blokken.

**Comment by lillelars** [comment]
@oyvindis Er dette noe du kan se på videre?

**Comment by oyvindis** [comment]
@lillelars Ja, jeg kan se på den nå!

**Comment by lillelars** [comment]
@oyvindis  Fikk Gjermund til å ta review og merge - ettersom vi ønsket denne med i prod og du var syk denne dagen.

**Comment by sindresandvik2** [comment]
Prioritet 1 OK i IT1

**Comment by sindresandvik2** [comment]
Dei siste to punkta under prioritet 2 blir tatt vare på i #2327  og #2252
