### ISSUE TITLE
API-registrering: Tilknytte datasettbeskrivelse skal søke i hele Felles Datakatalog

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1762]
For øyeblikket gjør den bare oppslag på egen virksomhets katalog. Det er ønskelig at dette endres til å gjøre oppslag i hele Felles datakatalog

![image](https://user-images.githubusercontent.com/39513382/57122243-adc12780-6d7c-11e9-9613-87a413d43284.png)

**Comment by sindresandvik2** [comment]
En får fortsatt opp kun virksomhetens egne datasett!!!!

**Comment by sindresandvik2** [comment]
Retestet O i UT1.   KAn kople til Datasett fra alle virksomheter. Og linkene fuingerer begge veier i søkeportalen!
