### ISSUE TITLE
Sette opp nytt miljø i GCP for demo-formål

### ISSUE THREAD

**Issue by bgrova** [Altinn/fdk#1764]
Sette opp nytt miljø for demo.
Oppskrift:
https://confluence.brreg.no/pages/viewpage.action?pageId=106539985

Skal brukes i temamøte på Brønnøysundregistrene 28.5.2019

**Comment by RogerSOlsen** [comment]
vi trenger registreringsløsning og portal i dette miljøet med tilsvarende design og funksjonalitet som det vi har i produksjon for registeringsløsning på https://registrering.fellesdatakatalog.brreg.no/ og i portal på https://fellesdatakatalog.brreg.no/ , men vi trenger ikke autorisasjon via Altinn
