### ISSUE TITLE
Datasett søk - LOS-Filter fortsatt feil

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1771]
For øyeblikket ser det ut til at en underkategori har et mer treff enn en hovedkatagori.. Det skal i hovedsak ikke være mulig å få til

![image](https://user-images.githubusercontent.com/39513382/57225575-13c3de00-700d-11e9-81ae-8e657de4b608.png)

**Comment by sindresandvik2** [comment]
Ikke lenger feil
