### ISSUE TITLE
Ønsker å sortere filter alfabetisk (Nå har vi mest treff øverst)

### ISSUE THREAD

**Issue by oyvindis** [Altinn/fdk#1772]
Ønsker å endre til alfabetisk rekkefølge på filteret
![image](https://user-images.githubusercontent.com/39513382/57278815-ce082380-70a7-11e9-86dc-45bf7df4fba1.png)

**Comment by oyvindis** [comment]
Sortering må inkludere språk.
Noen 'labels' finnes ved lookup.

**Comment by lillelars** [comment]
Lukkes og prioriteres ned pga arbeidsmengde
