### ISSUE TITLE
LOS: Rekkefølge på filtersetting gir feil resultat

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1785]
Dersom en først setter filter på en underkategori for så å sette filter på tilhørende overordnet kategori får en ingen treff. Dersom en først setter filter på overordnet kategori og så setter filter på et tilhørende underkategori så fungerer filtersettingen OK.  (Rett nok med andre utfordringer)  

1. Hovedkategori FØR underkategori: 
![image](https://user-images.githubusercontent.com/42966644/57444679-f8e1ab80-7250-11e9-9ad9-0514896b3b73.png)

2.  Underkategori FØR hovekategori
![image](https://user-images.githubusercontent.com/42966644/57444721-10b92f80-7251-11e9-9e98-accaac01711a.png)

Info fra Øyvind: 
curl mot endepunkt med los-tema 'folkehelse' og 'helse':
curl 'https://www.ut1.fellesdatakatalog.brreg.no/datasets?losTheme=helse%2Ffolkehelse%2Chelse&aggregations=accessRights%2Ctheme%2CorgPath%2Cprovenance%2Cspatial%2Clos' -H 'pragma: no-cache' -H 'cookie: _ga=GA1.2.1794233734.1505466867; _hjIncludedInSample=1; _gid=GA1.2.2027659960.1557122788; _gat=1' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9,nb;q=0.8' -H 'authorization: Basic ZmRrOkJSUkVH' -H 'accept: application/json' -H 'cache-control: no-cache' -H 'authority: www.ut1.fellesdatakatalog.brreg.no' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36' -H 'referer: https://www.ut1.fellesdatakatalog.brreg.no/?losTheme=helse%2Ffolkehelse%2Chelse' --compressed
gir ingen treff, så feil i endepunktet

**Comment by lillelars** [comment]
@thomasnokleby @sindresandvik2  denne ser ut til å være fikset. Closer denne
