### ISSUE TITLE
LOS: Hovedkategori forsvinner fra filtermenyen når datagrunnlaget er llite

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1794]
Dersom det mangler datasett i trefflisten som har hovedkategori vises ikke denne i hovedmenyen.

Eks: Dersom en søker på ordet Mikke dukker datasettet "Mikke Mus" opp.  Dette datasettet har kun 4 underkategorier og da vises kun disse i menyen UTEN tilknyttede hovedkategori.

![image](https://user-images.githubusercontent.com/42966644/57522940-d79dbf80-7323-11e9-8ca1-ac9735f810dd.png)

**Comment by oyvindis** [comment]
Snakket med Thomas, vi må få med aggregering til toppnivå for temaer i det som kommer under 'aggregations' for datasett. Han ser på dette i backend.

**Comment by sindresandvik2** [comment]
Det kan hende dette problemet blir løyst når #1783 blir fiksa

**Comment by thomasnokleby** [comment]
Denne er fikset, har korrigert mapping

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
