### ISSUE TITLE
Liste opp alle begrep

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1797]
Kommer fra behov: 
https://github.com/Informasjonsforvaltning/behov/issues/77

Ikoner og andre svg'er hentes herfra:
https://www.dropbox.com/sh/pi3534heqcbem90/AACBPGhZO8RyO9ZmdnCoC71ja?dl=0

Som: Intern leser og skrivebruker
Gitt at jeg står i Registreringsløsningens landingsside kataloger
Og jeg klikker på Begrepskatalog_
Ønsker jeg å: se en liste alle begrep som jeg kan sortere, alfabetisk på term og status
Slik at: jeg enkelt kan se begreper som allerede er registrert i begrepskatalogen, hvilke som er publisert i Felles begrepskatalog og hvilke som jobbes med (statuser), og få oversikt etterhvert som det blir mange begreper i min virksomhets katalog.

NB: Intern leser kan gjøre det samme som skrivebruker unntatt: å legge til nytt begrep.

Relatert til epos: #176
Relatert til brukerhistorier:
#75

Trådskisser skrivebruker : https://69d4ft.axshare.com/#g=1&p=oversiktside_begrep_skriverolle
Trådskisser lesebruker: https://69d4ft.axshare.com/#g=1&p=oversiktside_begrep_leserolle

Lenke til design:
https://projects.invisionapp.com/share/3SRCN149CQN#/screens/356258577
Lenke til løsningsarkitektur: se epos

Akseptansekriterier:
,# language: no
Egenskap:
Kriterier:
⦁	Alle registrerte begrep skal vises for både skrive- og lesetilgangsroller i en liste.
⦁	Det skal være mulig å sortere begrepslisten basert på kolonneheadingene Anbefalt term og status

Dekkes ikke: (Dekkes i #175)
⦁	Søke og filtrere blant begrep i registreringsløsningen
⦁	Sortering på feltene Gyldighet og Fagområde

Referanser:

Scenario: Alle registrerte begrep skal vises for skrivetilgangsrollen i en liste
Gitt at bruker er pålogget med skrivetilgang
Når bruker åpner siden for virksomhetens berepsbeskrivelser
Så skal det vises en liste med status over alle begreper opprettet av virksomheten

Scenario: Alle registrerte begrep skal vises for lesetilgangsrollen i en liste
Gitt at bruker er pålogget med lesetilgang
Når bruker åpner siden for virksomhetens berepsbeskrivelser
Så skal det vises en liste med status over alle begreper opprettet av virksomheten

Scenario: Det skal være mulig å sortere begrepslisten basert på kolonneheadingene "Anbefalt term" og "Status"
Gitt at bruker er pålogget med lesetilgang
Når bruker klikker på kolonneheadingen "Status"
Så skal listen sorteres etter verdiene i kolonnen "Status"

- [x] Test design

- [x] Test gjennomføring
[1797.xlsx](https://github.com/Informasjonsforvaltning/fdk/files/3533159/1797.xlsx)

**Comment by sindresandvik2** [comment]
Testet ferdig i denne runden.  Ingen kjente feilakkurat nå.  Godkjent av @joebrreg
