### ISSUE TITLE
Tune Søk for Begreps-katalog

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1805]
NB! Dette gjelder bare søk i Begrepskatalogen. Vi skal ikke ta for oss Datasett eller API i denne omgang.

Fra Behov:
https://github.com/Informasjonsforvaltning/behov/issues/54

Det er ønskelig å bruke noe tid på å konfigurere ElasticSearch (Timeboxes) for å forbedre søkefunksjonen vår.

I hovedsak to elementer vi ønsker: 

- [x] Søk på tittel skal vektes mye høyere enn annen treff

- [x] Treff på URIer (F.eks Publisher) i løsningen skal ikke gi treff

**Comment by thomasnokleby** [comment]
Har noe lokalt som ser ut til å booste tittel på generelle tekstsøk.

**Comment by lillelars** [comment]
@thomasnokleby  er kanskje litt upresis forklart i  oppgaven.
Et godt eksempel er ordet "Samboer"... Det gir treff i mange Begreps-tittler, men det er ønskelig å booste 100% match med søk betraktelig mer enn andre treff. Altså at Begrepet "Samboer" vil vises øverst.

**Comment by sindresandvik2** [comment]
Testet OK i UT1.

Klar forbedring . Fortsatt neon utfordringer med at direkte treff ikke kommer helt øverst.  Tas i neste tuning!
