### ISSUE TITLE
Designendringer søkeløsning for top-section 

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1806]
Fire oppgaver:

- [x] 1)  Endre farge og posisjon på lenker (må også fungere responsivt)

- [x] 2)  Farge på lenke

- [x] 4) Endre farge på søkeboks og filterknapp (mobilvisning)

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/11015f40-57a8-4f0e-bf4d-5eb2c38a2bb9)

evnt se design: https://projects.invisionapp.com/share/N9Q9157SD3U#/screens/355699912

**Comment by lillelars** [comment]
@skobba Oppdatert Task 3. Avklaringen er nå beskrvet i tasken

**Comment by skobba** [comment]
Mobilversjon har også en filer knapp som kanskje også bør være blå.

![image](https://user-images.githubusercontent.com/16732769/57999387-8769ee80-7ad5-11e9-8eaf-4743fb01d613.png)

**Comment by sindresandvik2** [comment]
Retestet OK i UT1 med Chrome, IE , Edge og Safari
