### ISSUE TITLE
Nytt søk fra trefflista i begrepskatalogen

### ISSUE THREAD

**Issue by maasgaard** [Altinn/fdk#1811]
Når jeg har søkt i begrepskatalogen og åpnet et treff, så må jeg gå tilbake til trefflista for å kunne gjøre et nytt søk. Jeg skulle gjerne hatt en "nytt søk"-knapp eller et søkefelt også på siden der jeg har åpnet treffet.

**Comment by sindresandvik2** [comment]
Et klart og konstruktivt forslag til forbedring.     @joebrreg Kan du vurdere om dette skal gjøres som en forbedring av eksisterende funksjonalitet eller om denne skal kjøres gjennom en behovsanalyse. Før vi eventuelt skal utvikle noe her må UX koples på først.

**Comment by joachim-me** [comment]
Denne må vi ta gjennom behovsprosessen. Jeg setter @marittor  som ansvarlig.

**Comment by lillelars** [comment]
Issue moved to [Informasjonsforvaltning/behov #290](https://github.com/Informasjonsforvaltning/behov/issues/290) via [**ZenHub**](https://www.zenhub.com/)
