### ISSUE TITLE
Definere arkitektur for Begrepsregistrering

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1815]
Bør levere et arkitekturdokument inni begrepskomponeten.
Stig dytter inn i archimate etter det er ferdig

**Comment by thomasnokleby** [comment]
Dokument mailet til Stig for kommentarer

**Comment by thomasnokleby** [comment]
Dokument nå publisert på https://confluence.brreg.no/display/INFFOR/Arkitektur+-+Begrepskatalog#space-menu-link-content
