### ISSUE TITLE
API-detaljside: Utvide med "Ta i bruk API'et" - Vise endepunkt (server) i API detaljside

### ISSUE THREAD

**Issue by stigbd** [Altinn/fdk#1816]
Design:
https://projects.invisionapp.com/share/7RQ8ZOGAUKF#/screens/344044369_API-PORTAL-DETALJ-Ett-Datasett--D-

For ein utvikler er informasjon om eit API sitt endepunkt (server object i OpenAPI specification) svært nyttig informasjon. I dag må ein laste ned spesifikasjons-fila for å finne denne. Det hadde forenkla mykje om denne informasjonen kunnne blitt inkludert i detalj-sida for API-et. 

Trenger URI + Description fra API-specc:
![image](https://user-images.githubusercontent.com/39513382/58311887-560d5d80-7e0a-11e9-9daf-b381aad2c794.png)

- [x] testdesign

- [ ] testgjennomføring
[1816.xlsx](https://github.com/Informasjonsforvaltning/fdk/files/3328951/1816.xlsx)

**Comment by lillelars** [comment]
@joebrreg  Kan du vurdere om dette kan taes som en liten endring? Eller om dette er en del av en større avklaring som bør tas gjennom behovsprosjektet

**Comment by joachim-me** [comment]
@lillelars Vi trenger ikke å ta denne gjennom behovsprosessen. Behovet er forstått, og det er etterspurt av flere. Vi må bare få designe på plass.
