### ISSUE TITLE
Oppdatere Kubernetes på GCP

### ISSUE THREAD

**Issue by bgrova** [Altinn/fdk#1819]
Vi bør ikke bli liggende for langt bak i versjonene.
Dette bør gjøres med jevne mellomrom.
https://cloud.google.com/kubernetes-engine/docs/release-notes#may_13_2019

**Comment by sindresandvik2** [comment]
@bgrova   Når må dette vere ferdig?

**Comment by lillelars** [comment]
Dette gjøres fortløpende automatisk
