### ISSUE TITLE
Søkeløsning LOS: Tallet i parantes bak filtervisning viser feil i forhold til totale antall datasett som vises

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1821]
Tallet i parantes bak filtervisning (LOS) blir feil i forhold til totale datasett som vises (altså tallet i fanen "Datasett") Dette bør vise det samme.

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/7951b14f-7e22-4ebe-9bfe-c6fb99902bea)

**Comment by sindresandvik2** [comment]
Duplikat
