### ISSUE TITLE
concept-cat: utvide konfigurasjon på concept-cat til å inkludere miljøspesifikke url

### ISSUE THREAD

**Issue by stigbd** [Altinn/fdk#1830]
Vi ønsker å kunne peke høstefunksjonaliteten mot ulike kilder pr miljø. Vi bør derfor kunne legge inn ulike uri-er i den relevante jenkins-konfigurasjons fil og sørge for at denne blir plukka opp av concept-cat applikasjonen.
Sjå https://github.com/Informasjonsforvaltning/fdk/blob/4fcb127a2ea38517792e998fff7ec42788ffc196/applications/concept-cat/src/main/resources/application.yml#L22

**Comment by sindresandvik2** [comment]
@joebrreg  I følge han som har rapportert dette må saken ha høy prioritet.  You fix?
