### ISSUE TITLE
Frontend: Implementer Header

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1835]
icons kan hentes herfra:
https://www.dropbox.com/sh/pi3534heqcbem90/AACBPGhZO8RyO9ZmdnCoC71ja?dl=0

**Comment by skobba** [comment]
![image](https://user-images.githubusercontent.com/16732769/59334878-bbfb4f80-8cfb-11e9-929c-784787af8cfa.png)

**Comment by sindresandvik2** [comment]
OK i UT1.    (Språkmenyen må justerast litt!)
