### ISSUE TITLE
Frontend: Implementer Brødsmulesti + Tilbakeknapp

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1836]
https://projects.invisionapp.com/share/3SRCN149CQN#/screens/356258577

NB! Husk at dette må linkes til riktig system (tilbake til registreringsløsning)

**Comment by sindresandvik2** [comment]
Ingen av de tre tilbakeknappmulighetene virker.
Brødsmulestien vises OK, men øverste valg (lengst opp ei brødsmulestien) fungerer ikke

**Comment by sindresandvik2** [comment]
Testet OK i UT1.   Brødsmulesti og tilbakeknapp OK.  Logo som tilbakeknapp er også OK.
