### ISSUE TITLE
Frontend: Implementer Tittel på virksomhet

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1838]
https://projects.invisionapp.com/share/3SRCN149CQN#/screens/356258577

Slåes opp i Publisher-tjenesten

**Comment by skobba** [comment]
Forslag til redigeringsfunksjon laget med Formik og hooks: https://codesandbox.io/s/reactformikinlinefieldeditor-w687o

**Comment by sindresandvik2** [comment]
OK.  Retestet i UT1
