### ISSUE TITLE
Frontend: Implementer hele tabellen med oversikt over begreper

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1840]
https://projects.invisionapp.com/share/3SRCN149CQN#/screens/356258577

**Comment by sindresandvik2** [comment]
Farge på tittelbaren i tabellen er for GRÅ.  Sjekk mot design.    (Fargen som finnes dagens FDK er også feil....)

Og så var det de pilene da......

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
