### ISSUE TITLE
Link fra Registreringsløsning til autonom Begrepsregistrering

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1843]
Ikonet for å kunne registrere Begrep
![image](https://user-images.githubusercontent.com/39513382/59330940-117f2e80-8cf3-11e9-8d0b-bbb531d7d517.png)

**Comment by skobba** [comment]
![image](https://user-images.githubusercontent.com/16732769/60251086-31ece280-98c8-11e9-8666-e552fec0a162.png)

**Comment by skobba** [comment]
![image](https://user-images.githubusercontent.com/16732769/60338940-916def80-99a7-11e9-984e-c4de2db56544.png)

**Comment by sindresandvik2** [comment]
Testet OK i UT1. Tilbakeknapper virker fortsatt ikke. Følges opp i #1836
