### ISSUE TITLE
Backend: Liste opp begreper på gitt firma

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1844]
Husk sortering og paging

**Comment by thomasnokleby** [comment]
Underoppgaver som må tas:

- [x] Få opp lokal postgresql base
- [x] Planlegge og implementere databaseschema for begrepsregistrering
- [ ] Implementere en REST-kontroller med ønsket funksjonalitet. (Uten tilgangskontroll for øyeblikket)
