### ISSUE TITLE
Backend: Implementere endepunkter for høsting av begreper ut mot søkeløsning

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1845]

**Comment by stigbd** [comment]
Har lagt til openAPI-spesifikasjon for SKOS-AP-NO endepunktet til concept-catalogue i branch feature/skos-ap-no-endepunkt/issue1845

**Comment by stigbd** [comment]
Vi må skaffe en url som er tilgjengelig frå internet til skos-ap-no endepunktet til concept-catalogue.

**Comment by stigbd** [comment]
Url som skos-ap-no endepunktet er tilgjengelig eksternt på er som følger:
https://registrering-begrep-api.ut1.fellesdatakatalog.brreg.no/collections

**Comment by sindresandvik2** [comment]
Blir testa i andre tasker
