### ISSUE TITLE
Frontend: Sett opp typescript, react, testrammeverk med mer

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1846]
- [x] typescript oppsett

- [x] react oppsett

- [x] testrammeverk

- [x] skjelett for begrepsregistrerings-frontend (CSS,html osv inngår her)

**Comment by skobba** [comment]
![image](https://user-images.githubusercontent.com/16732769/59018528-5d8b2880-8846-11e9-8866-6ff32d670966.png)
