### ISSUE TITLE
Validering BE

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1848]
Alle felter skal valdideres i BE
Når status blir satt til Publiser må feltene valideres

@stigbd  skaffer regler på innholdsvalidering.  Forøvrig skal spesifikasjonen SKOS-AP-NO følges

**Comment by stigbd** [comment]
Vi skal ikkje utøve "innholdsvalidering". Vi skal validere på følgande egenskaper:
- obligatoriske felter, og
- kardinalitet.
Valideringskrav vil bli gjort tilgjengelige på https://github.com/Informasjonsforvaltning/behov/issues/81

**Comment by sindresandvik2** [comment]
Testet i UT1 . trigger noen flere Korrekte" feilmeldinger som kanskje bør justeres litt i front end.
