### ISSUE TITLE
Frontend: Et kryss i søkefeltet for å refresh søk og resultatliste

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1851]
Tatt ut fra #1806

 3)  Ønsker et kryss 'X' som skal fjerne det man søker på. 
- Tilfelle 1: Dersom bruker har skrevet inn noe i søkefeltet og trykker 'X' skal søkefeltet nullstilles (samme funksjon som hvis man trykker Esc)
- Tilfelle 2: Dersom bruker har skrevet inn noe i søkefeltet og gjort et søk, deretter trykker 'X' skal søket nullstille seg, resultatsettet nullstilles, men filtere skal beholdes.

Design: 
https://projects.invisionapp.com/share/N9Q9157SD3U#/screens/355699912

**Comment by skobba** [comment]
![image](https://user-images.githubusercontent.com/16732769/58160632-2251fc80-7c7f-11e9-9799-3567f9b99f80.png)

**Comment by sindresandvik2** [comment]
Retestet OK i UT1  EN ny feil rapportert
