### ISSUE TITLE
Begrep: Endre fra "Eier" til "Ansvarlig" i filter

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1863]
Filter viser feil tekst

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/f0ea0f97-714a-4fc5-bb88-8cb50e2ef30c)

**Comment by lillelars** [comment]
@skobba Du har ganske god kontroll på denne type feil nå ;) Kan du ta denne også?

**Comment by skobba** [comment]
Affirmative :)

**Comment by sindresandvik2** [comment]
Testet OK i UT1 for alle tre språk
