### ISSUE TITLE
Søkeportal: X'en i søkefelt kommer over i søkeboksen når du bytter til Engelsk

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1865]
Ved endring til Engelsk:

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/301f1ff1-188b-4fc3-b234-72ec60d19359)

**Comment by lillelars** [comment]
@skobba er dette noe som går raskt å fikse? i så fall - kan du ta dette?

**Comment by skobba** [comment]
Tar denne også.

**Comment by sindresandvik2** [comment]
Testet OK i UT1
