### ISSUE TITLE
Designendringer søkeportal

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1888]
Se overordnet design design: https://projects.invisionapp.com/share/N9Q9157SD3U#/screens/355699913

- [x] Autoritativ kilde har nytt design og plassering 
Testa OK i Chrome, IE, Edge og Safari

- [x] Nytt design på tematisering for datasett 
Testa OK i Chrome, IE, Edge og Safari
- [x] Tab'ene "Datasett", "API-er", "Begreper" og "Informasjonsmodeller" har ny farge og med ikoner. De har også fått mindre font-weight og font-size
Testa OK i Chrome, Edge, IE og Safari

- [x] Ikoner for låsene på Datasett er oppdaterte (gjelder både sammendragsbokser og detaljside for datasaett)
OK, men gulfargen må byttes til Warning -dark

- [x] Detaljsidene har nå fått ikoner i toppen: https://projects.invisionapp.com/share/N9Q9157SD3U#/screens/345287057
OK i Chrome,og Edge.  Feil plasering i Safari og IE
Ikonet for Informasjonmoddeler vises ikke. OK for de tre andre katalogene

- [x] Skriftstrl under søkeboksen "Søk blant ......" er noe mindre
OK. I Chrome, Edge, IE og Safari

- [x] Tekst på Sorteringsknapper skal være blå når den er klikkbar
OK i Chrome, Edge , IE og Safari

- [x] Oppdatert illustrasjon i banner (kommer også som svg)
OK i Chrome, Edge , IE og Safari

Ikoner: Link til SVG-filer:

**Comment by sindresandvik2** [comment]
Test ok.  Kontrollert av Lene!   3 mindre feil blir registrert i egne feilmeldinger
