### ISSUE TITLE
Venstremeny: Forbedre menyen med en tittel

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1892]
"Gå til"
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/d26e8fbb-99a4-4244-b824-d726df2b26ad)

**Comment by sindresandvik2** [comment]
Tilleggsjustering:   Pass på at området mellom brødsmulestien og "Gå til"  er i henhold til design.  Gå til skal alltid være på samme høyde som Tittel på detlajsiden.
På Datasett detaljsiden er  venstremenyen for langt oppe. 
![image](https://user-images.githubusercontent.com/42966644/62543703-b6833700-b85e-11e9-9762-f09c8cd804b4.png)

På detaljsidene for API, Begrep og Informasjonmodeller  er venstremenyen nå for langt nede!
