### ISSUE TITLE
Gjøre url front-end konfigurerbare

### ISSUE THREAD

**Issue by stigbd** [Altinn/fdk#1899]
Det ser ut til at url i front-end er "hardkodet", slik at feks url i https://demo.fellesdatakatalog.brreg.no til registreringsløsningen (" bak "Logg inn i registreringsløsningen") peikar på produksjonsversjonen av registreringsløsningen. (Sjå skjermdump.) Dette er uheldig i demo-situasjoner.
![image](https://user-images.githubusercontent.com/1702357/58459338-70f21180-812b-11e9-8cd4-bc8dba4adb5f.png)

Vi burde gjere alle slike url konfigurerbare pr miljø.

**Comment by sindresandvik2** [comment]
@joebrreg  Kjører du dette saman me d andre utviklingsoppgåver i teamet?
