### ISSUE TITLE
Klargjør kobling mellom Begrepsregistrering og FDK

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1900]
Sette seg inn i og se hva som kan gjøres for å klargjøre denne koblingen..

**Comment by thomasnokleby** [comment]
Her er kjernen av saken at det som Begrepsregistrering produserer (en docker container med frontend og en docker container med backend) må på en eller annen måte tas i bruk av fdk. Etter avklaring med Stig har vi to koblinger: FDK skal kunne høste fra begrepsregistrering sin begrepspubliserer og i registreringsløsning skal bruker kunne trykke knapp for begrepsregistrering, om begrepsregistrering-container er oppe. Dette betyr i klartekst at FDK som helhet skal kunne fungere helt fint også når de 2 begrepsregistreringscontainernerne er nede eller ikke-eksisterende. Når det gjelder bygg og deploy tenker jeg Bjørn kan ta stafettpinnen videre, bygget må da bygge begrepsregistrering, og dytte de 2 kontainerne over i fdk sitt kubernetescluster.

**Comment by thomasnokleby** [comment]
De eneste koblingene mellom resten av fdk og begrepsregistrering blir da at fdk har en url for høsting (som da bare vil feile for den url om begrepsregistrering er nede) og at fdk har en url for å kunne teste om begrepsregistrering UI er oppe (slik at fdk vet om den skal vise knapp for begrepsregistrering eller ikke) og selve urlen bruker skal redirectes til når en bruker i fdk trykker begrepsregistreringsknappen

**Comment by stigbd** [comment]
Kommentarane til Thomas er korrekte, men eg kan godt oppsummere: 
Sammenhengen mellom Begrepskatalogen (aka begrepsregistrering) og resten av FDK-tjenestene består av følgande:
1. Høstingen i concept-cat skal høste fra et skos-ap-no endepunkt i begrepskatalogens API (på samme måte som concept-cat høster BRREG sin begrepspubliserer)
2. I registreringsløsningens startside, skal man kunne klikke på Begrepsregistrering og bli tatt over i Begrepskatalog GUI (på same måte som for Datasett og API). Dette skal framgå av skisser.

> Når det gjelder bygg og deploy tenker jeg Bjørn kan ta stafettpinnen videre, bygget må da bygge begrepsregistrering, og dytte de 2 kontainerne over i fdk sitt kubernetescluster.

Eg meiner dette er utført, sjå feks https://github.com/Informasjonsforvaltning/fdk-config/commit/0dd5e550e545b804cb38ffa791c6f10427430400
