### ISSUE TITLE
[FDK] Skille mellom LOS-tema og EU-tema i filtermeny

### ISSUE THREAD

**Issue by stigbd** [Altinn/fdk#1905]
Det er forvirrande at det i filtermeny er to forekomster av "Tema". Vi bør merke disse på same måte som dei merka i registreringsløsningen.

**Comment by joachim-me** [comment]
@lillelars Hadde vi ikke en oppgave på dette? At vi skulle markere EU-temaene med Utgår?

**Comment by stigbd** [comment]
Dette gjelder altså Felles datakatalog (Portal, aka "søkeløsning). Forslag til tekst for EU-tema:
"EU-tema (under utfasing)"

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
