### ISSUE TITLE
Los tema i Søkeportalen viser ikke korrekt hierarkiet med Hovedtema og Undertema

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1914]
Når en ekspanderer LOS tema vises en litt tilfeldig opplisting av LOS-temaene i filtermenyen.   Tema skal struktureres slik at undertema ligger under hovedtema og at desse kun skal vises njår en ekspanderer en hovedkategori.. (Ting er helt riktig i prod!) 
![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/398c7dfe-c16a-4806-8170-9be974339eb8)

**Comment by skobba** [comment]
Følgende commit gjør at resultatet fra 2 APIer endrer seg:
feature[reference-data] LOS Tema is now stored in our Db on first rea… (#1700)

1. Resultatet fra LOS API (introduserer internalId og children går fra null til [])
![image](https://user-images.githubusercontent.com/16732769/58808623-a8285d00-861a-11e9-86f9-fd22e3201f1a.png)

2. Resultatet fra dataset API (mangler bindestrek):
![image](https://user-images.githubusercontent.com/16732769/58808899-34d31b00-861b-11e9-9e14-2fb654f32791.png)

**Comment by thomasnokleby** [comment]
Dette var en regresjonsfeil, som forårsaket at Tema på toppnivå da hadde mellomrom, ikke bindestrek. Fix er merget.

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
