### ISSUE TITLE
Publisert datasett vises ikke i portalen

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#1933]
Datasettbeskrivelsen "Ektepaktregisteret" (lenke  i registreringsløsningen: https://registrering.fellesdatakatalog.brreg.no/catalogs/974760673/datasets/cafe6434-2540-4a2d-a629-0fdf203c7c9d ) vises ikke i portalen når jeg søker på Ektepaktregisteret. Publiseringen ble aktivert 03.06.19 og skulle vel da være tilgjengelig i portalen 04.06.19. Jeg har lagt ved kopi av status i registreringsløsningen og søk i portalen som ble utført i dag
[Ektepaktregisteret.docx](https://github.com/Informasjonsforvaltning/fdk/files/3260488/Ektepaktregisteret.docx)

**Comment by sindresandvik2** [comment]
Nå er Ektepaktregisteret også på plass.   Det viste seg å være en midlertidig stopp i innhøstingsjobbene.

**Comment by RogerSOlsen** [comment]
Takk for varsel!

Mvh Roger

tir. 11. jun. 2019 kl. 08:37 skrev sindresandvik2 <notifications@github.com
