### ISSUE TITLE
Koble ekte data til liste over begreper

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1942]
Nå bruker vi bare Mock-data... skal må gå mot reelle data når backend har dette klart.

**Comment by oyvindis** [comment]
- Opprette config for å koble mot api-host
- Bruke React Hooks i stedet for Redux for global state
- Hente liste fra api og koble mot komponent

**Comment by bgrova** [comment]
Ingressruter konfigurert for begrepsregistrering api:
https://registrering-begrep-api.ut1.fellesdatakatalog.brreg.no
https://registrering-begrep-api.st1.fellesdatakatalog.brreg.no
https://registrering-begrep-api.it1.fellesdatakatalog.brreg.no
https://registrering-begrep-api.fellesdatakatalog.brreg.no

Disse vil nå ligge i miljøvariabelen CONCEPT_REGISTRATION_API i concept-catalogue-gui

**Comment by sindresandvik2** [comment]
Testa OK med nye data.  Sortering OK. Design OK.  Resten blir testa når det er full data connection
