### ISSUE TITLE
Eksponere API til frontend

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1948]
- [x] Opprette miljøvariabler for backendURL i frontend - Øyvind legger til i frontend

- [x] Oppsett helmtemplate og configfiler med miljøvariabler

- [x] Vurdere/se på nginx oppsett

**Comment by bgrova** [comment]
Ingressruter konfigurert for begrepsregistrering api:
https://registrering-begrep-api.ut1.fellesdatakatalog.brreg.no
https://registrering-begrep-api.st1.fellesdatakatalog.brreg.no
https://registrering-begrep-api.it1.fellesdatakatalog.brreg.no
https://registrering-begrep-api.fellesdatakatalog.brreg.no
