### ISSUE TITLE
Få bankenes API-spesifikasjoner inn i API-katalog (demo)

### ISSUE THREAD

**Issue by joachim-me** [Altinn/fdk#1957]
Bankenes API-spesifikasjoner skal inn i API-katalogen. Dette skal gjøres via APIS.csv, dvs. ikke gjennom registreringsløsningen.

- [x] Lage spesifikasjonsfiler @stigbd 

- [x] Legge til oppdatert APIS.csv @stigbd 

- [x] Kodeendring for å kunne hente ut Tjenestetype (serviceType) fra APIS.csv

- [x] Deploye endringer til https://demo.fellesdatakatalog.brreg.no/

- [x] Hack for å få inn organisasjonsnavn i portal?

**Comment by sindresandvik2** [comment]
Problemet med "Ukjent" tilbyder må fikses!

**Comment by bgrova** [comment]
Oppskrift: https://confluence.brreg.no/display/APP/Legge+inn+nye+publishere
