### ISSUE TITLE
Konfigurering av Keycloak

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1958]
Deploy frontend, backend og keycloak sammen og verifiser at dette fungerer

 - [x] utvikle byggeskript for sso container - rest user module og data import (template+miljøvariablene).
 - [x] konvertere altinn nøklene i jenkins variabler. (Bjørn)
 - [x] koble sso til ID-porten test i it1
Error:  “Client authentication failed. Client not allowed to use token endpoint auth method client_secret_post. (correlation id: 91179f24-a828-5349-8b9f-5d0b8441d471)”
   - Prøv å snakke med idporten, det står i dokumentasjson at det skull være støttet
   - prøv å implemntere JWT-autentisering
   - custom ISP implementasjon for idporten (basic auth)
 - [x] bytte broker navn redirect_uri fra "oidc" til "idporten-oidc"(email til difi, Bjørn)
 - [x] tilla hostnavn sso:8084 som redirect_uri (email til difi, Bjørn)
 - [x] få nøklene til ID-porten prod (Bjørn)
 - [x] koble sso til ID-porten prod i prod (Bjørn)
 - [x] ID-porten mock med 5 brukerne
 - [x] koble sso til ID-porten mock i dev
 - [x] koble sso til ID-porten mock i ut1 og st1
 - [x] koble sso til altinn test i dev, ut1, st1 og it1
 - [ ] koble sso til altinn prod i prod(Bjørn)
 - [x] (opt) altinn mock med 5 brukerne
 - [x] (opt) koble sso til altinn mock i dev, ut1 og st1
 - [x] fjerne avhengighet av autorisering (gjennom entitynameservice) i catalogs
 - [x] deploy enhetsregisteret-proxy-mock til miljøene med altinn mock (ut1, st1)
 - [x] logout
 - [x] fjerne sso keys fra github, generere eller sette fra conf.
 - [x] fetch public key fra sso til å verifisere token i registration-api
 - [x] store refresh_token, så at side kan ble refreshet
 - [x] renew token
 - [x] virsksomhetstype/orgn whitelist filter til altinn brukerne
 - [x] ha fdk idporten-mock som en realm, ikke som sitt eget service, tar mye utviklerspc ressursser
 - [x] refresh med utgått token.
 - [ ] deploy alt (sso,altinn, user-api, enhetsregisteret til prod unntatt klientene (registration-api+registration-react). Sjekke login og tilgang fra  /auth/realms/fdk/account

**Comment by sindresandvik2** [comment]
Blir testet i egen test task
