### ISSUE TITLE
Backend: tilgjengligjør feltene "server Description" og "server uri" til frontend

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1978]
Trenger disse to feltene fra API-speccen
![image](https://user-images.githubusercontent.com/39513382/59917073-36754f00-9421-11e9-9cf4-ba00e246b3f4.png)
![image](https://user-images.githubusercontent.com/39513382/59917084-41c87a80-9421-11e9-91dc-d50ae6833574.png)

**Comment by frodegill** [comment]
server url og description sendes allerede
