### ISSUE TITLE
frontend: ny bolk/seksjon på detaljsiden API

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#1979]
Se design på: "Ta i bruk API'et"
https://projects.invisionapp.com/share/7RQ8ZOGAUKF#/screens/344044369_API-PORTAL-DETALJ-Ett-Datasett--D-

- [x] flytt dokumentasjon og specification linkene til denne bolken.

- [x] lag bolken med korrekt innhold

**Comment by sindresandvik2** [comment]
Testet OK i Chrome.   En justeringsissue opprettet
