### ISSUE TITLE
Oppdatere begrepet - PATCH

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1990]
- [x] utvid API-spekk med PATCH

- [x] implementer PACTH i JAVA

**Comment by stigbd** [comment]
Då har eg oppdatert spesifikasjonen som avtalt. I tillegg har eg rydda bort duplikat-spesifikasjon.
https://github.com/Informasjonsforvaltning/concept-catalogue/pull/40

**Comment by thomasnokleby** [comment]
Har lagt til 4 nye felt som avtalt

**Comment by sindresandvik2** [comment]
Vil bli testa under slutttest av brukerhistorien
