### ISSUE TITLE
Legg på Hjelpetekster på alle felter

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#1992]
https://projects.invisionapp.com/share/3SRCN149CQN#/screens/356259396

- [x] Hjelpetekst Definisjon

- [x] Hjelpetekst + tittel "tillatt og frarådet term"

- [x] Hjelpetekst + titler "bruk av begrep"

- [x] Hjelpetekst + titler "kontaktinformasjon"

Design: https://projects.invisionapp.com/share/3SRCN149CQN#/screens/372001856

Se eksisterende helpeteks i registration:
https://registrering.ut1.fellesdatakatalog.brreg.no/catalogs/910244132/datasets/b566dbeb-f9e6-4a03-8bef-ed8309d30120

**Comment by skobba** [comment]
![image](https://user-images.githubusercontent.com/16732769/60709582-18bfe380-9f11-11e9-84ba-cc0183d9c6b7.png)

**Comment by skobba** [comment]
concept-catalogue-gui workspace lines count: 
   total files : 95
   total code lines : 14263
   total comment lines : 48
   total blank lines : 340

**Comment by sindresandvik2** [comment]
Test gjennomflørt. Noen mindre issues registrert
