### ISSUE TITLE
Legg til "Kilde"

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2001]
Design: https://projects.invisionapp.com/share/3SRCN149CQN#/screens/372852560

![image](https://user-images.githubusercontent.com/16732769/61043577-eada1380-a3d6-11e9-8c21-25b9c7a35bb7.png)

Samme select i registration:
https://registrering.ut1.fellesdatakatalog.brreg.no/catalogs/910244132/datasets/90430949-edbd-434c-9990-17aea72ab107
![image](https://user-images.githubusercontent.com/16732769/61045542-58883e80-a3db-11e9-96af-fbee0481f694.png)

**Comment by skobba** [comment]
http://10.29.2.176:8083/986105174/6d770978-34b0-439c-a7cb-adacb3612220000

**Comment by skobba** [comment]
"So you search Al Gore’s amazing Internet and find out the go-to solution to manage the app’s state is Dan Abramov’s Redux"

**Comment by stigbd** [comment]
Oppdatert API-spesifikasjon som støtter kilde ligger i følgande branch:
feature/kilde/issue2001
cc: @thomasnokleby @skobba @oyvindis

**Comment by skobba** [comment]
![image](https://user-images.githubusercontent.com/16732769/63082067-89f9aa00-bf45-11e9-8963-487e81b12b55.png)

**Comment by skobba** [comment]
Default kildeBeskrivelse må være null og ikke "egendefinert", se -> https://github.com/Informasjonsforvaltning/fdk/issues/2169

**Comment by thomasnokleby** [comment]
Dette er nå merget i concept-catalogue repoet

**Comment by sindresandvik2** [comment]
Ping pong tilbake til BE:  
Kan ikke lagre objekt pp Kildebeskrivelse. Se her: 
anbefaltTerm: "adf", definisjon: "", kildebeskrivelse: {}, merknad: ""}
anbefaltTerm: "adf"
definisjon: ""
kildebeskrivelse: {}
merknad: ""

**Comment by sindresandvik2** [comment]
Stort sett ok.  Resten tas i egne bugs!
