### ISSUE TITLE
Søkeportalen, Datasett:   Dersom et datasett har en API-distribusjon vises denne som API (Undefined) i sammendragsboksene

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2005]
For hver API-dsitribusjon som blir datt opp vises denne med API (Undefined ) i sammendragsboksene. Inne på detaljsiden vises API-dsitribusjonene OK

Dersom en sette er opp en API-distribusjon som andre distribusjoner med type = API vises denne distribusjonen helt OK i sammendragsboksen. 

![image](https://user-images.githubusercontent.com/42966644/60094133-81f26a80-974b-11e9-9012-f887307fcdb9.png)

**Comment by lillelars** [comment]
Nytt design, håndtert på annen måte.
