### ISSUE TITLE
Ferdigstille SQL i PROD

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2018]
- [x] Låse ned skjema Public

- [ ] Sikkerhetsgjennomgang for db**

**Comment by bgrova** [comment]
create rettighet på schema public fjernet: REVOKE CREATE ON SCHEMA public FROM PUBLIC;
Ingen eksterne nettverk er autorisert til å connecte til instans fdk-sql-prod
Passord for brukeren postgres er satt til en 16 tegn lang random-generert streng av bokstaver, tall og tegn.
Backup av databasen tas automatisk hver natt
High availability er ikke konfigurert (ekstra kostnad - må vurderes hvis bruken og trafikken blir stor)
