### ISSUE TITLE
Implementer "publiseringsbar"

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2026]

**Comment by stigbd** [comment]
Då har eg lagt på eit endringslogelement i API-beskrivelsen med timestamp og brukerid. Dette fins i feature-branch https://github.com/Informasjonsforvaltning/concept-catalogue/tree/feature/sist_endret/issue2026
cc: @thomasnokleby

**Comment by oyvindis** [comment]
Første del inneholder av publiseringsbar inneholder ikke validering, dvs. publisering er lov selv om skjema ikke validerer i frontend.
I tillegg mangler tekst for "... lagret for noen sekunder siden", foreløpig gis ingen info om når begrepet sist ble lagret.

**Comment by sindresandvik2** [comment]
Delvis testa.  OK så langt.
