### ISSUE TITLE
Utvide feltet "merknad" til 5 linjer høyde

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2029]
Nå er det slik:
![image](https://user-images.githubusercontent.com/39513382/60885675-66f61f00-a250-11e9-9c86-736f4e5330db.png)

Ønsker slik (se datasett aktualitet som eksempel): 
![image](https://user-images.githubusercontent.com/39513382/60885707-7aa18580-a250-11e9-91e7-0a4510801b86.png)

**Comment by sindresandvik2** [comment]
Testet OK i Chrome og Edge
