### ISSUE TITLE
API-reg + Beg-reg: Fjerne Tilbake-knapp

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2032]
Vi ønsker å forbedre breadcrumben og bredden på main-innholdet og starter derfor med å fjerne "Tilbake-knappen"
For begrep:
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/14ec8674-182c-4aa9-a5ff-41e534defee0)

For datasett:
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/2e26d565-2a6c-4a99-86e6-394cfda6cb33)

**Comment by sindresandvik2** [comment]
Retestet OK i Chrome
