### ISSUE TITLE
Main-content i data-reg og beg-reg skal utvides til å være like bred som API-reg

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2033]
NB! Denne oppgaven gjelder både for data-registrering og Begrep-registrering

Ser slik ut i datareg:
![image](https://user-images.githubusercontent.com/39513382/61031608-2a493580-a3c0-11e9-9117-8ae3abd4fd40.png)

Ønskes at det skal se slik ut:
![image](https://user-images.githubusercontent.com/39513382/61031672-464cd700-a3c0-11e9-9f2a-01e5e62c5066.png)

**Comment by sindresandvik2** [comment]
Retestet OK i Chrome
