### ISSUE TITLE
Forbedring av breadcrumb - alle registreringsløsninger

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2034]
Se nytt design av breadcrumb:
https://projects.invisionapp.com/share/3SRCN149CQN#/screens/372852559

Skal løses for API-reg, Datasett-reg og Begreps-reg

"Her kommer omsider den lista du skulle få. Følgende oppdatering i design vedrører header og tittel:

- [x] Brødsmulesti
Skriften er større
Vi har også gjort endring i hva som skal stå i brødsmulestien («Registrer nye datasett/API-/begrepsbeskrivelse»)
Har lagt til en heltrukken linje under brødsmulestien

- [x] Tilbake-knapp
Denne er fjernet til fordel for mer tydelig brødsmulesti

- [x] TIttel registrering
Tittelen skal være «Registrer ny datasetttbeskrivelse» (helt til man går tilbake til oversikten, da skal tittelen tilsvare datasettets/API-ets/begrepets navn?)
Virksomhetsnanv under tittel er fjernet.

Skisse registrering: https://invis.io/N9Q9157SD3U#/343911173_DATA-REG-Tittel--D- 
Skisse portal: Skisse for portal kommer. En plugin lager for tiden krøll i skissene, sender lenke når jeg har fått ordnet det og oppdatert designet i InVision.
"

**Comment by oyvindis** [comment]
Tar en design-review med Lene før jeg legger denne til review.

**Comment by sindresandvik2** [comment]
OK.  Men en liten justering til er nødvendig (opprettes som ny issue)
