### ISSUE TITLE
Kjøring av tester som bruker database i Jenkins (og leser environment variable)

### ISSUE THREAD

**Issue by thomasnokleby** [Altinn/fdk#2035]
Jeg har nå slått av 3 tester i concept-catalogue, men vil gjerne gå gjennom dette sammen med deg, Bjørn. 
De tre miljø variablene FDK_SQL_JDBC_CONNECTION , FDK_SQL_USERNAME, FDK_SQL_PASSWORD trengs for å kjøre opp testene, men det virker ikke som dem er tilgjengelige under bygget (når det kjører testene).

**Comment by lillelars** [comment]
Sjekk om denne er gyldig lenger. Hvis ikke - close issuen.

**Comment by thomasnokleby** [comment]
Vi kjører nå tester som krever db i jenkins på en annen måte med et annet oppsett.
