### ISSUE TITLE
Feil plassering av ikon på detaljsiden for IE og Safari

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2053]
Feilen gjelder kun Safari og IE   (OK i Chrome og Edge) 
Ikonet er plassert for lavt. Se screen shot
![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/8c32d9ad-6ba1-4efe-afc3-6db802d58c3b)

Fix i IE skal ikke utføres dersom denne er tidkrevende

**Comment by skobba** [comment]
![image](https://user-images.githubusercontent.com/16732769/63450297-fabb2d80-c441-11e9-8f6a-ad323ccf7c00.png)

**Comment by sindresandvik2** [comment]
TEstet ok Av Lene
