### ISSUE TITLE
Ikon mangler på detaljsiden for Informasjonsmodeller

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2054]
![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/1ce3a0c0-cf50-40d7-982d-8f0bef1aacb5)

**Comment by skobba** [comment]
Mangler informasjonsmodeller lokalt.

**Comment by sindresandvik2** [comment]
Testet OK i Chrome  og i Safri!
