### ISSUE TITLE
Merkelig feil i Prod ang visning av detaljsiden Datasett

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2056]
Feilen er så langt kun identifisert på min (Sindres) testmaskin i CHROME.  (OK i Edge og IE). 
Feilen oppstår IKKE på andre testmaskiner (F.eks. Joackims eller Stigs PC-er) 

Feilen gjelder kun når en åpner datasett med såpass stor beskrivelsestekst at en må ekspandere feltet for å se hele teksten.  Altså, feilen kan ha noe med mengde data som skal åpnes...?

Feilmelding: Something went wrong

Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Full text: 
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

**Comment by lillelars** [comment]
Denne er duplikat og vi fant ut feilen. Nå oppstår den bare i eldre versjoner av IE :) Lukker derfor denne, ettersom vi ikke skal støtte dette.
