### ISSUE TITLE
Feil "lufting" og designjusteringer - Begrep detaljsiden

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2059]
Gjelder egentlig hele detaljsiden for registrering av begrep.

1) Det er for mye luft under hjelpeteksten (Før en ekspanderer hjelpeteksten)
2) For lite luft under selve registreringsfeltet
3) For lite luft under sleve "seksjonsoverskriften"    (Se design) 

Det skal være (optisk) like mye luft på alle kanter. Det kan forøvrig se ut til at det ligger en p-tag inni en p-tag, og at det er fjernet margin kun på den ytterste p-tagen.

Obligatorisk-label henger litt ifht. tittelen i hjelpetekst-boksen. Fint om denne kan løftes opp slik at den harmonerer bedre med tittelen.
(hilsen Lene)

**Comment by LeneSundsbo** [comment]
1. Dette er fikset, men det skal også være like lite luft når hjelpeteksten er ekspandert.
2. Dette gjelder fremdeles for Safari og Chrome (mac). Ønsker at margin økes.
3. Gjelder fremdeles for Safari og Chrome (mac). Det er altså snakk om luft under streken som er under tittel.
4. _Det skal være (optisk) like mye luft på alle kanter. _ Gjelder fremdels for Safari og Chrome (mac). Det er altså padding på den enkelte registreringsseksjonen det er snakk om.
5. _Det kan forøvrig se ut til at det ligger en p-tag inni en p-tag, og at det er fjernet margin kun på den ytterste p-tagen._ Regner med at det er snakk om hjelpeteksten. Det ser i så fall ut til å gjelde fremdeles. Dette henger nok sammen med punkt 1, da det ligger margin på den ytterste p-taggen.
6. _Obligatorisk-label henger litt ifht. tittelen i hjelpetekst-boksen. Fint om denne kan løftes opp slik at den harmonerer bedre med tittelen._ Gjelder fremdeles for Safari og Chrome (mac). Her er det snakk om små justeringer, nok til at det ikke føles som labelen henger.

**Comment by oyvindis** [comment]
Designreview på siste endringer er godkjent av Lene.

**Comment by sindresandvik2** [comment]
OK også i UT1
