### ISSUE TITLE
Implementere spesifikasjon

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2069]
Implementere  Open API-spesifikasjonen i BE

**Comment by stigbd** [comment]
Ref kommentaren i https://github.com/Informasjonsforvaltning/fdk/issues/2068#issuecomment-519507040

**Comment by stigbd** [comment]
Eg har gjort ein fix på denne, ver snill å sjå på https://github.com/Informasjonsforvaltning/concept-catalogue/pull/57

**Comment by thomasnokleby** [comment]
PR akseptert og merget. Denne er ferdig
