### ISSUE TITLE
Alle brukere kan se alle begrepslister

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2078]
I UT1 kan en nå se de begrep som er registret for brukeren "Ramsund" når en er logget inn som Reinli.  Dette medfører at det ser ut som at en kan endre/legge til nye begrep uten at det blir lagret. 

Det virker som at Ramsund nå er hardkodet.

**Comment by thomasnokleby** [comment]
Problemet her ser ut til å være at det som var tiltenkt et default firma, faktsk overskriver verdier som kommer inn. Fikset nå

**Comment by sindresandvik2** [comment]
Fiksa, men mange nye problem dukka opp
