### ISSUE TITLE
Høsting av nye begrep

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2086]
Etter at et nytt begrep er publisert må det da også kunne høstes slik at det vises i Søkeportalen.
Legg til Concept- catalog som HArvest mål!

Akseptansekriteriet for denne tasken er at nytt begrep skal kunne vises i Søkeportalen etter publisering og kjøring av høsting av begrep!

Undertasker på denne:
Endepunktet for høsting opp:

- [x] Lokalt

- [x] Ut1

- [x] St1

- [ ] It1

- [ ] Prod

- [ ] Legge til høsturl (prod) i konfigurasjon på concept-cat i fdk (så dette faktisk blir høstet)

**Comment by thomasnokleby** [comment]
Har noe som ser ut som et konfigurasjonsproblem med nginx. Jobber med det

**Comment by thomasnokleby** [comment]
Løst. For å kunne teste videre så trengs det at ut1 promoteres til st1 (og it1 når den tid kommer)

**Comment by sindresandvik2** [comment]
Fungerer for det meste,  mangler er spsifisert i egne feil
