### ISSUE TITLE
Sortering på Fagområde feiler

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2088]
Derosm en klikker på sorteringsikonene på toppen av kolonnen Fagområde 
![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/5168e551-cf03-4ba3-9b5b-261ef7a9f281)

dukker denne feilmeldingen opp: ![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/ef79dc6c-e0d4-4ea5-95b6-7c55e9d58da3)

**Comment by lillelars** [comment]
@sindresandvik2 gjelder denne fortsatt? Funker hos meg

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
