### ISSUE TITLE
Lenke til eksterne lenker fra hjelpetekst skal åpnes i ny fane

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2094]
Dersom hjelpeteksten inneholder en lenke og bruker trykker på den skal lenken åpnes i ny fane slik at bruker ikke blir kastet ut av registreringsløsningen.

I tillegg må lenken indikeres med et "ekstern-lenke" symbol  ![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/ed534a1e-6942-408e-9e30-4d02c736e406)

**Comment by sindresandvik2** [comment]
Ny fane blir åpnet, men alle får konsekvent 404.

Symbol   image.png mangler også!  Setter tasken tilbake til "Under arbeid"

**Comment by skobba** [comment]
Mangler et "ekstern-lenke" symbol  
![image](https://user-images.githubusercontent.com/16732769/63579413-e76ba780-c592-11e9-86cf-bc78d8f72ea3.png)

**Comment by sindresandvik2** [comment]
Ny tab dukker opp og ikon er på plass   (men lenka gir 404) tar det i eigen sak!)
