### ISSUE TITLE
Spesifiser løsning

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2098]
Løsningen skal godkjennes av @stigbd  før implementering

**Comment by markkopaas** [comment]
Vi kan bruke feature toggle. De brukere som må ha tilgang før autorisering, skal instrueres å slå på feature toggle. Vi kan kalle det "CONCEPT_REGISTRATION"

Akkurat nå styrer vi feature toggle gjennom localStorage, men det er teknisk mulig også til å styre det fra server konfigurasjon.

**Comment by stigbd** [comment]
Eg er usikker på om dette løyser oppgåva som er:
- å beskytte https://registrering-begrep.ut1.fellesdatakatalog.brreg.no/, og
- å beskytte api som gui bruker, dv https://registrering-begrep-api.ut1.fellesdatakatalog.brreg.no/begreper
Gjerne med basic autentication eller lignende. 

Feature toggle løyser vel ingen av disse to?

**Comment by markkopaas** [comment]
Feature toggle bare fjerner lenke fra registreringsløsning til brukere som ikke ha kunnskap om å slå det på, og på den måte kan vi deploye develop branch helt opp til prod nivå, og sjekke sso setup (altinn+ idporten)

Kanskje vi kan skru av hele ingress på de tjenestene som er ikke ferdig? 
Vi kjører tesster i ut1 og st1, så det skulle stå åpent middlertidlig, men vi kan skru av begge registrering-begrep og registrering-begrp.api i begge it og prod

**Comment by stigbd** [comment]
Viss vi skru de av, vil ingen nå disse. Det vil vi ikkje. Disse tjenestene skal kunne brukes.

**Comment by bgrova** [comment]
For ut1 og st1 miljøene tror jeg vi kunne løst det ved å legge på basic auth i fellesnginx, men denne finnes ikke for it1 og prod.

Som Markko skriver, så kan vi slå av ingress i it1 og prod, men da vil jo ingen ha tilgang til tjenestene. Hvis _noen_ brukere skal ha tilgang, vil jo ikke dette løse problemet.

**Comment by stigbd** [comment]
Oppklaring etter å ha snakka saman: Ingen skal ha tilgang. Då kan vi skru av ingress på disse tjenestene slik Marko seier. (Men det har ingenting med "Midlertidig adgangskontroll til Begrepsregistrering" å gjere, som denne oppgåva skulle løyse.)

**Comment by markkopaas** [comment]
Så midlertidlig løsning er, at vi skal ikke deploye begrepsløsning før det er ferdig. Jeg bare snakker om at vi vil deploy fdk repo, og den har bare lenker i registrering-ui som må fjernes.

Så apiene skal ble beskyttet på den måte at de er bare ikke deployet
