### ISSUE TITLE
Oppsett av infrastruktur for Begrepsregistrering og Keycloak

### ISSUE THREAD

**Issue by bgrova** [Altinn/fdk#2109]
Helm templates og konfig i Jenkis for proxy-komponenter
- [x]  Altinn proxy
- [x] Enhetsregisteret proxy

Helm templates og konfig i Jenkis for mock-komponenter
- [x]  Altinn proxy mock
- [x] Enhetsregistert proxy mock
- [x] idporten mock (nå en del av komponent sso)

Annet
-  [x] Helm template og konfig for user api
- [x] Oppsett av secrets for Altinn-konfigurasjon i dev- og prod-cluster

**Comment by sindresandvik2** [comment]
Testet i både IT1 og prod.  Alt er klart for prodsetting
