### ISSUE TITLE
Felt mangler i Collections 

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2111]
Når et begrep fra registreingsløsningen blir publisert dukker det pent opp i Collections. Her er et eksemple for begrepet "hekTESTropp": 

<https://registrering-begrep.ut1.fellesdatakatalog.brreg.no/910244132/ea58c7ae-abd3-4537-9f9f-ac18b93eb989>
        a                             skos:Concept ;
        skosno:betydningsbeskrivelse  [ a               skosno:Definisjon ;
                                        rdfs:label      "Type stopp som brukes ved testing av systemer som henger seg opp. "@nb ;
                                        dct:audience    "allmenheten"@nb ;
                                        dct:modified    ""^^xsd:date ;
                                        dct:source      [ rdfs:label    ""@nb ;
                                                          rdfs:seeAlso  <egendefinert>
                                                        ] ;
                                        skos:scopeNote  "Fra Neste Testinasjon"@nb
                                      ] ;
        dct:identifier                "ea58c7ae-abd3-4537-9f9f-ac18b93eb989" ;
        dct:publisher                 <https://data.brreg.no/enhetsregisteret/api/enheter/910244132> ;
        skosxl:prefLabel              [ a                   skosxl:Label ;
                                        skosxl:literalForm  "hekTESTropp"@no

**MEN.** Følgende felt har data som er lagt inn i registreringsløsningen  mangler: 
Eksempel 
Fagområde
Bruksområde
Tittel omfang, lenke omfang
Kontaktinfomrasjon epost, tlf

![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/dd6846a5-692c-42dd-a80f-c02f8d84022a)

**Comment by thomasnokleby** [comment]
Jeg har gjort en kort inspeksjon av koden, og tipper på at frontend her ikke sender inn de relevante data. Alle de overnenvte feltene er kjent og skal lagres.

**Comment by stigbd** [comment]
Front-end sender inn verdier og back-end lagrer. Men her er det nok back-end som feiler _i oppbygging av skos-ap-no endepunktet_. HarvestEndpoint.kt  eksponerer ikkje disse felta. Det kan vere fordi versjonen av concept-builder biblioteket er feil. Det er difi sin versjon av concept-builder som gjelder:
https://github.com/difi/skos-ap-no-tools/tree/master/concept-builder

**Comment by stigbd** [comment]
Status-oppdatering: Nesten alle felt er no med. Unntak:
- omfang mangler i skos-ap-no endepunkt  #2117
- bruksområde er i skos-ap-no, men mangler ut av concept-cat. #2118
- contactPoint.email: tryner ved rare tegn. Denne er adresseret i #2116

**Comment by sindresandvik2** [comment]
Lukker denne. Feil følges opp i tre andre feiolmeldinger
