### ISSUE TITLE
Begrepsregistrering: Omfang mangler i skos-ap-no endepunkt

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2117]
omfang mangler i skos-ap-no endepunkt

Blir lagret i registreringsløsninga og feltene er klargjort io Frontend

**Comment by stigbd** [comment]
Blir løst i https://github.com/difi/skos-ap-no-tools/issues/6

**Comment by stigbd** [comment]
Når difi-biblioteket støtter omfang, må vi 
-  støtte publisering av omfang i concept-catalogue:(no.begrepskatalog.conceptregistration.HarvestEndpoint)
- støtte høsting av omfang via fdk-concept-cats SKOS-AP-NO endepunkt. (I no.ccat.service.RDFToModelTransformer )
