### ISSUE TITLE
Registering begrep: Bruksområde er i skos-ap-no, men mangler ut av concept-cat.

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2118]
Bruksområde er i skos-ap-no, men mangler ut av concept-cat.

Bruksområde blir lagret i registreringsløsninga og felt er klargjort i frontend, men innholdet vises ikke i frontend

**Comment by thomasnokleby** [comment]
Sindre har bekreftet at feltet er med og fylt ut når det blir høstet fra concept-catalogue. Så da gjenstår en sjekkejobb for å se om det er innlesingen som snubler, eller om bruksområde som eget felt faktisk mangler (se https://fellesdatakatalog.brreg.no/concepts/3c32dbaa-d530-4c9f-8862-8ac0c3535d87 for å se at GUI snakker om fag og bruksområde, og at fagområde finnes.

**Comment by thomasnokleby** [comment]
Ser at dette feltet ikke er implementert i backend.

**Comment by sindresandvik2** [comment]
OBs:  Lagring av felt feilet: 
Kunne ikke lagre endring - Error: Fetch error: 400

**Comment by sindresandvik2** [comment]
Bruksområde  er nå med i Concept api-et .  Vises ikke i søkeprotalen  (Registrert som egen feil. )  Retestet ok i UT1
