### ISSUE TITLE
Implementere publiseringsbar del 2

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2121]
Oppfølger etter  #2026 

mangler tekst for "... lagret for noen sekunder siden", foreløpig gis ingen info om når begrepet sist ble lagret.

**Comment by oyvindis** [comment]
'endringstidspunkt' endres ikke ved patch, har foreløpig ikke noe dato-objekt å vise. Dato-objektet må ha med time-minutt-sekund.

![image](https://user-images.githubusercontent.com/6214701/63750624-17c28700-c8ae-11e9-9d82-110ba10708c0.png)
