### ISSUE TITLE
Støtte Omfang i SKOS-ap-no endepunktet og høste det i fdk concept-cat

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2141]
Når difi-biblioteket støtter omfang, må vi
- [x] støtte publisering av omfang i concept-catalogue:(no.begrepskatalog.conceptregistration.HarvestEndpoint)
- [ ] støtte høsting av omfang via fdk-concept-cats SKOS-AP-NO endepunkt. (I no.ccat.service.RDFToModelTransformer )

**Comment by sindresandvik2** [comment]
Data vises ok i UT1 (range)  Ok utg for FrontEnd.    
Testes utførlig når frontend er ferdig
