### ISSUE TITLE
Logikk for å håndtere visning av transport-data

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2146]
- [x] Her skal utdraget av datasett være: "Trafikk, reiser og samferdsel" && tilgang = Public (3d)

- [x] Se på mulighet for at  "default-filteret" ved startsiden ikke skal påvirke URL... Altså at URL IKKE(!) skal se slik ut ved inngang til siden: "https://nap.fellesdatakatalog.brreg.no/?losTheme=trafikk-reiser-og-samferdsel&accessrights=PUBLIC"

Akseptansekriterie: Dette filteret skal også være på ved søk etter datasett

**Comment by sindresandvik2** [comment]
OK utvalg.  En feil rapportert for feil med filter.  se #2305
