### ISSUE TITLE
Blåfarge på tittel og linker er feil i ut1, men korrekt i prod

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2154]
- [ ] Blåfarge på tittel og linker er feil i ut1, men korrekt i prod

- [ ] Feil oransj-farge ved "Begrenset offentlighet" sammendragboks og detaljside

Lenker 
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/8d7aa771-b001-4d06-b447-5d7091db489f)

Tittel:
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/6be20f25-3927-40ff-bb66-fd9a9b861072)

![image](https://user-images.githubusercontent.com/39513382/63408979-860bd300-c3f0-11e9-8bd0-d724175c52e6.png)

**Comment by sindresandvik2** [comment]
Retestet Ok i UT1
