### ISSUE TITLE
Disqus er borte!

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2155]
Feil funne i prod.    Nå dukker ikke Disqus opp i API-fanen!

**Comment by bgrova** [comment]
DISQUS_SHORTNAME har riktig verdi: felles-datakatalog
og blir med ut i deploy til search.
Jeg ser at den er med i env.json
@oyvindis er dette noe du kan se nærmere på? Virker som det er noe i frontend som ikke oppfører seg som før.

**Comment by oyvindis** [comment]
Jeg sjekker

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
