### ISSUE TITLE
Bruksområde - Lagringsfeil

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2156]
Bruksområde er nå endret fra en streng til array.  Må tilpasses i Frontend.  Nå får vi lagringsfeil . 

Sjekk at det er mulig å legge inn FLERE bruksområder

**Comment by sindresandvik2** [comment]
Retestet OK i UIT1.  LAgring er OK, (men publisering er ikke på plass)

**Comment by stigbd** [comment]
Publisering av _bruksområde_ blir fiksa i #2118

**Comment by sindresandvik2** [comment]
Reåpner feilen. 
Nå lagrer ikke Tillatt term, frarådet term og Bruksområde   (bruksområde lagrer rettnok ved 2. gangsforsøk......)

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
