### ISSUE TITLE
Begrepsregistreringslista dukker ikke opp for nytt firma

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2161]
Gjelder i UT1, for selskapet "Liland"   Logget på som Stein Eidem  (SE) 

Årsaksteori:
På endepunktet i concept-catalogue (GET Begrep <orgnummer>) så har det til nå vært en feil å spørre etter begrep for ikkeeksisterende firma. dette må løses opp til å bare gi en tom liste om firma ikke eksisterer

**Comment by sindresandvik2** [comment]
Fortsatt feil . Her er forsøk på å gi detaljinfo: 
![image](https://user-images.githubusercontent.com/42966644/63434467-735fc100-c425-11e9-84dc-16211db01465.png)

https://www.ut1.fellesdatakatalog.brreg.no/publishers/910258028

**Comment by thomasnokleby** [comment]
Dette er den kjente problematikken med at om det ikke finnes NOEN datasett med dette firmaet, så finnes det ikke et innslag i publishers, og da feiler vi

**Comment by sindresandvik2** [comment]
FIkset ved å oprette et datasett!
