### ISSUE TITLE
Endre tekst for forside på registreringsløsning

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2166]
For øyeblikket får bruker bare beskjed om at datasett og API'er kan registreres. Etter Begrepsregistrering er på plass må vi endre teksten til å inkludere dette.

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/d5bff80b-e547-4d56-ab28-37213fd878ed)

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
