### ISSUE TITLE
Vi trenger et eget endepunkt for liveness-probe i concept-catalogue backend

### ISSUE THREAD

**Issue by thomasnokleby** [Altinn/fdk#2168]
Dette fordi at den nåværende probe går mot et eksisterende endepunkt som lager masse unødvendige logglinjer

**Comment by stigbd** [comment]
Det som er nermest en standard, er måten Frode har løst det på i begrepspubliserer (brreg), og som Nils Ove har kopiert i publisher. Sjekk no.publishers.controller.PublishersApiImpl (26-32):
```
  @RequestMapping(value = ["/ping"], method = [GET], produces = ["text/plain"])
    fun ping(): ResponseEntity<String> =
        ResponseEntity.ok("pong")

    @RequestMapping(value = ["/ready"], method = [GET])
    fun ready(): ResponseEntity<Void> =
        ResponseEntity.ok().build()
```
Eg anbefaler at vi løyser det på denne måten.

PS! Dette skal ikkje inn i openAPI-spesifikasjonen.

**Comment by markkopaas** [comment]
den liveness/readiness som Spring tilbyr funker også ganske bra. Det er implementert i api-cat og reference-data

**Comment by stigbd** [comment]
Developers handbook har utkast til retningslinjer på dette her:
https://informasjonsforvaltning.github.io/developers_handbook/monitoring/probes/

**Comment by bgrova** [comment]
Helm template er oppdatert med nye readyness og liveness probe-endepunkter
Deployet til UT1 og det fungerer som det skal.

**Comment by sindresandvik2** [comment]
Lukkes etter solid testarbeid av @bgrova
