### ISSUE TITLE
Default forholdtilkilde er egendefinert og ikke null

### ISSUE THREAD

**Issue by skobba** [Altinn/fdk#2169]
# Default forholdtilkilde er egendefinert og ikke null
## 1) Kjøre POST
curl -X POST \
 http://localhost:8100/begreper/ \
 -H 'cache-control: no-cache' \
 -H 'content-type: application/json' \
 -d ' {
        "anbefaltTerm": "kildeBeskrivelse-test01",
        "status": "utkast",
        "ansvarligVirksomhet": {
           "id": "986105174"
       }
}' -v

## 2) Motatt ID 
ec1ca888-4a36-46fb-8edd-7a963daae68e

## 3) Kjør GET (og observer default verdi for forholdTilKilde)
curl 'http://localhost:8100/begreper/ec1ca888-4a36-46fb-8edd-7a963daae68e' | jq

{
  "id": "ec1ca888-4a36-46fb-8edd-7a963daae68e",
  "status": "utkast",
  "anbefaltTerm": "kildeBeskrivelse-test01",
  "definisjon": null,
  "kildebeskrivelse": {
    "forholdTilKilde": "egendefinert",
    "kilde": []
  },
  "merknad": null,
  "ansvarligVirksomhet": {
    "uri": null,
    "id": "986105174",
    "navn": null,
    "orgPath": null,
    "prefLabel": null
  },
  "eksempel": null,
  "fagområde": null,

**Comment by thomasnokleby** [comment]
Backend fix er i PR

**Comment by sindresandvik2** [comment]
Denne blir testet når Front end er endret.

**Comment by thomasnokleby** [comment]
Etter litt fram og tilbake ser konklusjonen ut til å være at Frontend må håndtere at Enumen kildebeskrivelse ikke skal kunne være null.

**Comment by skobba** [comment]
Etter avtale med @stigbd skal kildebeskrivelse kunne være null. curl eksempel på at kildebeskrivelse ikke blir satt til null.

![image](https://user-images.githubusercontent.com/16732769/63747812-489fbd80-c8a8-11e9-9960-b91968ed7fc8.png)

**Comment by sindresandvik2** [comment]
Blir fulgt opp med #2219
