### ISSUE TITLE
Datasett sammendrag OG detaljside - Kosmetikk ved "Begrenset offentlighet"

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2178]
- [ ] Feil farge på tekst "Datasettet har begrenset offentlighet". Skal være lik ikonfargen. Ser ut for meg som at fargekoden er satt til: #805F1E. Riktig fargekode skal være: #885B00 (på både ikon og tekst).

- [ ] Padding/Margin - Begrenset offentlighet DETALJSIDE- skal være midtstilt opp og ned i forhold til ikonet. 

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/a3e5b0d2-684b-4d09-90d9-f3effce11ce2)

**Comment by oyvindis** [comment]
1) Ikke rettet, finner ikke fargen #885B00 i fargeskjemaet. Beholder fargen som er color-warning-darker: #805F1E
2) Midtstiller tekst vertikalt.

**Comment by sindresandvik2** [comment]
Punkt 2 OK

**Comment by lillelars** [comment]
1) Ikke rettet, finner ikke fargen #885B00 i fargeskjemaet. Beholder fargen som er color-warning-darker: #805F1E

Fra Lene:
Fargen heter warning-darker, og ligger i InVision ser jeg: https://invis.io/B3T9BKV7KW6#/380979982_DESIGNSYSTEM-Fdk

**Comment by sindresandvik2** [comment]
ok i følge Lene
