### ISSUE TITLE
Feltet "Bruksområde" mangler i Søkeportalen

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2179]
Det er nå mulig å registrere Bruksområde i registreringsløsningen for begrep.  Men verdien har ingen felt i søkeportalen der det kan vises.   I concept-cat benevnes dette feltet som "Application" (intet mindre)

![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/e5908a07-7c78-4cdf-96d7-c650bebef8d2)

**Comment by oyvindis** [comment]
Foreløpig feiler begrepshøsting i lokalt utv-miljø, jeg får ikke gjenskapt feil. Avventer feilretting.

**Comment by oyvindis** [comment]
Feilsøk i ut1, https://www.ut1.fellesdatakatalog.brreg.no/api/concepts/41091a49-d1a3-4d55-9b15-30f38385a052

Backend issue:
'applications' skal returnere en array i hht. spec, men returnerer object.

**Comment by stigbd** [comment]
Her er det nok to feil i back-end:
1. back-end returnerer objekt, ikkje array, og
2. back-end returnerer kun en forekomst av 'appliation', der det faktisk er fleire.
Oppretter nytt issue som tracker dette, ref #2197

**Comment by sindresandvik2** [comment]
Retestet ok i UT1
