### ISSUE TITLE
Fjerne hele docker-compose ut fra fdk

### ISSUE THREAD

**Issue by stigbd** [Altinn/fdk#2211]
Det er ikke lenger "hoved" repo, og er ikke brukbar selvstendig igjen.

**Comment by markkopaas** [comment]
på den måte som fdk-docker-compose funker nå, mener vi at hver repo skulle inneholde bare sitt "del av docker-compose". fdk-docker-compose konkatenerer de delene.

nå er api-cat ut, så api-cat del av docker-compose skulle ut
