### ISSUE TITLE
Tomme begrep skal ikke lagres

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2216]
I registreringsløsningen blir nå et begrep lagret helt tomt i det en oppretter begrepet.  
Begrepet skal IKkE lagres tomt.  Det vil sei at autolagring ikke skal starte før noe er editert i et av feltene.

**Comment by oyvindis** [comment]
Det stemmer ikke helt med spec-en for begrep. Ved opprettelse av begrep så skal id genereres i backend, da må begrepet nødvendigvis også lagres tomt.

Da må vi evt. generere en id i frontend, vi bruker id-en som en unik identifikator for å navigere til registreringssiden for det aktuelle begrepet. Det blir endringer i logikk på frontend for å gjøre dette, og forutsetter at endringslogg også fungerer på begrep (backend).

**Comment by stigbd** [comment]
Alternativt bør front-end vente med å opprette begrep til det er lagt inn ein (ikkje-tom) verdi i "opprettelses"-skjemaet. Front-end vil då få id tilbake i Location-header ved post av ikkje-tomt begrep.

**Comment by lillelars** [comment]
@stigbd Før vi gjør noe på denne trenger vi noe mer input hvordan dette bør løses.

**Comment by lillelars** [comment]
må sees i sammenheng med autolagring og knapper generelt
