### ISSUE TITLE
Db-opprydding

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2227]
I UT1 må en slette begrep som nå vises i Søkeportalen men som ikke finnes i Registreringsløysingen.    totalt 6 stk. To begrep har ikke navn (Anbefalt term = NULL) 
Her er de 4 andre: 
https://www.ut1.fellesdatakatalog.brreg.no/concepts/995c9d91-6a61-4109-a57a-7ef8b002c982
https://www.ut1.fellesdatakatalog.brreg.no/concepts/b6fb24d3-4f28-4d40-9ed9-f7d14f49cb1a
https://www.ut1.fellesdatakatalog.brreg.no/concepts/2e0992d0-9215-460a-94c4-a033d06f7d18
https://www.ut1.fellesdatakatalog.brreg.no/concepts/503948b2-8694-4c3b-99db-7ca5a793f3f2

**Comment by thomasnokleby** [comment]
Done

**Comment by sindresandvik2** [comment]
Dei to uten namn  (Anbefalt term = NULL)  er der fortsatt!

**Comment by thomasnokleby** [comment]
Hvordan finner jeg disse to begrepene ?

**Comment by sindresandvik2** [comment]
I UT finnes det to begrep som ikke har tittel.   Du ser det dersom du filtrerer på Ramsund

**Comment by thomasnokleby** [comment]
Da er de slettet

**Comment by sindresandvik2** [comment]
:-)
