### ISSUE TITLE
Splitte db for UT1 og ST1

### ISSUE THREAD

**Issue by thomasnokleby** [Altinn/fdk#2229]
1)  Nå bruker både UT1 og ST1 samme PostgresDB.
2) Databasen som nå brukes til begge skal leve videre som UT1 Database
3) Ny tom db skal bli autogeneret i ST1 (etter konfigendring).

**Comment by thomasnokleby** [comment]
Det ser i utgangspunktet ut som URL for sql-base er korrekt både i UT1 og ST1. Så enten er syntaxen feil, eller det er noe ekstra oppsett i proxyene. Det er en proxy i hvert miljø (podnavn postgresql-sqlproxy ). 
Utdrag fra loggen i proxyen i UT1:
2019/09/06 12:07:47 Client closed local connection on 10.84.6.41:5432
2019/09/06 12:07:47 New connection for "fdk-dev:europe-north1:fdk-sql-test"
2019/09/06 12:07:47 Client closed local connection on 10.84.6.41:5432
2019/09/06 12:07:47 New connection for "fdk-dev:europe-north1:fdk-sql-test"
2019/09/06 12:07:47 Client closed local connection on 10.84.6.41:5432
2019/09/06 12:07:47 Client closed local connection on 10.84.6.41:5432

2019/09/06 12:13:58 Client closed local connection on 10.84.8.33:5432
2019/09/06 12:13:58 New connection for "fdk-dev:europe-north1:fdk-sql-test"
2019/09/06 12:13:58 Client closed local connection on 10.84.8.33:5432
2019/09/06 12:13:58 New connection for "fdk-dev:europe-north1:fdk-sql-test"
2019/09/06 12:13:58 Client closed local connection on 10.84.8.33:5432
2019/09/06 12:13:58 New connection for "fdk-dev:europe-north1:fdk-sql-test"
2019/09/06 12:13:58 Client closed local connection on 10.84.8.33:5432
2019/09/06 12:13:58 Client closed local connection on 10.84.8.33:5432

**Comment by sindresandvik2** [comment]
Nå er UT og ST1 lik for alle tre registreringsløsningene
