### ISSUE TITLE
Tellefeil i endpoints

### ISSUE THREAD

**Issue by sskagemo** [Altinn/fdk#2236]
Nav har påpekt at det er mismatch mellom det som oppgis som antall returnerte endpoints. Ved et kall står det "total": 16 mens en opptelling viser at det kun er 15.

Stig har eksempelet (epost idag) og har gjenskapt feilen i it1, men ikke klart å gjenskape den i demo eller prod.

**Comment by sindresandvik2** [comment]
@sskagemo   Kva for eit kall er det snakk om ?  Har du eksempel?
@stigbd   Kan du videresende mail?

**Comment by sskagemo** [comment]
Kallet:

https://www.it1.fellesdatakatalog.brreg.no/api/apis/endpoints?serviceType=Kontoopplysninger&environment=production

Responsen:

{
    "endpoints": [
        {
            "apiRef": "https://fellesdatakatalog.brreg.no/apis/0fd91bca-a264-40c3-adfc-769b36b9ceef",
            "orgNo": "937888104",
            "serviceType": "Kontoopplysninger",
            "url": "https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/937888104",
            "transportProfile": "eOppslag",
            "environment": "production"
        },
        {
            "apiRef": "https://fellesdatakatalog.brreg.no/apis/26d25a24-7bd8-42c0-9fbe-760ae86be3c1",
            "orgNo": "937889275",
            "serviceType": "Kontoopplysninger",
            "url": "https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/937889275",
            "transportProfile": "eOppslag",
            "environment": "production"
        },
        {
            "apiRef": "https://fellesdatakatalog.brreg.no/apis/84b9680f-3435-46ea-9b0f-51e3a8db9014",
            "orgNo": "937891334",
            "serviceType": "Kontoopplysninger",
            "url": "https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/937891334",
            "transportProfile": "eOppslag",
            "environment": "production"
        },
        {
            "apiRef": "https://fellesdatakatalog.brreg.no/apis/eaec0b2f-a178-43b6-9e00-285abfbefd30",
            "orgNo": "937895321",
            "serviceType": "Kontoopplysninger",
            "url": "https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/937895321",
            "transportProfile": "eOppslag",
            "environment": "production"
        },
        {
            "apiRef": "https://fellesdatakatalog.brreg.no/apis/a5b7906e-ee59-457e-8eac-1fcb85ec9000",
            "orgNo": "937899785",
            "serviceType": "Kontoopplysninger",
            "url": "https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/937899785",
            "transportProfile": "eOppslag",
            "environment": "production"
        },
        {
            "apiRef": "https://fellesdatakatalog.brreg.no/apis/18c6dce3-1ec5-4b3d-a837-ce73e0118010",
            "orgNo": "944521836",
            "serviceType": "Kontoopplysninger",
            "url": "https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/944521836",
            "transportProfile": "eOppslag",
            "environment": "production"
        },
        {
            "apiRef": "https://fellesdatakatalog.brreg.no/apis/59554c81-4b57-45e6-9d0e-434e342c46a0",
            "orgNo": "920426530",
            "serviceType": "Kontoopplysninger",
            "url": "https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/920426530",
            "transportProfile": "eOppslag",
            "environment": "production"
        },
        {
            "apiRef": "https://fellesdatakatalog.brreg.no/apis/127ea784-b25e-400c-9b5a-6edac205050d",
            "orgNo": "937889631",
            "serviceType": "Kontoopplysninger",
            "url": "https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/937889631",
            "transportProfile": "eOppslag",
            "environment": "production"
        },
        {
            "apiRef": "https://fellesdatakatalog.brreg.no/apis/262b81de-b4d9-4c3f-bba4-0c32f308721b",
            "orgNo": "937888015",
            "serviceType": "Kontoopplysninger",
            "url": "https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/937888015",
            "transportProfile": "eOppslag",
            "environment": "production"
        },
        {
            "apiRef": "https://fellesdatakatalog.brreg.no/apis/bc2a0f38-b7b3-46a6-b96e-a15a18237698",
            "orgNo": "952706365",
            "serviceType": "Kontoopplysninger",
            "url": "https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/952706365",
            "transportProfile": "eOppslag",
            "environment": "production"
        },
        {
            "apiRef": "https://fellesdatakatalog.brreg.no/apis/6d5427c0-d409-4c34-84f9-9c8cee8caa1c",
            "orgNo": "937899408",
            "serviceType": "Kontoopplysninger",
            "url": "https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/937899408",
            "transportProfile": "eOppslag",
            "environment": "production"
        },
        {
            "apiRef": "https://fellesdatakatalog.brreg.no/apis/9d869626-d28c-49e6-8547-69c75f452d1a",
            "orgNo": "937901003",
            "serviceType": "Kontoopplysninger",
            "url": "https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/937901003",
            "transportProfile": "eOppslag",
            "environment": "production"
        },
        {
            "apiRef": "https://fellesdatakatalog.brreg.no/apis/f894665c-6315-4985-806e-8d81492f64e4",
            "orgNo": "984851006",
            "serviceType": "Kontoopplysninger",
            "url": "https://publicsector.dnb.no/v1",
            "transportProfile": "eOppslag",
            "environment": "production"
        },
        {
            "apiRef": "https://fellesdatakatalog.brreg.no/apis/2450d4a3-f769-4f59-865c-e70afecafefd",
            "orgNo": "937889186",
            "serviceType": "Kontoopplysninger",
            "url": "https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/937889186",
            "transportProfile": "eOppslag",
            "environment": "production"
        },
        {
            "apiRef": "https://fellesdatakatalog.brreg.no/apis/58b009b4-8c0c-4e4f-8be8-2296629ac6b8",
            "orgNo": "837884942",
            "serviceType": "Kontoopplysninger",
            "url": "https://api.sparebank1.no/dsopaccountcontrolinfo/v2/AccountControlInfoService/v2/837884942",
            "transportProfile": "eOppslag",
            "environment": "production"
        }
    ],
    "total": 16
}

**Comment by stigbd** [comment]
Duplicate of https://github.com/Informasjonsforvaltning/fdk-api-harvester/issues/9
