### ISSUE TITLE
Frontend: Implementer mulighet til å ta i bruk input for multiple språkfelt

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2241]
- [x] Erstatte basic tekstfelt med et felt som støtter input for flere språk

- [x] Koble logikken slik at språkvelger og inputfelt henger sammen 

Husk å skrive tester her og ;)

**Comment by sindresandvik2** [comment]
Testet. Noen bugs er rapportert.  Følges opp separat og ny slutttest vil bli kjørt når alle bugs er retta for storien
