### ISSUE TITLE
"Liland" harvest fungerer ikke i UT1

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2245]
Når en hsøter nye publiserte begrep fra virksomheten Liland dukker disse IKKE opp i søkeportalen.  Publiserte begrep fra Ramsund er OK

**Comment by stigbd** [comment]
Kan vere at høsting ikkje skjer for denne virksomheten. Sjekk values i jenkins

**Comment by markkopaas** [comment]
@stigbd kommentar var korrekt. vi har konfiguret høstinglist i jenkins
