### ISSUE TITLE
Utviklermiljø til registreringsløsning på host (fix cors i nginx conf)

### ISSUE THREAD

**Issue by markkopaas** [Altinn/fdk#2247]
estimat 1d

Probleme er at nginx routing logikk lar ikke gjennom cors spørringene.

verdi: det tar mye pc-kraft og mental kraft å få hele system kjørende på utviklersmiljø.
onboarding av frontend-utviklere blir enklere,

**Comment by sindresandvik2** [comment]
Regresjonstestet OK  https://jira.brreg.no/secure/XrayExecuteTest!default.jspa?testExecIssueKey=API-992&testIssueKey=API-991
 Feil som ble oppdaget har ingenting direkte med denne oppgaven å gjøre
