### ISSUE TITLE
Jenkins status synkronisering til github - concept-cat-gui

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2249]
Problemet er at vi har hatt et par situasjon, når test feiler i jenkins, men det vises ikke i PR på github. Så feilende bransj blir merget i hovedbransj og det mener at alle kommende bygge skal også feile.

**Comment by markkopaas** [comment]
hindring, trenger github repo admin tilgang, til å:
1) disable github hook til pull_request i de separarerte repoene (api-harvester, concept-catalogue, concept-catalogue-gui
2) sjekke at github bruker har ok access til å poste status melding.

**Comment by lillelars** [comment]
@bgrova  husk å dokumentere dette i confluence også
