### ISSUE TITLE
Feil i valideringsmeldinger

### ISSUE THREAD

**Issue by joachim-me** [Altinn/fdk#2255]
- [x] Grisete feilmelding for definisjon:

![image.png](https://images.zenhubusercontent.com/5c6e939eab9efc3c63334546/b830fc01-cd8e-47ba-afce-135aa98b3287)
Det skal være slik som anbefalt term: Feltet er obligatorisk.

- [ ] Det skal ikke dukke opp feilmeldinger når du går inn og ut av valgfrie felt. Feilen gjelder følgende felt: Tittel på kilde, Eksempel, Fagområde

**Comment by sindresandvik2** [comment]
Kun første punkt er fikset.  Punkt to gjenstår!

**Comment by skobba** [comment]
Her smeller det hvis Anbefalt term slettes:
https://registrering-begrep.ut1.fellesdatakatalog.brreg.no/910244132/3357748e-7884-4b4d-9368-be085fcaf33f

![image](https://user-images.githubusercontent.com/16732769/64944595-00543980-d86f-11e9-852a-d5a6eb7d1225.png)

**Comment by sindresandvik2** [comment]
Nå er feil i feltet Definisjon dukket opp igjen.   Tittel på kilde, Eksempel, Fagområde er nå OK

**Comment by sindresandvik2** [comment]
HURRA.  OK i UT1
