### ISSUE TITLE
Undersøk (og fiks) om geonorge sine lisenser blir lest korrekt

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2263]
Påstand: 
Vi tror at tallene vi får på rapportsiden av "Åpne data" er altfor lave. Vi tror dette er fordi vi ikke klarer å lese geonorge sine lisenser korrekt. Stemmer dette? I så fall hva kan vi gjøre her?

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/2fd10276-b29d-489f-99b1-e1dff7294f4b)

**Comment by thomasnokleby** [comment]
Har verifisert via postman at datanorge (https://api.geonorge.no/metadata/dcat) Har 507 datasett. Disse datasettene ser ut til å ha til sammen 2252 distribusjoner.  Filen  open-licenses-skos.rdf inneholder listen over de lisenser som systemet anser som åpne.

**Comment by thomasnokleby** [comment]
Det ser ut som lisensen i filen open-licenses bruker lisensen "http://data.norge.no/nlod/" mens datanorge nå bruker lisensen "http://data.norge.no/nlod/no/1.0" Det finnes 723 distribusjoner i data-dumpen fra data-norge med denne lisensen. Det er en stor jobb å finne ut hvor mange datasett disse distribusjonene faktisk dekker, så jeg tenker vi rett og slett legger til denne lisensen til listen.

**Comment by thomasnokleby** [comment]
La til ny lisens, og kjører pr

**Comment by lillelars** [comment]
Det ser ut til at datasettet "Naturtyper - marine" skal ha den lisensen du snakker om. Denne blir likevel ikke vist i søkeløsning med åpen lisens. 
Har du lagt denne til i selve høstelogikken vår?
Se bildet under: 
![image](https://user-images.githubusercontent.com/39513382/64841294-e6acbb00-d5fe-11e9-9100-fec8345f7116.png)

Dette er en åpen lisens som vi bør støtte...
Det ser ut til at du har lagt til dette i registreringsløsningen NB! Her er det ikke ønskelig å vise mer enn den første, ettersom den vil ta brukeren til siste versjon av lisensen... Se bilde:
![image](https://user-images.githubusercontent.com/39513382/64842193-ac90e880-d601-11e9-81a6-28b9d6758e67.png)

Helt til slutt er det også en del lisenser fra creativecommon:
![image](https://user-images.githubusercontent.com/39513382/64842311-275a0380-d602-11e9-8a5f-f8a6895a2979.png)

Disse skal også godtas. Selv om det noen steder står med en forlengelse av creativecommon/deed.no skal dette også godtas.
![image](https://user-images.githubusercontent.com/39513382/64842396-6d16cc00-d602-11e9-8004-e975d176c8bd.png)

I hovedsak bør alle lisenser vises i søkeløsningen. Men viktigst i denne tasken er å vise og at rapporter teller opp og karakteriseres som åpne datasett må datasettet ha en av disse tre ulike lisense: creative common zero (CC0), Creative common navngivelse (CC 4.0-BY) eller Norsk lisens for åpne data (NLOD). Se difi sin veiledning: https://doc.difi.no/data/veileder-apne-data/#_hva_er_%C3%A5pne_lisenser

**Comment by lillelars** [comment]
Setter denne tilbake til arbeid...

**Comment by thomasnokleby** [comment]
Analyse så langt. For datasettet nevnt over (Naturtyper - Marine), ser det ut som koden forventer at dette er et SKOS Concept, mens det ser ut som det vi faktisk oppdager er en generisk ressurs uten spesiell struktur. Graver videre

**Comment by sindresandvik2** [comment]
OK i UT1.  Antall treff hart økt betraktelig og er klart nærmere det vi tror er riktig verdi

**Comment by thomasnokleby** [comment]
Oppsummering: Lisenser i det overnevnte datasettet var lagret på en subtilt annerledes måte enn det vi har møtt på tidligere. La til kode for å tolke lisenser på denne nye måten, en helt additiv endring.
