### ISSUE TITLE
Undersøk (og fiks) hvorfor vi ikke leser geografi fra data.norge sine datasett

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2264]
Dette påvirker filtreringen vår og gir oss dermed mange ukjente datasett.

![image](https://user-images.githubusercontent.com/39513382/64532161-43fbf000-d311-11e9-9ceb-c4931f3903fb.png)

**Comment by thomasnokleby** [comment]
Dette er mer en missing feature enn en bug. 
Problemet her er at i noen datasett så er Geografi definert som en url som peker på et navngitt område (F.eks norge : http://sws.geonames.org/3144096/ ) og dette blir håndtert. Men når for eksempel datasettene til Data Norge bruker et koordinatsystem, så har vi, såvidt jeg kan se, ikke støtte for dette.
Det er en litt større jobb å mappe dette koordinatsystemet over til stedsnavn, som bør grundig analyseres først. Om man bare er interessert i å få ned antallet ukjente (og f.eks avgjøre om det er i Norge eller Utlandet) så snakker vi om et par få dager med utvkling. 
Eksempel dct:spatial (som da er geografi-taggen) :
<dct:spatial parseType="Resource">
            <locn:geometry datatype="http://www.opengis.net/ont/geosparql#gmlLiteral">
                <![CDATA[<gml:Envelope srsName="http://www.opengis.net/def/crs/OGC/1.3/CRS84"><gml:lowerCorner>4,5 57,7187</gml:lowerCorner><gml:upperCorner>32,7990 70,9183</gml:upperCorner></gml:Envelope>]]>
            </locn:geometry>
        </dct:spatial>

**Comment by joachim-me** [comment]
@thomasnokleby Enig i at dette er større jobb, og det skal vi heller ikke støtte nå. Vi skal støtte Geonames og AdministrativeEnheter. Ser ut som du ser i geonorge-katalogen og ikke data.norge som oppgaven sier (geografi fra data.norge som bruker administrative enheter fra genorge...).

Se i denne katalogen: https://data.norge.no/api/dcat2/data.jsonld
Hvorfor leser vi ikke dette: dct:spatial                     <http://data.geonorge.no/administrativeEnheter/kommune/id/172874> ;

**Comment by thomasnokleby** [comment]
Etter en gjennomgang, så ser jeg at koden forventer inn en whitelist med lokasjoner. Denne kommer typisk fra codes/location, i Reference-Data.  Når jeg sjekker denne på lokal maskin får jeg ut en og bare en lokasjon, en obskur kommune i ringerike. Jobber videre med å finne ut om det er bare lokalt eller i ut1 også

**Comment by thomasnokleby** [comment]
Oppsummering:
Refrence-data er stedet hvor lokasjonene blir lagret. Disse er lazy, det vil si de blir lagret etterhvert som de blir oppdaget. Jeg har ikke gravd i denne lagringskoden ennå. De blir lagret, ser det ut som, som https://<noe>. Man kan f.eks høste https://data.norge.no/api/dcat2/data.jsonld og da få de fleste lokasjonene som ser ut til å bli brukt.

Etter lokasjonene har blitt lagret, kommer jobben med å tolke datasettene. dct:Spatial er da et av feltene som skal lagres. Det underliggende problemet består av to elementer: At koden p.t bruker uri som oppslag, for å hente ut blant annet preflabel. OG at uri i data norge sine spatial tags bruker HTTP ikke HTTPS. Så da finner ikke oppslaget dem.

**Comment by thomasnokleby** [comment]
Problemet, kokt ned til dets minste bestanddeler er følgende:
Når vi oppdager lokasjoner, så lagrer vi dem.
Vi slår opp lokasjonen, og høster inn litt data (blant annet preflabel).
Når man f.eks slår opp 
http://data.geonorge.no/administrativeEnheter/fylke/id/173157 (observer http)
så er id på denne faktisk https://data.geonorge.no/administrativeEnheter/fylke/id/173157 (observer https) og det er dette vi lagrer. 
Når vi senere oppdager samme id (med http) prøver vi å slå dette opp internt, og feiler, siden det er korrekt lagret med https.
Jeg har kode som på en kjip måte fikser dette, men skal bruke litt tid på å se om vi kan fikse dette på en mer korrekt måte.

**Comment by sindresandvik2** [comment]
Etter Harvest ser det fortsatt ut som at det er over 1200 ukjente i GEOGRAFI

**Comment by thomasnokleby** [comment]
Det ser ut som vi har to forskjellige definisjoner, f.eks http://sws.geonames.org/3144096/ som faktisk blir tolket og ikke regnet som ukjent, og  http://data.geonorge.no/administrativeEnheter/nasjon/id/173163 som i seg selv er gyldig, men blir regnet som ukjent. Graver videre

**Comment by thomasnokleby** [comment]
Filteret som filtrerer spatial propertien går på følgende felt i dokumentene spatial.prefLabel.no.raw. 
Jeg vil tro det bør gjøres arbeid i LoadLocations,addLocationsToThemes (som blir kjørt, såvidt jeg kan se, på datasett for å bygge opp locations-listen) slik at uansett location-tag så blir det enten lastet eller generert en preflabel som da også har en .no.raw

**Comment by thomasnokleby** [comment]
TODO: Grave i koden (CodesService.addLocation) som da lagrer en location, for å se om preflabel faktisk blir lagret til TDB, eller om det er her det feiler.

**Comment by lillelars** [comment]
Dette er nå løst. Woop woop!
