### ISSUE TITLE
Feil i visning av knytting mellom Datasett og API-beskrivelse

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2268]
Når en oppretter en knytting fra Datasett til API-beskrivelse vises ikke knyttingen i Søkeportal API-beskrivelse. I Søkeportalen Datasett vises knyttingen korrekt. 

Fremgangsmåte;
1. Registrer et nytt datasett i registreringsløsningen.
2. Legg til en API-distribusjon
3. Publiser datasettet
4. Gå inn på søkeportalen og så inn på detaljsiden for det nye datasettet
5. Sjekk at den registrerte API-distribusjonen vises
6. Klikk på API-distribusjonen slik at du kommer inn på detaljsiden for API-beskrivelsen.
7. Her dukker feilen opp:  Det er nå IKKE mulig å se knyttingen tilbake til datasett.

For tidligere registrerte data ser det ut som at dette har fungert.
Feilen er gjenskapt i både UT1 og ST1     (UT1 har ny cors i nginx conf)

**Comment by sindresandvik2** [comment]
Fortsatt feil......   SJekk dette datasettet i UT1: 
https://www.ut1.fellesdatakatalog.brreg.no/datasets/418dcca9-db16-427d-bef2-94c7b1fd5778

**Comment by markkopaas** [comment]
Motsatt lookup har aldri ble implementert, så det er ikke en bug men nyt feature

side | dataset->api | api->dataset |
| --- | --- | --- |
| dataset detalje | [x] | [x] |
| api detalje | [ ] | [x] |

**Comment by sindresandvik2** [comment]
TAs i #2321
