### ISSUE TITLE
Kildelenke er feil!

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2276]
Når en klikker på lenken brukt for "Sitat fra kilde" eller "Basert på kilde"   viser det seg at dette er sammensatt av flere URL-er.

Se eksempel: 
https://www.ut1.fellesdatakatalog.brreg.no/www.helsedirektoratet.no

Åpning av lenke bli ikke åpnet i ny fane!

**Comment by azaxarov** [comment]
EDIT:
Det ser ut at back end returnerer lenker uten protokoll. Dvs, selv om jeg skrev lenken med "https://", fikk jeg likevel bare "vg.no" i søkeportalen. Det krever mer graving og mest sansynligvis en ny bug.
__

Undersøkte den og innser at vi må ha strengere validering av URI-er i concept-catalogue-gui.

Det vil si at søkeportalen kan ikke få lenker som ser slikt ut: "vg.no". Det er per definisjon ikke riktig, selv om vi pleier å bruke de slikt.

I tillegg er det feil å anta at lenken skal enten ha "http://", eller "http://www.", eller "https://", eller "https://www." foran.

Det å åpne lenke i ny fanen er fikset.

**Comment by lillelars** [comment]
@azaxarov
"Undersøkte den og innser at vi må ha strengere validering av URI-er i concept-catalogue-gui."
Vi MÅ ingenting ;) Vi bør ha dette - men dette har ikke så høy prioritet og kan forklares som brukerfeil.

Derimot er det ønskelig å ha det. Finnes det en enkel måte å validere URI'er på (som i max 30 min arbeid) i frontend registreringsløsningen til Begreper? (concept-catalouge-gui)? 

Hvis ikke:  Vi dropper validering og sender det brukeren taster inn som URL direkte ut (uavhengig om det er en gyldig URL eller ikke)

**_NB! Feilen her er at nå blir scheme-parten av URL'en fjernet og pathen blir endret til der bruker står. Dette er helt feil ettersom dette skal være en ekstern lenke som kan lenke til hva som helst._**

Se "http://" --> "http**s**..... 
![image](https://user-images.githubusercontent.com/39513382/64676183-4f682c00-d475-11e9-8b9a-6df1a6ac80da.png)

-->

![image](https://user-images.githubusercontent.com/39513382/64676503-049ae400-d476-11e9-9725-d39a44703101.png)

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
