### ISSUE TITLE
Høsting fra begrepspubliserer har stoppet

### ISSUE THREAD

**Issue by marittor** [Altinn/fdk#2292]
BRREG begrepspubliserer har to nye begrep "oppslagstjeneste" og "begrep" som ble godkjent 10.9. Disse ligger ute på endepunktet men er ikke høstet av harvester inn i FDK portal. Det kan se ut som høsting derfra ikke fungerer.

**Comment by stigbd** [comment]
Begge begreper ligger i BR sitt SKOS-AP-NO endepunkt som skal vere høstet. Sjekk
```
curl -i -H "Accept: text/turtle" https://data.brreg.no/begrep/
```
oppslagstjeneste er http://data.brreg.no/begrep/50670
begrep er http://data.brreg.no/begrep/28111

**Comment by sindresandvik2** [comment]
Høsting av begrep kjører fint i UT1 ved hjelp av restart av POD

**Comment by marittor** [comment]
Disse to begrepene er fortsatt ikke høstet. Hva er feilen her?

**Comment by sindresandvik2** [comment]
Det er ikke prodsatt enda!    OK i U1.   Kommer i neste prodsetting som er planlagt i slutten av denne uka

**Comment by marittor** [comment]
OK, trodde dette var fikset helt ut, var derfor jeg stussa på at den var lukket. Da er det bare å lukke igjen så skal ikke jeg blande meg mer 👍

**Comment by stigbd** [comment]
Vi bør ikkje lukke disse før feilen er retta i prod. Drr den er meldt .

**Comment by sindresandvik2** [comment]
Det er i så fall ein ny tradisjon. Forstår poenget ditt @stigbd. Må i så fall innføre ein  eigen prosess for"known bugs"

**Comment by sindresandvik2** [comment]
Nå er det på plass i PROD.
