### ISSUE TITLE
konfigurere ingressruter for NAP

### ISSUE THREAD

**Issue by bgrova** [Altinn/fdk#2300]
Konfigurere ingress for NAP:
nap.ut1.fellesdatakatalog.brreg.no
nap.st1.fellesdatakatalog.brreg.no
nap.it1.fellesdatakatalog.brreg.no
nap.fellesdatakatalog.brreg.no

For prod (nap.fellesdatakatalog.brreg.no) må det bestilles DNS-record.

**Comment by bgrova** [comment]
DNS record for prod bestilt
https://jira.brreg.no/servicedesk/customer/portal/1/SDBR-4692

**Comment by bgrova** [comment]
DNS record er nå på plass

**Comment by bgrova** [comment]
nap.ut1.fellesdatakatalog.brreg.no
nap.st1.fellesdatakatalog.brreg.no
er nå aktive

nap.it1.fellesdatakatalog.brreg.no
nap.fellesdatakatalog.brreg.no
blir aktive ved neste deploy til disse to miljøene

**Comment by sindresandvik2** [comment]
For å få dette opp å kjøre må det Host name legges til i white list!

**Comment by sindresandvik2** [comment]
OK i UT1 og ST1.  NAP og "vanlig" fdk kjører nå parallelt uten local strage setting
