### ISSUE TITLE
Teksten på publiseringsbar må endres ved oppstart registreringsbildet

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2314]
Når bruker åpner et publisert begrep som allerede er lagret dukker meldingen "Endringene er lagret" opp.   Denne må erstattes med Endringen er sist oppdatert tid/dato

**Comment by oyvindis** [comment]
Avklart med Joakim at tekst er:
"Lagret som utkast tirsdag 17. september 2019 kl. 15:59" eller
"Endringer ble oppdatert tirsdag 17. september 2019 kl. 15:59"

**Comment by sindresandvik2** [comment]
retestet OK i UT1
