### ISSUE TITLE
Knappen "Publisering" skal ikke være enablet før alle obligatoriske felt er fylt ut

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2316]
Nå dukker det opp en dårlig feilmelding dersom en publiserer før alle obl. felt er registrert. Dette løses ved at Publiseringsknappen ikke er enablet før det er aktuelt å publisere

**Comment by sindresandvik2** [comment]
2 ting:
a)  For streng validering.  Nå må også KILDE vere med for å kunne publisere.  Kilde er IKKE et obligatorisk felt
b)  Disablet knapp ser ikke ut som at den er disablet!   Er dette sjekket med Lene?

**Comment by oyvindis** [comment]
a) Opprettet egen PR som endrer valideringsregel for kildebeskrivelse til nullable.

b) Disablet knapp styres av global stil for disablet knapp. Skal vi lage en egen sak på dette som vi kan ta med design på tvers av alle løsningene?

**Comment by sindresandvik2** [comment]
OK.   Ang disable knapp så tar eg det med Lene og dersom noko skal endrast så blir det ny sak!

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
