### ISSUE TITLE
Publisere begrepsbeskrivelser med det samme

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2318]
Hentet fra behov:
https://github.com/Informasjonsforvaltning/behov/issues/358

Som: skrivebruker i Felles begrepskatalog
Ønsker jeg å: fjerne unødvendig ventetid på høsting,
Slik at: jeg kan publisere begrepsbeskrivelser umiddelbart

Relatert til epos:

Lenke til design:
Lenke til løsningsarkitektur: https://informasjonsforvaltning.github.io/SA_Informasjonsforvaltning/f4212a30-53d0-4c27-a682-4f88d6c692c8/views/f48b3ecc-ae46-45c0-8e5a-bc73889e185c.html

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

- [x] Testdesign

- [ ] Testgjennomføring 
[2318.xlsx](https://github.com/Informasjonsforvaltning/fdk/files/3782536/2318.xlsx)

**Comment by markkopaas** [comment]
![image](https://user-images.githubusercontent.com/7446932/65156636-b5355480-da2f-11e9-84e7-e08c02c12000.png)

**Comment by Chlenix** [comment]
Lagt til 2 resterende publiseringssteder
