### ISSUE TITLE
Generell informasjon om NAP

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2319]
Hentet fra behov:
https://github.com/Informasjonsforvaltning/behov/issues/288

Vises som hyperlenke-tekst inntil vi får URL.

Se design: https://projects.invisionapp.com/share/PVQIEP15ADG#/screens/369545086

**Comment by oyvindis** [comment]
Avklart med Joakim: 'Registrer datasett' endres til likt som FDK -> 'Registrering'.

**Comment by sindresandvik2** [comment]
Jo da. Lenka er der men ingen ting bak so far....  OK
