### ISSUE TITLE
Vise knytning i API-detaljside for datasett som er koblet til API-distribusjone fra datasett registrering

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2321]
Skal vises i samme seksjon uavhengig hvilken vei kobling er gjort i registreringsløsningen: 
![image](https://user-images.githubusercontent.com/39513382/64962360-8edcb100-d897-11e9-8a9a-112e00f3474e.png)

**Comment by markkopaas** [comment]
i ut1 er det /datasets/418dcca9-db16-427d-bef2-94c7b1fd5778

**Comment by sindresandvik2** [comment]
Retetset OK i UT1.  Relasjoner mellom Datasett og API  vises nå korrekt i Søkeportal  for koplinger gjort begge veier.
