### ISSUE TITLE
Kosmetiske forbedringer

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2322]
Registrering

- [x] Innlogging: Den lyseblå bakgrunnen dekker ikke hele skjermen i høyden.

- [x] Autolagring: Innhold i linjen legger seg helt ut i fullbredde. Skal ha samme innholdsbredde som header.

(Begrep i egen issue)

- [x] Hjelpetekst: Det er for mye luft i bunnen av den grå bokesn med hjelpetekst.

Portal

- [x] Søkefelt: Ledeteksten «Søk etter innhold» er ikke midtstilt vertikalt søkefeltet i (Safari).

**Comment by sindresandvik2** [comment]
1 OK
2  Ingen endring utført 
3   OK for Datakatalog
4 OK i Safari
