### ISSUE TITLE
[concept-cat] Begreps-høsting: legge polititets katalog inn i begreps-høsting

### ISSUE THREAD

**Issue by stigbd** [Altinn/fdk#2329]
Politiets katalog frå vår begreps-registrering må legges inn i høsteløsningen.

Dvs. at følgande url leggast til i uriList i fila application.yml i concept-cat:
https://registrering-begrep-api.fellesdatakatalog.brreg.no/collections?publisher=915429785
Resultatet skal bli slik.
```
  harvestsourcesuris:
    urlOverride : ${CONCEPT_CAT_HARVEST_URL_OVERRIDE:}
    uriList:
      - "https://data.brreg.no/begrep/"
      - "https://data.skatteetaten.no/begreper/"
      - "https://raw.githubusercontent.com/akhvidsten/skosmapping/master/Virksomhetsarkitektur"
      - "https://registrering-begrep-api.fellesdatakatalog.brreg.no/collections?publisher=915429785"
``` 
Dette kan også leggast inn for develop og unit-integration profilen (lenger ned i fila).

**Comment by sindresandvik2** [comment]
OK i PROD!
