### ISSUE TITLE
Bruke samme variablenavn til samme ting i service env vars.

### ISSUE THREAD

**Issue by markkopaas** [Altinn/fdk#2331]

**Comment by markkopaas** [comment]
estimat 2 dager, det er massevis av variabler - selveste komponentene, docker-compose, jenkins, og helm
også er det veldig høy risk i alle miljøene, inkl prod.

**Comment by lillelars** [comment]
@stigbd har laget en naming convention til utviklerhåndboka. Kanskje dette er relevant?

**Comment by lillelars** [comment]
Dette ble håndtert ved overgangen til DIGDIR cloud
