### ISSUE TITLE
forenkle frontend docker container som filserver -  fjerne dev-modus

### ISSUE THREAD

**Issue by markkopaas** [Altinn/fdk#2336]
Bruk multistage build sån at den siste image er nginx-basert.

Verdi kommer fa antall av testbare frontend miljø  og enklere oppsett 
Akkurat nå er det tre - dev-on-host, dev-in-container, og prod i container. dev-in-container er unødvendig.

it tilleg har vi mindre footprint

**Comment by markkopaas** [comment]
Det kan deles til flere steg, eller til oppgaver
 - [x] fjerne dev-modus (#2237 skal få gevinst)
 - [ ] multi-stage build med nginx (concept-cat-gui kan få gzip, siden det har ikke reverse proxy som search og registration-react)

estimat 
1 time til å fjerne dev-modus
1 dag  for multistage dockerfile

**Comment by lillelars** [comment]
Siste del av denne oppgaven: 
" 
- [ ] multi-stage build med nginx (concept-cat-gui kan få gzip, siden det har ikke reverse proxy som search og registration-react)
"
håndteres i #2588

**Comment by lillelars** [comment]
resten av denne issuen håndteres nå i #2588
