### ISSUE TITLE
Tilleggskrav for utvalg NAP: Må også inkludere alle datasett med EU-tema = Transport

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2338]
I tillegg til LOS-tema = "Trafikk, reiser og samferdsel" skal også alle datasett med EU-tema =Transport komme med i utvalget.

Det betyr i praksis EU-tema = "Trafikk, reiser og samferdsel" OR LOS-Tema = "Transport"

**Comment by skobba** [comment]
Vi må implementere et OR filter i backend.

**Comment by stigbd** [comment]
Vil dette også kunne løysast med å sende to spørringer mot backend, først med los-tema (query-param=lostheme), deretter med eu-tema (query-para=theme)? Dette skulle vere ekvivalent med et OR filter.

**Comment by skobba** [comment]
Det blir i overkant komplisert å aggregere aggregeringen.

**Comment by markkopaas** [comment]
vi diskutert, at vi har ny filter themeProfile='transport'

**Comment by stigbd** [comment]
Vi løser dette ved å innføre "themeprofile" parameter. Denne kan settes til "transport". Da blir NAP som følger (pseudokode):
`?åpnedata=true&themeprofile=transport`
Altså løses det i backend, som dermed krever refaktorering av search-api.

**Comment by sindresandvik2** [comment]
OK utvalg i UT1.
