### ISSUE TITLE
Datasett detaljside: Forslag til å endre teksten i feltet "begrep brukt i datasettet"

### ISSUE THREAD

**Issue by marittor** [Altinn/fdk#2341]
Foreslår å endre følgende felt i portal - datasettbeskrivelse: «begrep brukt i datasettet». Det vi ønsker å si er at opplysningene i datasettet har en definisjon.  Kan feltnavnet i portalen vises som: «datasettet består av følgende definerte opplysninger»

**Comment by LeneSundsbo** [comment]
Etter en kort og lite opphetet diskusjon kan jeg servere deg følgende oppsummering fra nordre fløy:

«Begreper brukt i datasettet» er allerede en lang tittel, som er litt uheldig siden tittelen går igjen i venstremenyen og skiller seg fra de andre menypunktene. «Datasettet består av følgende definerte opplysninger» er enda lengre, og dermed enda mindre heldig. «Brukt i datasettet» / «Datasettet består av» har vi ikke benyttet for noen av de andre titlene/menypunktene, så egentlig ønsker jeg i utgangspunktet å korte ned tittelen til f.eks. bare «Begreper».

Er det ordet _begrep_ som ikke fungerer godt nok? Er det i så fall en løsning å endre (og forkorte) tittelen til «Definisjoner» eller «Definerte opplysninger» i stedet?

**Comment by lillelars** [comment]
@marittor
