### ISSUE TITLE
Datasett detaljside: Vise ansvarlig virksomhet sammen med term og definisjon av refererte begrep

### ISSUE THREAD

**Issue by marittor** [Altinn/fdk#2342]
Som: konsument av datasettbeskrivelse
Ønsker jeg: å se ansvarlig virksomhet for et begrep som er referert til i datasettbeskrivelsen
Slik at: det kommer tydelig fram dersom andre enn eier av datasettet er ansvarlig for tolkningen av begrepet

Eksempel: Datsettbeskrivelsen for Gjeldsregisteret viser til flere begreper fra en annen virksomhet - Skatteetaten - det bør komme fram at dette er nettopp Skatteetatens begreper i detaljevisningen

**Comment by joachim-me** [comment]
@marittor Denne trenger design, og er kanskje for omfattende for å gå utenom behovsprosessen?
