### ISSUE TITLE
Refaktorer fdk-concept-harvester til nytt repo (1)

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2348]
Verifiser at dette fungerer.

PS. Spør Stig om hjelp - han har gjort dette før :D

**Comment by stigbd** [comment]
Da er concept-cat refaktorert til det nye repoet. Vi må vente med å fjerne den fra fdk til frys er over. Då må vi også sette opp webhooks slik at jenkins starter å bygge fra det nye repoet.
https://github.com/Informasjonsforvaltning/fdk-concept-harvester/commit/9c8d9f88a8dc19b2b405c39615efbcfbdcb80138
