### ISSUE TITLE
admin backend komponent - REST CRUD (2)

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2349]
Tabell over whitelisted orgnummer (høsteliste)

- [x] crud
- [x] deploy dockerfiles
- [x] deploy i et miljø
- [ ] auth
- [ ] automatictest

**Comment by stigbd** [comment]
Denne er påbegynt i https://github.com/Informasjonsforvaltning/fdk-harvest-admin/tree/firstversion

**Comment by sindresandvik2** [comment]
Testet i UT1 vha Postmann   POST, GET og PUT med stor suksess
