### ISSUE TITLE
Høste-admin gui: fdk-admin-gui komponent (3)

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2350]
NB! Trenger taskliste her før man begynner på oppgaven  (så man kan se progress)
https://admin.fellesdatakatalog.brreg.no  ?

- [x] Bestille URL for admin-GUI

- [x] konfigurere url  i ingress-ruter for testmiljøer

- [x] multistage Dockerfile med nginx som siste base-image (#2336)

- [x] app shell
- [ ] auth
- [ ] crud

Skal ha disse funksjoner:
https://harvester.ut1.fellesdatakatalog.brreg.no/admin

Start på Design:
https://projects.invisionapp.com/share/SFTW6CSAD94#/screens/382414022_334-02

**Comment by lillelars** [comment]
DNS record er ferdig.

URL skal være: https://admin.fellesdatakatalog.brreg.no

**Comment by bgrova** [comment]
Ingressruter for admin er konfigurert i ut1, st1 og demo miljøene, men er kommentert ut inntil fdk-admin-gui er klar for deploy.
Igressruter i prod konfigureres samtidig som vi setter opp helm-templaten.

**Comment by sindresandvik2** [comment]
GUI testet OK. En liste over utbedringer som kan vere lurt er sattopp i egen issue. #2566
