### ISSUE TITLE
System admin-rolle i keycloak (4)

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2351]
Lenke til løsningsarkitektur: https://informasjonsforvaltning.github.io/SA_Informasjonsforvaltning/f4212a30-53d0-4c27-a682-4f88d6c692c8/views/f48b3ecc-ae46-45c0-8e5a-bc73889e185c.html

**Comment by markkopaas** [comment]
I dev miljøene, Maud Gulliksen er satt opp som admin.

test:
1) logg seg på med Maud Gulliksen (dev, ut1, it1)
2) logg inni sso admin console (sso.xx.fellesdatakatalog.brreg.no/), og sjekke aktive sessioner. Sjekk at bruker har fått en ekstra rolle "admin" (authorities="publisher:910244132:admin,admin")

**Comment by sindresandvik2** [comment]
Testet ok i UT1 i henhold tl MArkkos spesifikasjoner.  Innlogget Maud G. ble vist som admin i consollet!
