### ISSUE TITLE
Sende Trigger melding fra harvest-admin (Publish) (8)

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2355]
https://www.asyncapi.com/

- [x] fdk-harvest-admin
- [ ] reg (neste sprint)
- [ ] cron (neste sprint)

**Comment by Chlenix** [comment]
foreslår at vi lager "reg" og "cron" som en (eller 2) separate tasks. Kanskje til neste sprint?

**Comment by sindresandvik2** [comment]
Lukket. Vil bli testet når Brukerhistorien er ferdig!
