### ISSUE TITLE
generere kjørbare api-docs fra spec

### ISSUE THREAD

**Issue by markkopaas** [Altinn/fdk#2356]
kjøre docs mot api i it1 (det er nåværende best demosystem)

**Comment by stigbd** [comment]
Vi må gjere ei behovsanalyse: kvifor vil vi dette? Kva for problem er dette ei løysing på?

**Comment by markkopaas** [comment]
Velocity tag mener effektivitet til utviklerene. se hvor mange tommelopp det blir.

Frontend-utvikler vil ha "exploration" av brukbare apiene.
Apiene med token authorization er lit vanskelig å kalle fra postman/curl.

også, det kan bli en fantastisk verktøy til Sindre, til å direkte teste apiene uten postman.
