### ISSUE TITLE
Feil ved bruk av lenker ut av NAP

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2359]
Dersom en klikker på  disse lenke-typer skal bruker navigeres UT av NAP:

Knytninger til begrep
Knytninger til API-beskrivelser
Knytninger til Datasett som er utenfor NAP

**Comment by lillelars** [comment]
Gjelder det også knytninger til datasett som er innefor NAP?

**Comment by oyvindis** [comment]
Avklart med Sindre, alle relasjoner peker ut av NAP (også relasjoner datasett/api/begrep som er NAP)

**Comment by sindresandvik2** [comment]
Ser ikke ut til å virke helt optimalt.  En kommer "Ut av NAP, men ingen Datasett, Api-beskrivelse eller begrep vises når en kommer inn på "ren" FDK detaljside. 
![image](https://user-images.githubusercontent.com/42966644/65515166-0e453280-dedf-11e9-9d5f-5c4ebefded0d.png)

**Comment by oyvindis** [comment]
Miljøvariabel SEARCH_HOST skal peke til ut1.fellesdatakatalog.brreg.no

Vi har definert variabel i ut1, men lenkene blir fortsatt feil, de blir defaultet til prod. Jeg må feilsøke litt mer på denne.

**Comment by sindresandvik2** [comment]
Nesten riktig.   Nå kommer en ut av NAP, men 
For begrep:  Fortsatt vises ikke begrepet   (og teksten i  Nettleserfanen vises fortsatt som NAP
For API: Når en klikker på FDK logo vises teksten i  Nettleserfanen fortsatt som NAP
For Datasett: Når en klikker på FDK logo vises teksten i  Nettleserfanen fortsatt som NAP

OBS:  Det ser ut som at vanlig FDK nå vises som NAP i nettleserfanen

**Comment by sindresandvik2** [comment]
Testet OK i UT1!
