### ISSUE TITLE
Lage en knapp for "Force-bygg dette bygget eksakt slik det er, på nytt"

### ISSUE THREAD

**Issue by thomasnokleby** [Altinn/fdk#2364]
Siden Nexus (filserver som leverer de forskjellige biblioteksfilene) sporadisk bare dør på seg, så trenger vi en knapp, ideelt sett på detalj-siden for bygget (Force Rebuild?), slik at vi enkelt kan prøve på nytt.

**Comment by markkopaas** [comment]
jeg brukte replay i dag (nexus error), og det funket fint!
