### ISSUE TITLE
Begrep mangler ved søk i Begreper i datasettkatalogens registreringsløsning

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#2382]
Jeg får to treff på "Adresse" når jeg søker på termen i begrepskatalogen i portalen, se https://fellesdatakatalog.brreg.no/concepts/422a5052-b21f-4abd-934b-8f015d188067  og https://fellesdatakatalog.brreg.no/concepts/bddb45d3-1353-4944-9b5d-bd2aad663872 .
Jeg får allikevel ikke opp "Adresse" når jeg søker på "Adresse" i begrepsfeltet i datasettkatalogen til Brønnøysundregistrene, men får opp "Adressekode", "Adressetekst" osv.

**Comment by sindresandvik2** [comment]
Gjenskapt. 
Problemet er i Datasett-registrering der en skal knytte begrep til et datasett.  Når en skriver inn et begrep dukker begrepsalternativene opp i liste under feltet. Når det blir for mange treff på søkeordet vises ikke alle treff.  Problemet gjelder også for søkeord som "sak" og "arkiv" 

Løsningsforslag; 
La eksakte treff komme øverst. Da vil bruker kunne skrive inn lengre søkestrenger for å redusere trefflisten og på den måten finne mer spesifikke ord som "adressetekst" 
Alternativ løsning er å legge til en link nederst "vis flere treff"

**Comment by oyvindis** [comment]
Jeg tror ikke jeg helt forstår hva du mener med løsningsforslaget, "eksakte treff øverst". Hvis du på noen måte vil endre rekkefølgen på søkeresultat så må vi konfigurere et eget endepunkt for dette som igjen har sin egen konfigurering mot elastic, f.eks. prefix-match eller annen type boosting av resultat. Det er den anbefalte måten å gjøre det på, men litt mer omfattende med frontend og backend.

Alternativt er å utvide hvor mange treff man viser i listen, f.eks. vise 20 treff.

**Comment by sindresandvik2** [comment]
Med eksakte treff øverst meiner eg at 
"sak" kjem før "saksarkiv"  når du søker på "sak"og "arkiv" kjem før "arkivskap" når ein søker på "arkiv"

Å utvide resultatlista kan også vere ei løsying, men då er nok også 20 treff for lite

**Comment by oyvindis** [comment]
Avklart, øker til 25 og må senere prioritere sak "tune søk" for å fikse underliggende problem.

**Comment by sindresandvik2** [comment]
Nå er det blitt slik at INGEN liste dukkar opp dersom ein skriv inn eit begrep i feltet

**Comment by sindresandvik2** [comment]
Retestet OK i UT1 ved å bruke søkeordet "sur" (som har 17 forekomster)
