### ISSUE TITLE
Endre lenke til å peke korrekt sted

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2395]
Lenken "Om Nasjonalt tilgangspunkt for transportdata" skal peke til http://dataut.vegvesen.no/group/about/nap

![image](https://user-images.githubusercontent.com/39513382/65486936-12089300-dea6-11e9-9903-defeaa0bef02.png)

**Comment by oyvindis** [comment]
Ekstern lenke, skal den også ha symbolet vi bruker for eksterne lenker?

**Comment by sindresandvik2** [comment]
OK i UT1.  Også godkjent av Frode.
