### ISSUE TITLE
Endre tekst i footer

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2396]
Teksten om samarbeidet i footer skal lyde: "Dette er et samarbeidsprosjekt mellom Statens vegvesen, Jernbanedirektoratet, Entur og Brønnøysundregistrene"

![image](https://user-images.githubusercontent.com/39513382/65486835-d077e800-dea5-11e9-9124-04c57c8ae293.png)

**Comment by sindresandvik2** [comment]
Utført OK  i UT1
