### ISSUE TITLE
Datasett som mangler EU-tema skal ikke tagges UKJENT dersom det finnes LOS-tema

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2414]
Det ser ut som at vi legger på tag'n UKJENT dersom det ikke er registret et EU-tema på datasettet. Så lenge det er registret minst et TEMA (enten LOS eller EU) skal ikke UKJENT tagges for noen av TEMA-variantene.

**Comment by lillelars** [comment]
Klarer ikke gjenskape lenger
