### ISSUE TITLE
Implementere støtte for "se-også"-relasjon

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2436]
- [ ] Man skal kunne opprette, endre og slette.

- [x] Validering

- [ ] NB husk test

**Comment by azaxarov** [comment]
Basert på samtale med @stigbd og @NilsOveTen:

- [x] concept-catalogue må kunne registrere en liste av referanser (begrep URIer) til "seeAlso" begreper

- [x] concept-catalogue må kunne eksponere rdfs:seeAlso ressurs som inneholder referanser (begrep URIer) til "seeAlso" begreper

- [ ] fdk-concept-harvester må kunne notere og lagre alle "seeAlso" relasjoner mellom interne og eksterne begreper ved høsting

- [ ] fdk-concept-harvester må kunne slå opp "seeAlso" relasjoner ved søk

**Comment by lillelars** [comment]
Fungerer som forventet
