### ISSUE TITLE
Validering mangler for NN og EN felt

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2446]
Validering  (eks:  feltet må ha minst to tegn) er ikke lagt inn for NN og EN -feltene

**Comment by joachim-me** [comment]
@sindresandvik2 Det er en større endring på validering av obligatoriske felt på ulike språk. Vi tar med denne her.

**Comment by oyvindis** [comment]
Denne validerer foreløpig kun obligatoriske språkfelt, dvs. tittel og beskrivelse.

**Comment by sindresandvik2** [comment]
Testet OK for Datasett Obligatoriske felt.
