### ISSUE TITLE
Registrere lese-bruker

### ISSUE THREAD

**Issue by stigbd** [Altinn/fdk#2447]
Som en bruker med leserolle i en gitt virksomhet i en katalog 
Ønsker jeg å opprette en bruker i begrepskatalogen basert på min e-post i virksomheten
Slik at jeg får logget inn i min virksomhets begrepskatalog som lesebruker.

Happy-flyt:

1. - Når bruker trykker på eksisterende  knapp "log inn i registreringsløsningen", kommer man til en ny versjon av https://registrering.fellesdatakatalog.brreg.no/loggin som er "delt i to". Til venstre kan man "registrere ny lesebruker" (og logge inn som lesebruker), til høyre logger man inn med skrive/admin-rettigheter via id-porten (som før).
2. - Ved å trykke på ny knapp "registrer ny lesebruker", kommer brukeren til ny login-side i sso-kompoenten. Her fyller hen inn e-post adresse (virksomhetsadressen) og navn. Brukeren trykker på "submit". Brukeren får melding om å sjekke sin inboks.
3. - Dersom virksomhetens e-post domene er "whitelisted", sendes en verifiserings e-post til brukeren med en lenke. 
4. - Når bruker trykker på lenken i verifiserings e-posten, kommer hen til det nye skjermbildet "Opprette lesebruker". 
5. - Bruker oppretter  passord og trykker på knappen "Opprett bruker", og hen kommer så til login-siden. Se brukerhistorie Logge inn som lese-bruker #2448 

Alternativ-flyt: e-post domene kan ikke knyttes til et gyldig organisasjonsnummer. Eks: bruker forsøker å registrere med @gmail.com:
- Starter i (2) "Brukeren trykker på "submit"".
- Bruker får beskjed i skjermbildet om at denne e-post adressen ikke er gyldig.

Alternativ-flyt: e-post domene kan knyttes til et gyldig organisasjonsnummer, men organisasjonen er ikke "del av FDK". Eks: bruker forsøker å registrere med xyz@stigsenkeltmannsforetak.no
- Starter i (2) "Brukeren trykker på "submit""
- Bruker får beskjed i skjermbildet om at denne e-post adressen går ikke.

Løsningsforslag:
- SSO-tjenesten sender verfisering e-post.
- Bruker-data håndteres av user-api tjenesten. __Denne mangler api-spesifikasjon, så den må lages.__ Og følgende nye operasjoner må lages: POST /users (lager ny bruker), PUT /users/{id}
- Whitelist er implementert i user-api.
- For å sjekke e-post domene mot organisasjonsnummer, to alternativer:
- - Vi kan undersøke om det finnes et api for dette, feks i norid.no. 
- - Vi må vedlikeholde dette selv i organization-catalogue.

Forutsetninger:
- relasjon mellom organisasjon og domene er m:n

- [x] Testdesign

- [x] Testgjennomføring
[2447.xlsx](https://github.com/Informasjonsforvaltning/fdk/files/3917184/2447.xlsx)

**Comment by markkopaas** [comment]
Mulige lagringsstrategier til lese-brukerne
1 - lagre alle brukerne i user-api  
2 - lagre read-access brukerne i separat lokal identity provider, som skal senere ble lagret i ldap eller postrgresql  
3 - lagre alle brukerne i postgresql i fdk realm.

metod 1 og 3 har en bonusfeature, at bruker kan "oppgraderes" fra lesebrukert til skrivebruker, og også motsattveg. ikke sikkert om metod 2


plan:
- [x] (refaktor) bevege tilgangsspørring fra login til token mapper (script)
- [x] rest user storage adapter skips email brukerne (vi kan fjerne den adapter senere)
- [x] bruker signup i local-idp
- [x] user-api skal svare email-brukerne (eller skal vi ha separat api endepunkte til username->authorities som ikke gir navn eller noe ant atributer)
- [ ] persistence til lokalbrukerne (først prøve ldap, postgres er backup option)
- [ ] smtp host og sette opp email verifisering
- [x] (cleanup) bruk skript mapper til autentisering i stedet av custom user federation provider
- [ ] (cleanup) http token mapper (java)
