### ISSUE TITLE
Logge inn som lese-bruker

### ISSUE THREAD

**Issue by stigbd** [Altinn/fdk#2448]
Som en registrert bruker med leserolle i en gitt virksomhet
Ønsker jeg å logge inn  i begrepskatalogen med min e-post adresse og passord
Slik at jeg får lesetilgang til min virksomhets begrepskatalog

Happy Flyt:
(1. punkt er identisk med #2447, men gjengis her:)
1. - Når bruker trykker på log inn i registreringsløsningen, kommer man til en ny versjon av https://registrering.fellesdatakatalog.brreg.no/loggin som er "delt i to". Til venstre kan man registrere ny lesebruker (og logge inn som lesebruker), til høyre logger man inn med skrive/admin-rettigheter via id-porten.
2. - Når bruker fyller ut brukernavn (e-post) og passord og trykker "logg inn som lesebruker", kommer bruker til sin(e) virksomhets/ers oversiktsside for kataloger som han har lese-tilgang til. 
3. - Når bruker trykker på begrepskatalog, kommer han inn i begrepskatalog med rettigheter for les.

Alternativ flyt: bruker er ikke registrert (e-post er ukjent)

Alternativ flyt: bruker oppgir feil passord

Alternativ flyt: Virksomheten har ingen kataloger
- Starter i 2: "bruker trykker logg inn som lesebruker"
- Brukeren kommer til et tom oversiktsside.

Løsningsforslag:
- Bruker får token i browser. (Dette er løst i #2447 )
- Design: "deaktivere" kataloger bruker ikke har lese-tilgang til
- Implementere "deaktivere" kataloger.
- Endre tilgangsstyring på concept-catalogue api.
- En million små concept-catalogue-gui oppgaver.

**Testcaser:**
(Denne brukerhistorien blir også testet knyttet til #4747
Testing av selve lesing av data gjøres i #2535)
- [x] Sjekk lesebruker tilknyttet virksomhet med data i alle tre kataloger
- [ ] Sjekk lesebruker tilknyttet virksomhet uten data (tomme kataloger) 
- [ ] Sjekk lesebruker uten tilknytning til virksomhet
- [x] Sjekk innlogging med feil passord

**Comment by sindresandvik2** [comment]
Testet så langt ein kan komme i ut1
