### ISSUE TITLE
Frontend - loginside splittes og legges til ny innlogging for lesebruker (1)

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2458]
Impl API-login side

https://projects.invisionapp.com/share/4KUKQMM2WRY#/screens/390718642_REG-KATALOGER-LOGIN-01

**Comment by markkopaas** [comment]
Vår implementasjon av sso ikke frame-mulighet. Det mener at applikasjon kan bare gi et hint til sso, hvilke metod skal brukes.  Så den venstre blokk skal også ha bare en knapp "log inn med e-mail", ikke form.

En alternativmulighet er at vi bare har en login knapp, som da åpner en sso skjerm, som har to del. Det er egentlig enkleste å implementere, kanskje vi kan vise demo.
![image](https://user-images.githubusercontent.com/7446932/67165264-6eff4800-f383-11e9-935f-bf27ae3069a4.png)


Det er jo egentlig teknisk mulig å implementere  brukernavn-passord autorisering, som tegnet i oppgave men det er ikke enklere.

**Comment by skobba** [comment]
Avbryter videre arbeid på denne intill vi vet mer om keycloak.

Bakgrunnsbilde: https://www.dropbox.com/s/atx73976zjhyz0w/illustration-login.svg?dl=0
**Dissable theme caching**
`located here
./standalone/configuration/standalone.xml
Make the following changes to standalone.
<theme>
    <staticMaxAge>-1</staticMaxAge>
    <cacheThemes>false</cacheThemes>
    <cacheTemplates>false</cacheTemplates>
    ...
</theme>`

**Comment by lillelars** [comment]
Testet OK i Chrome og Edge.
Opprettet egen bug på feil tekst. Se #2615 . Må håndteres før prodsetting.
