### ISSUE TITLE
Persistering av brukere

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2461]
LDAP
En del av denne oppgaven er å finne ut om dette lar seg gjøre enkelt eller ikke.
Mål: Hvor lang tid vil det ta?
Timeboxes til 6h.

**Comment by sindresandvik2** [comment]
Brukere forsvinner fortsatt ved restart av SSO-pod.  Fortsatt feil!

**Comment by NilsOveTen** [comment]
Fortsatt 2 bugs

- Brukere i idporten-mock blir ikke oppdatert

- Keycloak klarer ikke å opprette eget schema

**Comment by NilsOveTen** [comment]
Idporten-mock brukere skal nå bli importert.

Vi må alltid manuelt lage databasen til keycloak, vi kan like så greit lage schema i samme slengen. Eneste blir at keycloak lagrer til public-schema ved lokal utvikling.

**Comment by sindresandvik2** [comment]
Retestet OK i UT1.  Lesebruker fortsatt intakt etter restart av POD
