### ISSUE TITLE
 Konfigurer keycloak til å benytte SMTP server

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2462]
- [x] leg til variablene som at keycloak kan benytte SMTP server
- [x] lage konto i gmail, slå av 2-trinn autorisering.
- [ ] konfigurere mail-parametrene i sso service.

**Comment by NilsOveTen** [comment]
Testet med en tilfeldig smtp-server. Kom meg gjennom hele prosessen, med alt av verifisering osv

![Screenshot from 2019-10-28 10-18-34](https://user-images.githubusercontent.com/50194012/67667581-6b188a80-f96e-11e9-8635-239d71a5388e.png)

**Comment by markkopaas** [comment]
@Stig B. Dørmænen Hvordan kan vi gå videre? jeg ser minst tre ting vi kan prøve: 1) skal vi prøve ut brreg.no server? 2) skal vi prove smtp.gmail.com relay med from og reply address i brreg.no? skal vi prøve ut noe andre smtp tjenestene (mailjet?)


Markko Paas  13 minutes ago
jeg kan prøve 2) med min personlig gmail konto, hvis jeg får en offentlig reply address som ligger i brreg.no

Markko Paas  12 minutes ago
ok, jeg kan teste med from/reply til extmpa@brreg.no

**Comment by markkopaas** [comment]
@stigbd @joebrreg 

Jeg har nå testet nå scenario 2)

input:
user = markko.paas.smtp@gmail.com
from = extmpa@brreg.no
from name = xxx
replyTo= extmpa@brreg.no
reply to name = xxx

output:
- fikk email
- from var endret til user - markko.paas.smtp@gmail.com (xxx)
- reply åpner extmpa@brreg.no

Så det er enkelt og funker ganske greit.

**Comment by stigbd** [comment]
Kan du teste med user = extmpa@brreg.no?

**Comment by markkopaas** [comment]
testet nå. den nesten vellykket.
Først prøvde jeg logge inn gmail med "extmpa@brreg.no". google var "kind enough" til å la meg å lage en alias konto. men jeg måtte ha en ny gmail-konto, det ble markko.paas.extmpa@gmail.com. Og det ser ut at det funker ok fordi jeg kan nå logge seg på gmail med extmpa@brreg.no. Bra.

så prøvde jeg å autorisere smtp.
feil med extmpa@brreg.no, vellykker med markko.paas.extmpa@gmail.com
Og dessverre, user fortsett overskriver "from" feltet. Så den from er fortsett markko.paas.extmpa@gmail.com

det var nesten.

**Comment by valosnah** [comment]
fellesdatakatalog.brreg@gmail.com

2-faktor er av.
Passord kan etterspørres på slack

**Comment by lillelars** [comment]
@valosnah @markkopaas  Kan dere ferdigstille denne? Hvem tar ansvar for å legge siste bit inn? :)
