### ISSUE TITLE
Validering av email

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2465]
- [ ] E-post domene som ikke kan knyttes til et gyldig organisasjonsnummer.
For eksempel dersom bruker forsøker å registrere seg med @gmail.com må dette håndteres. Skal gi beskjed til bruker at e-mail ikke er gyldig.

- [ ] e-post domene kan knyttes til et gyldig organisasjonsnummer, men organisasjonen er ikke "del av FDK".
Eks bruker forsøker å registrere med xyz@stigsenkelmannsforetak.no 
bruker får beskjed om at denne emailen ikke kan brukes.

**Comment by sindresandvik2** [comment]
Registrering av vilkårlig gmail-bruker gir forventet feilmelding i UT1
