### ISSUE TITLE
READ access mock

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2475]

**Comment by markkopaas** [comment]
vi har alledre implementert miljøvariable basert admin-rolle. På samme måte er det mulig å gi vist email brukerne read tilgang. 
Forslag til format er json map:
ADMIN_LIST:23076102252
AUTHORITIES:{"my@.email.com":"publisher:8893483943:read"}

**Comment by lillelars** [comment]
dupliat - løses av frontend
