### ISSUE TITLE
Registrering - Registrere gyldighet

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2486]
- [ ] Trenger frontendvalidering på at Fra ikke er etter TIl

Se design:
https://invis.io/3SRCN149CQN#/356261432_BEGREP-REG-Gyldighet-Default--D-

Se design _lesebruker_:
https://projects.invisionapp.com/share/3SRCN149CQN#/screens/388727723

**Comment by joachim-me** [comment]
Testet i demo i Chrome og Firefox.
