### ISSUE TITLE
Søkeportal - Registrere gyldighet - vise gyldighet

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2488]
Se design for portal:
https://projects.invisionapp.com/share/3SRCN149CQN#/screens/382272198

Se design for Detaljside (bla 1-3 sider til høyre):
https://projects.invisionapp.com/share/3SRCN149CQN#/screens/378074325

**Comment by lillelars** [comment]
ser ikke ut til at "gyldighet" blir høstet korrekt?

**Comment by stigbd** [comment]
Eksempel hadde vore fint, ver så snill.

**Comment by lillelars** [comment]
Fungerer som det skal nå.

**Comment by lillelars** [comment]
Testet i demo m/ chrome. Fungerer som forventet
