### ISSUE TITLE
Brødsmulesti for begrep må være lik som for datasettbeskrivelse

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2490]
NB! Denne bør gjøres sammen med #2505

Når en nå går inn på et eksisterende begrep så vises fortsatt teksten "Registrer nytt begrep" i brødsmulestien.    "Registrere nytt begrep skal kun vises for helt nye begrep og skal endres så snart noen skriver i feltet Anbefalt term  (Slik som det fungerer for datasettregistrering)

![image](https://user-images.githubusercontent.com/42966644/65962489-16f6b500-e459-11e9-8cbb-419b6a1a9483.png)

**Comment by lillelars** [comment]
@skobba denne bør gjøres samtidig som #2505 ettersom det sannsynligvis skal inn i samme logikk.

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
