### ISSUE TITLE
Endre felter "anbefalt term" og "definisjon" i begrepsmodell (backend)

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2501]
Utvide slik at "anbefalt term" og "definisjon" i begrepsmodell støtter språk (backend).

- [x]  Endre i speccen

Høy risiko.

Plan "mongon & database reset"
---

 - [x] Kopere mongo-repository løsning fra "a-backend reposittory
 - [x] getAll
 - [ ] post (her kan frontend få list og legg til nye)
 - [ ] patch (her kan frontend edit)
 - [ ] publisher filter i getAll
 - [ ] ? bestemme hvis status filter trenges - det er ikke i bruk, vurdere å fjerne fra
 - [ ] turtle
 - [ ] ? de andre jena formatene i output

Plan "compatibility mode og postgres", ikke valgt å gå videre med
---

- [x] concept-catalogue-gui support for strings/maps from GET (anbefaltTerm, definisjon)
- [ ] harverst endpoint support for strings/maps from DB (anbefaltTerm, definisjon)
- [x] concept-catalogue should return maps from GET (anbefaltTerm, definisjon)
- [ ] concept-catalogue POST/PATCH writes maps to DB (anbefaltTerm, definisjon)
- [ ] concept-catalogue-gui support for POST/PATCH maps (anbefaltTerm, definisjon)
- [ ] migrate data in concept-catalogue DB from strings to maps (anbefaltTerm, definisjon)
- [ ] remove compatibility mode code in concept-catalogue and concept-catalogue-gui

----
chore
 - [ ] opdatere mocks
 - [ ] separere list query fra enkel item query.

----
cleanup
- [ ] migrere database - string til json
- [ ] fjerne alt støtte av string

**Comment by lillelars** [comment]
@markkopaas kan du begynne med denne?

**Comment by stigbd** [comment]
Endret spec i https://github.com/Informasjonsforvaltning/concept-catalogue/tree/feat/change-spec-to-support-multiple-languages

**Comment by sindresandvik2** [comment]
I UT1 fungerer språkstøtte for to obligatoriske felt.
editering, lagring og publisering er OK
