### ISSUE TITLE
Logikk rundt validering av obligatoriske språkfelt

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2502]
Obligatoriske felt gjelder uavhengig språk. Det betyr at dersom bruker legger inn verdi i "Anbefalt term"på Nynorsk er det tilstrekkelig til å validere godkjent for dette feltet.

Det må altså lages en logikk der valideringen sjekker mer enn bare bokmål-feltet på de obligatoriske feltene.

- [ ] Validering av obligatoriske felt - BEGREP

**Comment by sindresandvik2** [comment]
OK i Frontend, men ny feil registrert slik at BE også implementerer de samme reglene.
