### ISSUE TITLE
Tekstendringer i API-registrering

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2503]
- [x] 1) "Registrere ny API-beskrivelse" --> Skal hete "Registrer ny API-beskrivelse"

- [x] 2) "Legg til ny API-beskrivelse" --> Skal hete "Registrer ny API-beskrivelse"

- [x] 3) Registrering av API'er skal fjernes fra denne siden.

- [x] Fjern header fra datasett-registrering

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/5d889740-2c6d-43f1-9199-6f0391e0dbdb)

**Comment by sindresandvik2** [comment]
Vakkert implementert i UT1
