### ISSUE TITLE
Tittel ved registrering av nye begreper får nytt design og ny funksjon

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2505]
- [ ] Fjerne tittel fra header

- [ ] Tittel på siden der en registrerer nytt begrep skal fungere likt som brødsmulestien.

Se design:
https://projects.invisionapp.com/share/3SRCN149CQN#/screens/356259398

Vi ønsker å gjøre dette konsekvent over alle katalogene våre.
Tittelen skal ikke lenger vises i header, men som tittel over der skjema begynner.

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/479a34a4-1fec-4add-a1cb-bcefde2b9947)

**Comment by sindresandvik2** [comment]
Fjerning av tittel mangler

**Comment by sindresandvik2** [comment]
OK i UT1
