### ISSUE TITLE
Feilmelding "Something went wrong ved opning av Datasett detalj

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2510]
Feil er ikke konstant hos alle og kan ikke gjenskapes.  Feilen har tidligere vært observert av Sindre, men etter rydding av nettleserdata forsvant problemet.

Nå er feilen meldt inn av kunde, jim.yang@difi.no (problemet forsvant etter oppdatering av PC)
![something went wrong.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/360e6e63-6be2-4ba2-a033-1c2e1f34a89b)

I følge https://reactjs.org/docs/error-decoder.html/?invariant=185 har dette noe med en resuursgrense som er nådd.

Andre observasjoner:
- Feilen er så langt kun identifsert i Chrome
- Det kan se ut som at feilen oppstår når en åpner de datasettene med flest linker/mest data
- På min (@sindresandvik2 ) maskin dukker nå feilen alltid opp i **Chrome** når jeg prøver å åpne detaljsiden for "Kontakt- og reservasjonsregisteret"   Tilsvarende forsøk i IE, Edge, Firefox går fint!
- Fjerning av Nettstedsinnstillinger i Chrome (innstillinger) løste problemet midlertidig

**Comment by joachim-me** [comment]
Feilen har nå også oppstått i Edge.

**Comment by joachim-me** [comment]
Feil gjenskapt i Edge: Microsoft Edge 44.18362.449.0, Microsoft EdgeHTML 18.18363
![image](https://user-images.githubusercontent.com/46488929/70146955-9f851200-16a3-11ea-94cc-d4e8b60a402e.png)

**Comment by sindresandvik2** [comment]
Feil fiksa i IT1 Verifisert via Edge
