### ISSUE TITLE
Skrivefeil detaljside information model

### ISSUE THREAD

**Issue by joachim-me** [Altinn/fdk#2519]
Skrivefeil. Skal stå Information Model Description:
![image.png](https://images.zenhubusercontent.com/5c6e939eab9efc3c63334546/562d5f71-cbb1-4199-a53d-f9fbeaac0ad5)

I tillleg skal det stå The National Data Catalog. Dette gjelder for alle detaljsider.

**Comment by sindresandvik2** [comment]
Retestet ok i UT1 for alle 4 detaljsider (engelsk)  pluss heading i Informasjonmodell
