### ISSUE TITLE
Begrepskatalog - nytt design på tittel

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2524]
Tittel skal nå fjernes fra Headeren og legges over tabellen i main i stedet.

Tittel over tabell over begreper i egen virksomhet (må fikse tittel + virksomhet). 
Se design:
https://projects.invisionapp.com/share/3SRCN149CQN#/screens/385434191

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
