### ISSUE TITLE
admin backend komponent - REST DELETE (2b) 

### ISSUE THREAD

**Issue by stigbd** [Altinn/fdk#2533]
Vi trenger en DELETE-operasjon i fdk-harvest-admin. Skal slette en gitt DataSource.

**Comment by stigbd** [comment]
Operasjonen er lagt til i OpenAPI-spesifikasjonen på ny branch: feature/deleteDatasource

**Comment by sindresandvik2** [comment]
OK. Testet via Postman sammen med German
