### ISSUE TITLE
Fjern mouseover i sammendragsbokser!

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2534]
Nå dukker Mouseover opp overalt i sammendragsboksene uten at det gir merverdi. (I tillegg vises det feil tekst for Datasett, Begrep og Informasjonsmodeller)

Fjernes for ALLE sammendragsboksene (Datasett, API-beskrivelse, Begrep, Informasjonsmodeller)

**Comment by lillelars** [comment]
utgår.
