### ISSUE TITLE
Make API-catalogues available throug a DCAT-AP-NO v.2.0 endpoint 

### ISSUE THREAD

**Issue by stigbd** [Altinn/fdk#2537]
NB! Første oppgave her er å se ha grooming session hvor deltagerne også finner et ca estimat.

Reduserer denne oppgaven ned til 6 felter:
Tittel
Beskrivelse
Utgiver
format
Link til speccen
serverURL

As an owner of a API-catalogue
I want to make my API-descriptions available as a DCAT-AP-NO v.2.0 endpoint
So that interested parties can harvest my API-catalogue

-----
Ref the example over at https://raw.githubusercontent.com/difi/dcat-ap-no/review/ontology/catalog.ttl
An example catalogue: https://raw.githubusercontent.com/brreg/openAPI/master/specs/API-catalog.ttl
Tasks:

- [x] Create a service that, using the above library, reads the example "catalogue" and makes it available by e.g. curl -H "Accept: text/turtle" https://data.brreg.no/apis

**Comment by markkopaas** [comment]
Tjeneste som serverer api-registreringene  i dag er "registration-api". Så vi har følgende mulige strategier 
 1) separere ut api registration som eget tjeneste (nodejs) (som concept-catalogue er)
 2) harvest endpoint som eget tjeneste (nodejs), knuttet med registration-api database
 3) legg til harvest endpoint til eksisterende api. (spring)

jeg tror 3) er mest praktisk, mens 1) kan ta oss nærmere til den arkitekturmål, hvor alt er separert.

Jeg har ikke søkt om turtle implementasjon i Javascript. Det er mulig at slik finnes.
