### ISSUE TITLE
Harvest API-descriptions in a catalogue on an event

### ISSUE THREAD

**Issue by stigbd** [Altinn/fdk#2538]
As a system-administrator of FDK
I want to harvest API-descriptions based on DCAT-AP-NO v2.0 DataService triggered from fdk-harvest-admin-gui
So that FDK-portal gets updated with the latest API-descriptions from the relevant API-catalogue.

Tasks:
- [x] Update admin-gui to represent dataservice (DCAT-AP-NO v2.0)

- [x] add dataservice type in backend

**Comment by lillelars** [comment]
Kan lukke denne etter prat med Nils Ove
