### ISSUE TITLE
Skjule katalog- datasett og api inngangsknapper (registration-react)

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2542]
Se design: https://projects.invisionapp.com/share/8WTQMR2A35G#/screens/393429389_FDK-WF-Registrering-Oversikt

Se også hover-effecten over knappene.

API-katalog og Datasettkatalog skal gråes ut (gjøres så de ikke er klikkbare) dersom bruker er logget på som en lesebruker:

Testgjennomføring:
- [ ] Verifiser at knapper er fjernet (skal gråes ut, ikke være klikkbare)
- [ ] Verifiser at admin-bruker fortsatt har knappene tilgjengelige OG at de fungerer

**Comment by oyvindis** [comment]
Løsning her løses på samme måte som i #2543

**Comment by sindresandvik2** [comment]
Testet OK i uT1 ofr eksisterende og ny lesebruker
