### ISSUE TITLE
Skjule opprett begrep og publiseringsbar i concept-catalogue-gui 

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2543]
ved innlogget lese-bruker

**Testgjennomføring:** 

- [ ] Verifiser at knapp og publiseringslinje er fjernet

- [ ] Verifiser at knapp og publisering/sletting fortsatt fungerer for admin-bruker

**Comment by oyvindis** [comment]
Bruke CASL for å sjekke om komponenter kan vises basert på regel knyttet til rolle.

**Comment by lillelars** [comment]
Testet OK i chrome og edge.
