### ISSUE TITLE
Begreps-registrering: når bruker fjerner innhold fra obligatorisk felt og skal registrere nytt innhold

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2547]
Statusbaren endrer seg ikke tilbake slik at bruker får beskjed om at skjemaet er lagret.
Det ser likevel ut som at brukerinput blir lagret, så det virker som det bare er feil med statusbar.

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/329c2fdd-48ae-490c-b5cf-32cee2cf62af)

**Comment by sindresandvik2** [comment]
Testet ok.  Meldingen forsvinner .
