### ISSUE TITLE
Tilgangskontroll: Bruker med mange reportees får ikke tilgang til registreringsløsningen

### ISSUE THREAD

**Issue by stigbd** [Altinn/fdk#2551]
I dag gjør vi følgende spørring mot Altinn:
```
GET /api/serviceowner/reportees?ForceEIAuthentication&subject=<personid>&servicecode=4814&serviceedition=1
```
Det gir liste over reportees for berørt bruker. Ingen av disse reportees gir bruker tilgang til registreringsløsningen. Det viser seg at spørringen ikke gir oss _alle_ reportees knytta til brukeren.

Ved å filtrere på ulike måter ihht. https://www.altinn.no/api/serviceowner/help har vi fått redusert lista til relevante reportees (for denne brukeren), og der får vi treff på den kommunen brukeren har reportee-rollen for. Den filtrerte spørringen vi teste med var:
```
GET api/serviceowner/reportees?$filter=Type%20eq%20%27Enterprise%27&ForceEIAuthentication&subject=<personid>&servicecode=4814&serviceedition=1
```
Imdilertid kan vi ikke benytte denne type filter, siden den kan potensielt filtrere bort andre brukere, og etter tips fra Altinn, bør vi bruke skip/orderby, ref https://www.odata.org/documentation/odata-version-2-0/uri-conventions/ . Dette er etter det vi forstår, måten å få til en slags paging-funksjonalitet mot dette OData-APIet.

Hvordan dette skal løses i praksis, må vi teste ut. Antageligvis som følger:
Først hente N første ved:
```
GET api/serviceowner/reportees?$orderby%20eq%20%27OrganizationNumber%27&ForceEIAuthentication&subject=<personid>&servicecode=4814&serviceedition=1
```
så hente neste fra og med nummber N+1 ved (eksempelet er N=50, men det må sjekkes):
```
api/serviceowner/reportees?$skip=50&orderby%20eq%20%27OrganizationNumber%27&ForceEIAuthentication&subject=<personid>&servicecode=4814&serviceedition=1
```
til vi ikke få flere i responsen.

**Comment by sindresandvik2** [comment]
Tilgang er nå på plass

**Comment by stigbd** [comment]
Bekrefta ok fra bruker.
