### ISSUE TITLE
Sende Trigger Melding fra en cronscript (hver 6. time)

### ISSUE THREAD

**Issue by Chlenix** [Altinn/fdk#2560]
- [ ] Opprett ny tjeneste, ref oppskrift for dette. Repo bør hete "fdk-harvest-scheduler" (@valosnah )
- [ ] Lag ny oppskrift for ny tjeneste som tar høyde for GitHub Actions (@valosnah )
- [x] Implementer tjeneste (@Chlenix )
- [ ] Config (dvs helm-ting) skal ligge i repo, og ikkje i fdk-config.

**Comment by valosnah** [comment]
@Chlenix Vi har ikke begynt med selve tjenesten, men repoet er klart til bruk.

**Comment by valosnah** [comment]
Status 29.10: 
Kommuniserer med Kubernetes
Laster opp Dockerimage
Får generert og apply'et Helm template

Holder på med:
Kjøre deployen på Kubernetes

Det er en del prøving og feiling, og tidstyven pr nå er at vi må kjøre komplette bygg.

**Comment by lillelars** [comment]
Tested OK i ut1
