### ISSUE TITLE
keycloack theme - konfigurering

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2576]
Design: https://projects.invisionapp.com/share/8WTQMR2A35G#/screens/390718641

Account page url: http://localhost:8084/auth/realms/fdk-local/account

Admin page: http://localhost:8084/auth/admin/

standalone.sh: /opt/jboss/keycloak/standalone/configuration/standalone.xml

**Comment by lillelars** [comment]
Disable caching for themes, se: https://medium.com/@auscunningham/create-a-custom-theme-for-keycloak-8781207be604

**Comment by skobba** [comment]
# Login

![image](https://user-images.githubusercontent.com/16732769/68463237-7d1be800-020e-11ea-8005-9802f8e358f8.png)

# Registrering
![image](https://user-images.githubusercontent.com/16732769/68463287-99b82000-020e-11ea-9517-4b8a530bdcbd.png)

# Glemt passord
![image](https://user-images.githubusercontent.com/16732769/68463314-a63c7880-020e-11ea-8dfa-33000fbeae29.png)

**Comment by sindresandvik2** [comment]
OK for lesebruker i UT1
