### ISSUE TITLE
NAP - Vise hvilken portal det publiseres til

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2582]
Som: datasetteier
Ønsker jeg å: gjennom valg som gjøres i registreringen se om datasettet blir publisert henholdsvis i åpne data portal og sektor-portal (f.eks. NAP)
Slik at: jeg forstår konsekvensene av mine valg

Relatert til epos: #346

Lenke til design: https://invis.io/SFTW6CSAD94#/384955884_REGISTRERING-Datasett-01
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Viktig

Akseptansekriterier:
,# language: no
Egenskap:
Kriterier:
⦁ Vise meldinger om at datasett publiseres til NAP

Referanser:
Scenario: Vise meldinger om at datasett publiseres til NAP
Gitt at detaljsiden for registrere nytt datasett vises
Når bruker velger "Tilgangsnivå" = "Offentlig"
og bruker velger "Tema" = "Trafikk, reiser og samferdsel"
Så skal meldingen "Datasettet vil bli publisert i Felles datakatalog og NAP" vises på siden

- [x] Testdesign

- [x] Testgjennomføring 
[2582.xlsx](https://github.com/Informasjonsforvaltning/fdk/files/3836096/2582.xlsx)

**Comment by sindresandvik2** [comment]
Testet ferdig.  En feil registret som følges opp separat
