### ISSUE TITLE
Infomeldinger om publisering i ulike portaler

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2584]
Publiseres i NAP: https://invis.io/N9Q9157SD3U#/389790259_DATA-REG-Tema-emne-Nap--D-
Publiseres ikke i NAP: https://invis.io/N9Q9157SD3U#/390664516_DATA-REG-Tema-emne-Ikke-Nap--D-

**Comment by sindresandvik2** [comment]
Test ok. i UT1. En feil registert  #26554
