### ISSUE TITLE
admin-gui: Får ikke lagt til noen endepunkter

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2594]
Testet i IT1:
Steg 1: Legger til info om nytt endepunkt jeg ønsker å høste fra.
![image](https://user-images.githubusercontent.com/39513382/67859895-f768b000-fb1c-11e9-971c-4e41329285c8.png)

Steg 2: Trykker "Save". Ingenting dukker opp

![image](https://user-images.githubusercontent.com/39513382/67859920-03ed0880-fb1d-11e9-8bec-3038ab60336e.png)

**Comment by azaxarov** [comment]
Mismatch mellom API og GUI versjonene

**Comment by lillelars** [comment]
@azaxarov skal ha fått siste versjon inn til it1 nå (ser både logout, og strengen du endret til SKOS-AP-NO), men klarer fortsatt ikke å legge til info om ønsket endepunkt..

**Comment by valosnah** [comment]
Det virker som problemet skyldtes en healthcheck som ikke ville oppdatere seg automatisk.

**Comment by lillelars** [comment]
testet ok i IT1
