### ISSUE TITLE
Høsting blir trigget hele tiden i it1

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2605]
Et health-check frå Kubernetes mot /collections-endepunktet. Denne må fjernast/slåast av asap.
Det fungerer ikke at høsting trigges hele tiden hvertfall :)

**Comment by stigbd** [comment]
Det er begreper/ping som skal brukast. Truleg er dette korrekt i andre miljøer.

**Comment by valosnah** [comment]
Healthcheck oppdatert. Så ut til å være noen gamle verdier som ikke hadde blitt oppdatert i Kubernetes.

**Comment by lillelars** [comment]
ser ut til å fungere som det skal nå
