### ISSUE TITLE
Registreringsløsningen virker ikke - får blank side når jeg vil legge til eller redigere et datasett

### ISSUE THREAD

**Issue by hildea** [Altinn/fdk#2608]
Jeg prøver å redigere et datasett i https://registrering.fellesdatakatalog.brreg.no/catalogs/971032081/datasets , men får en blank side:

 ![registrere_datasett](https://user-images.githubusercontent.com/6659191/68190491-ca4d4f00-ffad-11e9-96ad-d16c073d9f70.PNG)

Jeg får sida over etter å ha klikket på en av "Utkast"-lenkene her:
![registrere_datasett2](https://user-images.githubusercontent.com/6659191/68190725-3a5bd500-ffae-11e9-8f79-a6d5ae8dd802.PNG)

Registreringsløsninga ser ut til å virke for APIer og begrep. 

Registreringsløsninga har virket greit tidligere, siste gang jeg er sikker på at det var OK var 6. september, men jeg tror jeg har vært inne seinere også. (Jeg skal ikke faktisk legge til datasett, men jeg vil se nærmere på feltene i registreringsskjemaet.)

**Comment by stigbd** [comment]
Takk for at du melder. Problema du opplever skuldast feil vi har i integrasjon mot andre eksterne tjenester. Vi jobbar intenst med å løyse problemet.

**Comment by stigbd** [comment]
Då er feilen funne og retta. Dermed skal Registreringsløsningen virke igjen. Det er mulig du må "refreshe" sida for at løysinga skal fungere hos deg.

Eg lukker dermed dette issuet, men om du stadig opplever problemer, meld tilbake her.
