### ISSUE TITLE
forbedre måte å kjøre tjenestene lokalt

### ISSUE THREAD

**Issue by markkopaas** [Altinn/fdk#2609]
1) bruk docker repository, til å unngå lokal bygge av alle imagene.
2) forbedre lokal-miljø setup. Vi bruker docker-compose til å kjøre tjenestene lokalt, men akkurat nå ligger docker-compose filene i selveste sub-repoene. Løsning er å duplisere (eller sette sammen) en docker-compose fil i fdk-docker-compose repo.

Til slutten, det mener at hvis man har tom disk, de eneste man må gjøre er
```
git clone fdk-docker-compose
cd fdk-docker-compose
docker-compose up -d
```

**Comment by markkopaas** [comment]
@stigbd  har du noe idé, hvordan kan vi løse dette?

**Comment by stigbd** [comment]
Problem 1 trur eg er enkel løysing på. Premisset er feil. Det er ikkje korrekt at vi ikkje har tilgjengelig docker-repository. Google sitt Container Registry _er_ tiljgengelig:
```
docker pull [HOSTNAME]/[PROJECT-ID]/[IMAGE]@[IMAGE_DIGEST]
```
Ref https://cloud.google.com/container-registry/docs/pushing-and-pulling

**Comment by markkopaas** [comment]
jeg tror det kan være en løsning! 
det er par ting som vi må prøve ut:
- ci må tag også  trunk build som "latest" (eller vi kan regne image nøkkel fra kildekode)
- fikse docker-compose file med riktig image
- autorisering av repo

**Comment by markkopaas** [comment]
løsning til 2 kan være at i stedet av å referere filene til repo, vi kan faktisk gjøre manuell merge av docker-compose fil

**Comment by stigbd** [comment]
Kva for "brukerhistorie" er dette ei løysing på?

**Comment by markkopaas** [comment]
Til å utvikle, trenger du å kjøre (en del av) systemet på et kontrollert måte. 
Enkleste måte er å gjøre det er å kjøre på lokal maskin.

**Comment by markkopaas** [comment]
Fra slack:


Stig B. Dørmænen Today at 10:01 AM
Minner om at det er mulig å "pulle" våre images frå Google Cloud registry når du bruker docker/docker-compose lokalt. På den måten er det relativt enkelt å utvikle/test ein tjeneste lokalt ved å hente andre tjenester frå registry. @Hans Olav Sund Eg foreslår at du lagar ei oppskrift på feks Confluence. Referanse:
https://cloud.google.com/container-registry/docs/pushing-and-pulling
:+1:
1

3 replies

Stig B. Dørmænen  1 hour ago
Eksemple på korleis referere til eitt av våre images er:
image: eu.gcr.io/fdk-infra/api-cat:env_ut1_latest
(edited)
:+1:
1


Stig B. Dørmænen  1 hour ago
PS! Disse images er public, så det betyr at det ikkje trengs autentisering eller liknande for å pulle.
:+1:
1

**Comment by markkopaas** [comment]
I byggescript, finnes det følgende linje til image tagging:
https://github.com/Informasjonsforvaltning/fdk-config/blob/17ea269981e59275e60fa5c74f4d2de62d431a15/jenkins/deploy/deploy.jenkinsfile#L96

og vi kan allerede se den syntaks i bruk her:
https://github.com/Informasjonsforvaltning/organization-catalogue/blob/7c0b0d6ae4262d8e9f4c1ba7246e992afd879d43/docker-compose.override.yml#L5

Skal vi bestemme officielt at CI trunk build heter  "env_ut1_latest" eller skal vi endre byggeskript å generere noe mer semantic tag?

master (fordi vi ønsker å bevege alle repoene til å bruke master som trunk)
trunk (fordi det er generisk, noen repoer bruker master, noen develop)
ci_master/ci_trunk - å vise at den var bygget i ci 
latest - fint fordi da er det lett å overstyre det med lokal build, uten ekstra tagging, som også. Vi må bare ta vare, at bare trunk build (=deploy to ut1) skal push denne tag til repo.

**Comment by markkopaas** [comment]
Nils Ove  5 hours ago
Tror planen er at @Hans Olav Sund skal fikse en 'latest'-tag


Markko Paas  5 hours ago
men da må det filtrert

Markko Paas  5 hours ago
at bare trunk build skal tagges latest, og ikke brasch build (edited)

**Comment by markkopaas** [comment]
når @valosnah  er klar met #2331, kan vi bruke den samme configfil som HELM bruker, også lokalt.
