### ISSUE TITLE
unifisere struktur av maven pom.xml filene i prosjektene

### ISSUE THREAD

**Issue by markkopaas** [Altinn/fdk#2613]
som eksemple, mitt siste oppdrag var å sammenligne concept-catalogue og organization-catalogue.  byggekonfigurasjoner er alt for forskjellige, og overføring av løsningene er vanskelig.

en løsning kan være at vi velger en leder-prosjekt i hver teknologi (sannsynligvis den som får utviklingsprioritet fra features)- og de andre prosjektene koperer fra dette.

**Comment by stigbd** [comment]
Enig i at det er eit mål at alle pom.xml bør vere like. Men i og med at alle tjenestene våre er på ulike stader i livssyklusen til eikvar tid, vil ikkje dette vere slik i praksis. Eksempel: organization-catalogue har lært av og forbedra i forhold til concept-catalogue. Når vi refaktorerer concept-catalogue, vil denne trulig implementere forbedringar i forhold til organization-catalogue. 

Så unifisering er ikkje eit mål i seg sjølv. Kontinuerlig læring og forbedring er eit mål.


Til slutt: a-backend-service er nettopp eit slikt leder-prosjekt (template repository i GitHub) som nye repoer skal bygge på.

Eg foreslår derfor at du lukker denne.
