### ISSUE TITLE
Feil tekst for lesetilgang

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2615]
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/00fd1ef1-5c27-4c22-91f5-46e6b4c6e727)

Skal stå "Med lesetilgang kan du se all informasjon din virksomhet har registrert i sine kataloger"

![image](https://user-images.githubusercontent.com/39513382/68282469-12d23e80-007a-11ea-8d37-958743993b95.png)
Skal stå: "Du kan gi andre skrivetilgang til katalogene for din virksomhet via Altinn. 
Les mer om hvordan du gir andre tilgang"

**Comment by sindresandvik2** [comment]
Endring på plass i UT1  (med et par små  ekstra justeringer som ser ut til å være OK)
