### ISSUE TITLE
Lenker for lesebruker bør fortsatt være klikkbare og vises som lenker

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2617]
Lenker bør fortsatt være klikkbare lenker (gjelder hvertfall omfang og kilder)
![image](https://user-images.githubusercontent.com/39513382/68283481-e7505380-007b-11ea-8a91-d79554e57b51.png)

![image](https://user-images.githubusercontent.com/39513382/68283637-2b435880-007c-11ea-972e-84ab3ddec848.png)

**Comment by sindresandvik2** [comment]
Retestet OK i UT1. Lenker knyttet til Kilde og tol Omfang virker fint
