### ISSUE TITLE
String for Obligatorisk felt skal fjernes for lesebruker

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2619]
![image](https://user-images.githubusercontent.com/39513382/68284676-35feed00-007e-11ea-883a-44d22de69ed1.png)

**Comment by oyvindis** [comment]
@lillelars String for Obligatorisk er med i skissene jeg tok utgangspunkt i, vil du ta de bort? Er det ikke fint å ha den markeringen med også for en lesebruker? F.eks en lesebruker har kan jo verifisere at alle obligatoriske felt er godt nok utfylt.

**Comment by sindresandvik2** [comment]
Testet OK i UT1
