### ISSUE TITLE
Feil notasjon av "publisher" i tilgangstyrings rolletoken.

### ISSUE THREAD

**Issue by markkopaas** [Altinn/fdk#2625]
Riktig navn til ressurs er "organization". 

 - [x] generere duplisert token i access token ved som deklarerti user-api (publiser+organisation)
 - [x] migrere alle appen (registration frontend, registration-api, begrep-fe, begrep-api, ...?)
 - [ ] fjerne publisher token fra authorities attribute i access token (etter deploy av de to første)

Den må fikses før vi begynner med "publisering  datasett i min katalog fra en annen virkssomhet"

**Comment by sindresandvik2** [comment]
Testes når  #2632 er ferdig!
