### ISSUE TITLE
Utvide APIet til organization catalogue med støtte for registrering på vegne av andre

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2645]
Lagre egenskapen på de virksomheter som kan registrere på vegne av andre

~- [ ] Lage test for domains~ bør være i separat issue/PR

- [x] Oversette Java tester til Kotlin (Mal fra backend service)

- [x] Støtte for registrering på vegne av andre (boolean flag)

**Comment by sindresandvik2** [comment]
Testes i selve brukerhistorien
