### ISSUE TITLE
Backend: Publisher datasett oppdateres ved registrering på vegne av andre, validering

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2651]
Akkurat nå dataset registrering helt åpent og uten validering det mener at det er allerede nå tillatt å registrere hva som helst. 

- [x] refactor domain service
- [x] validering av registrert dataset (sjekk publisher. no ant?)
- [x] validering av published dataset (har vi noe regler?)

**Comment by sindresandvik2** [comment]
OK i UT1 . De som er assignet til å registrere på vegne av andre får lov, de som IKKE er assignet til å reg på vegne av andre får IKKE lov!
