### ISSUE TITLE
Vis katalognavn ved ulik publisher for datasettbeskrivelse og katalog

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2652]
https://projects.invisionapp.com/share/N9Q9157SD3U#/screens/392950738

- [ ] Sammendragboks

- [ ] Detaljside

**Comment by sindresandvik2** [comment]
Kanskje ikke helt ferdig.   Sjekk de datasettene som GeoNorge har lagt inn.

**Comment by sindresandvik2** [comment]
Virker fint for dei som er blitt registret via GeoNorge.   Vil bli testa ytterligere når egneregistrering fra reg løsningen blir ferdig
