### ISSUE TITLE
NAP-melding vises for tidlig

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2654]
Dersom en velger Offentlig først og så velger et LOS-tema ulikt Transport vises meldingen om  at beskrivelsen vil kun vises i FDK og ikke NAP
![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/c5c9555a-2280-48c4-90f0-c099dd86bd68)

Omvendt rekkeføge, Velg først LOS=Transport og så tilgang = Begrenset kommer samme  melding

**Comment by oyvindis** [comment]
Litt komplisert å få til. Det skal være en sesjonsbasert tilstand som vet om feltene på noe tidspunkt har vært true/true i sesjonen, da skal meldingen om 'avpublisering i NAP' vises.

Estimat: 2,5 dager.

**Comment by lillelars** [comment]
@joebrreg kan vi lukke denne hvis eposet godkjennes ?
