### ISSUE TITLE
Datasettregistrering: Klikkbare inputfelt kan ikke klikkes og har ikke korrekt ikon

### ISSUE THREAD

**Issue by skobba** [Altinn/fdk#2663]
Registrering

Inputfelt: Man må klikke helt til venstre i inputfeltet for å kunne skrive. Hele feltet skal være editerbart. 
Gjelder for Datasett: 
* Begrep -> mangler cursor + går ikke ann å klikke til venstre
* Geografisk avgrensning, Søkeord -> mangler cursor

**Comment by lillelars** [comment]
Dette fungerer nå som ønsket. Testet i chrome i it1

**Comment by lillelars** [comment]
Fungerer nå som det skal i chrome. testet i demo
