### ISSUE TITLE
Begrep-detaljside: Mindre skrift for "Kilde"-feltet

### ISSUE THREAD

**Issue by skobba** [Altinn/fdk#2664]
Mindre skrift og margin/padding på begreps-detaljside (gjelder kilde og ansvarlig) se design.
Design:  https://projects.invisionapp.com/share/3SRCN149CQN#/screens/387607014

vs slik det er i dag:
![image](https://user-images.githubusercontent.com/39513382/72323652-819acc00-36a9-11ea-8990-91cbc9c26818.png)

**Comment by lillelars** [comment]
Håndteres i egen designsak
