### ISSUE TITLE
Log-out fra begrepskatalog tar bruker til feil sted

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2671]
Relatert til #2694 

Bruker havner nå inn i SSO (evnt  ID-porten ved skrivebruker), i stedet for tilbake til:
https://registrering.ut1.fellesdatakatalog.brreg.no/loggedOut

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/8b14d91f-cc33-479e-
812f-15bf28369711)

-->

 ![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/9447cac7-80d5-4ad8-8562-961124f6b046)

**Comment by markkopaas** [comment]
duplikat av #2694

**Comment by lillelars** [comment]
@markkopaas  Er vel ikke en duplikat av:
duplikat av #2694... ? Men om det blir løst i #2694 så er det greit for meg.
Denne saken gjelder både for Lesebruker og for skrivebruker.

**Comment by markkopaas** [comment]
Ja vi kan holde det åpent så vi kan teste

**Comment by sindresandvik2** [comment]
ok i UT1
