### ISSUE TITLE
Endre logo i Demo-miljø

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2674]
Vi ønsker å vise tydeligere at bruker er i demo-miljø.
Første steg for dette er å endre logoen.

https://www.dropbox.com/sh/7aw9r5rfbdgceei/AAD9EUC9S557hJfAYi9BMtjAa?dl=0

**Comment by sindresandvik2** [comment]
Retestet OK i Demo  og forsåvidt i IT1 og UT1
