### ISSUE TITLE
Lenke-endringer for NAP-leveranse

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2689]
- [ ] Hvis vi står i BRREG Transportportal og klikker på logo/symbolet så havner vi hos Transportportal.no (CMS) https://transportportal.atlas.vegvesen.no/no/

- [ ] Hvis vi klikker på «Om transportportal.no» hos BRREG havner vi direkte på «om portalen» i CMS: https://transportportal.atlas.vegvesen.no/about/

Detaljer link må vi komme tilbake til når det legges ut i Atlas.

**Comment by oyvindis** [comment]
Design review er gjort med Lene

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
