### ISSUE TITLE
Temaendringer i forbindelse med LOS 3.0

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2690]
Vi har lagt inn alle våre LOS emner i https://docs.google.com/spreadsheets/d/1llKIldetOMDRBqC5XlgE3mQqzU2OefoKxxQttzMa6rU/edit?usp=sharing.

Her er det LOS kategoriene: «mobilitetstilbud», «veg og vegregulering»,«trafikkinformasjon» og "Yrkestransport" som tilknyttes transportportal.no. med de emneord som hører til dem (se excel doc over).

**Comment by sindresandvik2** [comment]
Testet ok i UT1
