### ISSUE TITLE
Endringer i design for NAP - Viktig

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2691]
Nytt design: https://projects.invisionapp.com/share/8WTQMR2A35G#/screens/393903146_TRAFIKK-S-K-Default--D-

Vegvesen grønn
Pantone U/C: 361 U / 361 C
C: 70 M: 0 Y: 100 K: 0
R: 93 G: 184 B: 46
HEX: #58b02c
HSL: 100, 60%, 45%
RAL: 6018
NCS: S 2060-G30Y

Vegvesen Blå: Pantone U/C: Process Blue U / C
C: 100 M: 15 Y: 15 K: 0
R: 0 G: 142 B: 194
HEX: #008ec2
HSL: 196, 100%, 38%
RAL: 5012
NCS: S 2050-R90B

Vegvesen Lysegrå:
#f2f2f2

- [x] Logo fjernes, blir ny tittel m/ny farge

![image](https://user-images.githubusercontent.com/39513382/69130998-d529d880-0ab1-11ea-96cd-1fbfa4a4f45e.png)

- [x] Endre header til blå/grå bakgrunn med hvit skrift
Farge bakgrunn: #444f55
Farge skrift: #ffffff
![image](https://user-images.githubusercontent.com/39513382/69143891-5c834600-0aca-11ea-8077-07ad8df92480.png)

- [x] Endre til "Om Transportportal.no"
![image](https://user-images.githubusercontent.com/39513382/69131046-f2f73d80-0ab1-11ea-8d42-f1db6677eb67.png)

- [x] Endre til "Registrere data"
![image](https://user-images.githubusercontent.com/39513382/69131092-0c988500-0ab2-11ea-9207-9332f212b788.png)

- [x] Ny blåfarge på knapp:
Vegvesen Blå: Pantone U/C: Process Blue U / C
C: 100 M: 15 Y: 15 K: 0
R: 0 G: 142 B: 194
HEX: #008ec2
HSL: 196, 100%, 38%
RAL: 5012
NCS: S 2050-R90B
![image](https://user-images.githubusercontent.com/39513382/69131142-26d26300-0ab2-11ea-90b3-71e807231d6b.png)

- [x] Bakgrunnsfarge endres til lysegrå, og vi endrer til FDK-tema, med nye farger
Vegvesen Lysegrå:
#f2f2f2

![image](https://user-images.githubusercontent.com/39513382/69131346-86c90980-0ab2-11ea-9361-054fcc99df73.png)

- [x] Endre farge på datasett-detaljside datasettbeskrivelseikon:

![image](https://user-images.githubusercontent.com/39513382/69143348-08c42d00-0ac9-11ea-9ce1-186d318b7e70.png)

- [x] Legge til "Søk blant XXX datasettbeskrivelser" slik vi har i FDK
![image](https://user-images.githubusercontent.com/39513382/69143767-0f9f6f80-0aca-11ea-81b5-58a1c87c1764.png)

- [x] ENDRE ikon + navn fra fane/tab
![image](https://user-images.githubusercontent.com/39513382/69144495-b59fa980-0acb-11ea-8283-c892dde6cce0.png)

NYTT IKON LIGGER HER:
https://www.dropbox.com/sh/vuokjwmrz3m0vkz/AAD7yd9XbqCFPp1w8QNOavjya?dl=0

**Comment by lillelars** [comment]
NB! Husk å få ny svg logo fra @frode-kleven

**Comment by sindresandvik2** [comment]
ok I ut1
