### ISSUE TITLE
Endre i sertifikat hos brreg 

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2692]
- [x] Vi må endre sertifikatet i prod hos oss slik at vi godkjenner at denne url'en peker mot vår IP:
https://data.transportportal.no

**Comment by valosnah** [comment]
https://confluence.brreg.no/display/INFFOR/Oppdatere+SSL-sertifikater

Det ser ut som jeg trenger superadmin, dvs jeg trenger hjelp av Stig for å gjøre dette.

**Comment by lillelars** [comment]
venter på svar fra Steinar Kjærnsrød angående sertifikat-fil fra SVV

**Comment by valosnah** [comment]
Vi har mottatt svar fra Steinar, ser ut som dette legges på is inntil videre. Hittil har jeg kun satt opp ruting i demo-ingressen, og endret hvilken side som får nap-theme. Skal endre dette tilbake slik det var. (dvs at nap.fellesdatakatalog vises med riktig theme)

**Comment by valosnah** [comment]
Sertifikat lagt i bestilling hos Statens Vegvesen, ETA: etter jul

**Comment by valosnah** [comment]
Sertifikat mottatt og lagt inn, data.transportportal.no er gyldig og peker til riktig applikasjon. Noen små issues med transportportal-skin, som følges opp i #2959

**Comment by valosnah** [comment]
Kjent issue hvis man bruker Firefox: Når du besøker data.transportportal.no for første gang, uten å noensinne ha besøkt transportportal.no, regnes ikke sertifikatet som gyldig.
Dette er utelukkende et problem på firefox, og kan omgås ved å besøke transportportal.no først, som er regnet som typisk bruksmønster.
Det er mulig vi mangler et intermediate/rotsertifikat i GCP.
