### ISSUE TITLE
Innloggingsproblemer med Lesebruker Begrep

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2694]
Følgende prosess feiler:
1. Logger inn i registreringsløsningen med eksisterende lesebruker
2. Går inn på begrepskatalogen.
3. Fra begrepskatalogen: kjør logg ut!
4. Da dukker påloggingsbildet "ID porten "MOCK opp.  ![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/7b75a726-fca1-4554-9536-909a26103eed)
5. Ny pålogging med den samme lesebrukeren feiler nå og gir beskjed om Feil username/password

**Comment by markkopaas** [comment]
Problemet er litt relatert til hva vi hadde med logout fra registrerinengs-side. Da var problemet, at på logout, var begrepregistrerings-klienten fortsett i logged-in state. 

Nå ønsker vi at
 -  alle registreringsløsningenge (to nå, men det blir mer) behover seg, som en system - så at når man logger seg ut  fra begrepsregistrering, havner man igjen i hoved-login side, som ligger i den hoved-registrering-shell.
 - hvis man logger seg ut i begrepsystem, må også sesjon i registreringssession ble terminert.

Løsning

- [ ] i begrepsregistrering, implementere en afterlogout path som gjør redirect til registrering. (eller alternativ løsning er å legge registreringsløsning som tillatt redirecturi)
- [ ] fjerne token lagring i registreringsløsning
- [ ] implementere deep linking (fordi vi fjernet token-lagring, blir det umulig å refreshe nettside)
  
estimat: 2 dag

**Comment by sindresandvik2** [comment]
Problem med registrering av NY lesebruker.  Får generell feilmelding
