### ISSUE TITLE
Data-registrering: endre tekst for transportportal

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2699]
- [ ] Endre tekst til: Datasettbeskrivelsen vil være tilgjengelig i Felles datakatalog etter publisering.

![image](https://user-images.githubusercontent.com/39513382/69142108-65721880-0ac6-11ea-8de3-24b717a46652.png)

- [ ] Endre tekst til Transportportal.no
![image](https://user-images.githubusercontent.com/39513382/69141971-1f1cb980-0ac6-11ea-9940-fc1b7ce0dd18.png)

**Comment by sindresandvik2** [comment]
Fantastisk bra Lars.
