### ISSUE TITLE
Visning av EU-tema lager blanke felt når tema ikke eksiterer

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2700]
Symptom: 
![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/c81d0e43-5ab5-4ed8-bbad-d9faeb1a3a98)

Hovedkilden til problemet ser ut til å vere at datasett fra Kartverket (og andre) refererer til tema fra kodelister i Kartverket. : https://register.geonorge.no/subregister/metadata-kodelister/kartverket/nasjonal-temainndeling/kartverket/plan"

Løsningsforslag: når tema som ikke eksisterer eller som ikke kan vises listes opp i under theme skal disse ikke generere tomme områder i tema.visningen.

**Comment by lillelars** [comment]
Dette er nå også i UT1... Så vi må se på og fikse dette:
![image](https://user-images.githubusercontent.com/39513382/69551321-c903b680-0f9c-11ea-8790-026221e75cf8.png)

**Comment by sindresandvik2** [comment]
FIkset i UT1
