### ISSUE TITLE
Refactor registration-api til nye repoer

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2702]
- [x] Legg registration-api inn i dataset-catalogue repo og slett api-controller (6h)

- [ ] Legg registration-api inn i api-catalogue repo og slett datasett-controller (6h)

- [ ] Fjern registration-api fra fdk (2h)

- [ ] deploy dataset-catalougue, api-catalogue  (1h)

Tot: 2,5d

**Comment by sindresandvik2** [comment]
Retestet av Lars og Sindre. Både nyregistrerte datasett og APi samt endringer.  Avpublisering med publisering er også testa.    Alt med Suksess
