### ISSUE TITLE
Mulighet for å motta varsling (RSS/ATOM)

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2708]
All backend for denne oppgaven ligger her (finnes allerede i ut1):
https://github.com/Informasjonsforvaltning/fdk/pull/2678 
og 
https://github.com/Informasjonsforvaltning/fdk/pull/2686

Det som gjenstår er:

- [ ] Legg til RSS / ATOM icon nederst på siden
SE EKSEMPEL HER:
https://data.norge.no/organisasjoner/harstad-kommune
![image](https://user-images.githubusercontent.com/39513382/69323110-5f0aaa80-0c46-11ea-820b-a982bb30f23c.png)

- [ ] Legg til mulighet for dynamisk lenke basert på filter-valg og søk

Hentet fra behov: 
https://github.com/Informasjonsforvaltning/behov/issues/162

Som: bruker av den nasjonale dataportalen
Ønsker jeg å: motta varslinger (feks ved hjelp av RSS/ATOM eller annet)
Slik at: jeg kan få vite når det har kommet et nytt datasett knyttet til et tema, fra en virksomhet, eller basert på et annet filter

Relatert til epos: #91 #346
Funksjonaliteten er etterspurt i EDP Open data Landscaping Questionaire. Finnes delvis på data.norge.no i dag

Enkleste design er at det for hver side er en egen RSS-link-knapp - f.eks. i footer, som gir RSS feed for det aktuelle filteret. Minimum-filtrering er tema (for å skille transporportal fra andre), men løsningen bør være generell uavhengig av hva man har valgt å filtrere på.

Eksempel på side som har en RSS-knapp for datasett pr organisasjon:
https://data.norge.no/organisasjoner/harstad-kommune

Relatert til brukerhistorie #179 (samme trigger, annen målgruppe)

Lenke til design: https://invis.io/N9Q9157SD3U#/355699912_DATA-PORTAL-S-K-Default--D-
Lenke til løsningsarkitektur:

**Comment by sindresandvik2** [comment]
RSS oppdatert korrekt fra UT1
