### ISSUE TITLE
Datasett-registrering, LOS-tema: Oppdatere lede-tekst og design

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2740]
I dagens løsning har vi ingen ledetekst og vi har feil design.
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/c90e3669-adba-43a8-b3c5-8df1844fca88)

Se designskisser for hvordan det skal være:
https://projects.invisionapp.com/share/N9Q9157SD3U#/screens/356240494

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
