### ISSUE TITLE
Alle felter vises som labels/tekst

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2748]
NB! Husk å ta med "registrere på vegne av andre" også

**Comment by skobba** [comment]
Etter gjennomgang med Lars:
[x] Tekst skal være lik som concept-catalog.
[x] Lite Obligatorisk badge skal midtstilles.
[x] URLer skal flyttes litt til høyre.
[x] Tilgangsnivå må få tilbake helptext.
[x] Begrep og Søkeord språk badge må midtstilles.
[x] Obligatorisk badge på "Formålet med datasettet" og "Tilgangsnivå" og "Tema og emner"
[x] EU tema warning skal vises for readonly bruker.
[x] ReadOnlyField indent til høyre (Geografi, tid og språk + Eksempeldata)
[x] console errors
[x] eslint errors
[x] "Lenke" tittel (Tilgangsnivå, Informasjonsmodell, Distribusjoner) + et lite mellomrom
[] Kontakinformasjon (epost og telefon layout)
[] API-distribusjoner (må også vise api beskrivelser av andre)
[x] Distribusjon - fjerne slett/leggtil-knapper

**Comment by sindresandvik2** [comment]
Testet OK  i UT1.  Lene bør ta ein runde......
