### ISSUE TITLE
Endre ikon ved tittel så det reflekterer korrekt status på datasettbeskrivelse

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2754]
Se design:
https://projects.invisionapp.com/share/N9Q9157SD3U#/screens/343911177

![image](https://user-images.githubusercontent.com/39513382/70120138-1dc5c200-166c-11ea-876a-9f8795c9fd08.png)

Lenke til ikoner:
https://www.dropbox.com/sh/pi3534heqcbem90/AAB9SRYNJLhI_QFX_FYcckiBa/Icons?dl=0&subfolder_nav_tracking=1

**Comment by oyvindis** [comment]
Tittel ser det ikke ut som vi lenger har, vi må legge den også til.

Finner designskisse her, den er ikke lik den som er lenket øverst på denne saken:
https://projects.invisionapp.com/share/N9Q9157SD3U#/screens/392127787

@eggedosis hvilken skal vi bruke?

**Comment by LeneSundsbo** [comment]
@oyvindis Det er den nye skissen som gjelder (altså den i InVision). Forskjellen fra gammel til ny skisse er at vi har fått en ny seksjon øverst (_registrer på vegne av andre_). Tittel er dermed dyttet ned som seksjon 2.

**Comment by lillelars** [comment]
tested ok i ut1
