### ISSUE TITLE
Legge til statusbar med ny status godkjent

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2757]
- [x] Kan publisere uten å fylle ut obligatoriske felt

- [x] Når status er "Godkjent" og bruker gjør endringer står det "endringene er publisert"

- [ ] ved endring av datasettbeskrivelsen må jeg trykke to ganger for å endre status (bør vel holde å trykke 1 gang :) )

- [x] Ønsker at det skal stå "Sist oppdatert *timestamp* uavhengig av status (se Begreps-status-bar)

**Comment by oyvindis** [comment]
'ved endring av datasettbeskrivelsen må jeg trykke to ganger for å endre status': skjer pga. lagring ved onBlur fra et input-felt, det suppress alle andre actions. Dvs. er ikke isolert til statusbar.

**Comment by lillelars** [comment]
testet ok i ut1.
@oyvindis håndterer buggen i egen issue
