### ISSUE TITLE
Implementer CRUD-funksjonalitet for behandlingsaktiviteter

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2758]
- [x] Opprett specc

- [x] Kopiere fdk-harvest-admin løsning (ta bort rabbitmq og triggerHarvest endpoint)

- [x] Oppdatere modell ihht. specc

- [x] Erstatte PUT med PATCH

- [x] Sette opp GitHub actions og deploy

**Comment by sindresandvik2** [comment]
Blir testa gjennom Frontend senere
