### ISSUE TITLE
Data-Reg: Endre logikk for håndtere meldingen for hvor datasettbeskrivelsen publiseres

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2762]
**### NYE KRITERIER FOR Å PUBLISERE UT I TRANSPORTPORTAL.NO**:

Dersom enten en av underkategoriene ELLER et av emneordene under en av underkategoriene er valgt er kriteriet for tema mot transportportal oppfylt. Det betyr at dersom datasettbeskrivelsen også har "Offentlig" tilgangsnivå er valgt skal melding vises.

Alle underkategoriene ligger under hovedkategori: Trafikk og Transport
**Underkategorier som oppfyller tema-kriteriet:**
Mobilitetstilbud
Trafikkinformasjon
Veg og vegregulering
Yrkestransport

Med nye LOS 3.0 temaer/emner må også meldingen for når det går ut i Transportportal.no endres basert på dette. Det er snakk om disse to meldingene:
![image](https://user-images.githubusercontent.com/39513382/69629859-c9f42100-104c-11ea-993e-b585feb40273.png)

![image](https://user-images.githubusercontent.com/39513382/69630007-e42dff00-104c-11ea-8fa8-2eb397a11210.png)

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
