### ISSUE TITLE
Lag et script for migrering fra LOS2.0 til LOS3.0

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2773]
Tar utgangspunkt i Øystein sitt arbeid:
https://docs.google.com/spreadsheets/d/1_Kmaofy4JHBD3OqIfoJ9zCbVXeRStS8aUtK_klN7Bj0/edit

Lage et script og kjør dette i prod (etter man har snakket med en voksen)

**Comment by markkopaas** [comment]
@sindresandvik2  Jeg foreslår å gjøre den sript som Spring startup script. Det mener at skripten bli kjørt i protsetting-tid.  Og det mener at alt som har vært kommittet i mellomtid (estimert som opp til litt senere i dag), skal også bli med. Erd det mulig å regressionteste det?

**Comment by sindresandvik2** [comment]
OK i UT1, IT1 og i PROD!
