### ISSUE TITLE
Endre "Kom i gang med registrering"

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2774]
NB! Det holder å gjøre dette på bokmål.

Legg til teksten:

"Det er også mulig at din virksomhet kan få registrere på vegne av andre. Dersom du ønsker dette, må du kontakte FDK på: fellesdatakatalog@brreg.no. "

på ny linje her:
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/062db1f7-67b9-4d71-a3fc-f8eb79785931)

**Comment by sindresandvik2** [comment]
ok i UT1
