### ISSUE TITLE
Høsting av begrep: Kilde kommer ikke med

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2778]
Med testet registrert begrep: "Perestrojka" av Ramsund og Rognan

Det ser ut som begrepsregistreringen dytter ut riktig felt, men at det ikke blir plukket opp av harvestern eller portal:
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/8fca08a5-3375-4b74-b684-9047b60503eb)

Etter registrert begrep "Perestrojka" blir ikke feltet "kilde" med videre... det er tomt i søkeløsning.
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/4ac92559-4721-46a0-b7ea-7cbba22e5817)

**Comment by sindresandvik2** [comment]
Testet OK i UT1
