### ISSUE TITLE
"Sist oppdatert"-banner dekker til footer

### ISSUE THREAD

**Issue by akhvidsten** [Altinn/fdk#2781]
Når jeg skal endre et begrep i begrepsregistreringsløsningen, dekker "sist oppdatert"-banneret nederst på siden til informasjonen under. Se vedlegg.

![Skjermbilde](https://user-images.githubusercontent.com/46559179/69787414-ca132e80-11bc-11ea-9a78-d6b68dd06e16.PNG)

**Comment by stigbd** [comment]
Antageligvis forsøker du å endre et begrep som allereie er publisert. Sidan det ifølge standarden ikkje er lov å endre på publiserte begreper, er det ingen publiser/lagre knapp.

Dersom du går inn på et begrep som er i utkast, vil du sjå at publiser-knappen ligger _i_ banner.

**Comment by lillelars** [comment]
Se bort i fra Stig sin kommentar over.. Skal ikke vise statusbar annet enn "sist oppdatert" på begreper som er publisert. Det at statusbaren dekker over footeren er notert, men blir dessverre ikke prioritert å gjøre noe med fremover.
