### ISSUE TITLE
RSS og ATOM for NAP plukker ut for mange datasett i Transportportal

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2782]
Se: 
https://nap.fellesdatakatalog.brreg.no/

RSS og ATOM lenkene når vi er i Transportportal.no (NAP)-filter, så tar den for øyeblikket med alle datasett. Her må vi altså legge på samme filter som allerede gjøres default for denne siden.

Altså: 
Tilgang = offentlig
OG 

Tema = 
(
Mobilitetstilbud
Trafikkinformasjon
Veg og vegregulering
Yrkestransport
)
ELLER et emneord under en av disse temaene.

**Comment by sindresandvik2** [comment]
NAP RSS er nå identisk med NAP i søkeportal i UT1
