### ISSUE TITLE
Oppdatering av begrep registreres ikke

### ISSUE THREAD

**Issue by akhvidsten** [Altinn/fdk#2784]
Legger til "DPE" under tillatt term for begrepet "Digital post til eInnsyn". Endringen lagres ikke og er borte neste gang jeg logger inn i registreringsløsningen. Lurer på om lagre/publiser-knappen er skjult av banneret, som forklart i en separat issue jeg rapporterte i stad.

**Comment by stigbd** [comment]
Duplikat av #2781
