### ISSUE TITLE
Høsting av Begrep fra vår registreringsløsning til UT1 fungerer ikke

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2793]
Gjenskap:

1) Logget inn som Michelle Westlie og endrer begrepet "Grenseovergangssted"
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/c0be0431-ec8b-4513-9b47-bacc2f7f5642)

2) Ser i Collections at Begrepet er korrekt fra registreringsløsningen:
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/ccf87631-6b62-4fdc-90ac-48effaf6899d)

3) Endringen har ikke skjedd i søkeportal:
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/bb66a443-0583-4ee1-9254-c4b5ca9e6e76) 

4) Verifiserer at høsteendepunktet ligger i admin-løsningen vår. Forsøker å trigge harvest manuelt.
![image](https://user-images.githubusercontent.com/39513382/69867488-38ccb680-12a7-11ea-929d-e0f732ca933f.png)

... Fortsatt ingen endring i portal.

NB! Forsøkte også å trigge høsting av eksternt endepunkt. Det fungerer som normalt.

**Comment by stigbd** [comment]
Feilen ligger trolig i fdk-concept-harvester når den høster begrepet. Har trulig noko med id/identifier å gjere. Disse samsvarer ikke. Ref skjermdump:
![image](https://user-images.githubusercontent.com/1702357/69872374-87814d00-12b5-11ea-821a-5a7514ee7f88.png)
Sjekk også commit https://github.com/Informasjonsforvaltning/fdk-concept-harvester/commit/c6ad87a09737a7707b48b45887d140fb5d53686b

**Comment by stigbd** [comment]
Hypotese: Oppstår når begrepet publiseres, avpubliseres og publiseres på nytt.

**Comment by stigbd** [comment]
@azaxarov Kan du forsøke å gjenskap denne på localhost med lokal elasticsearch? Og gjerne skrive ein test som lager feilen.

**Comment by lillelars** [comment]
Setter denne on hold til vi ser det er et problem igjen... har brukt nok tid inntil videre

**Comment by azaxarov** [comment]
@stigbd @lillelars 

Jeg klarte å gjenskape og fikse denne issue.

Det finnes flere årasaker som gjorde at vi hadde denne issue.
1) URI som vi oppgir i Admin GUI bør ha publisher query parameter, som begrenser begreper for en gitt publisher. Hvis ikke parameteren er satt, høstes alle begreper for alle organisasjoner fra collections endepunkt.
2) FDK Concept Harvester forsøkte å detektere om begrepet har allerede vært høstet tidligere ved å slå den opp i Elasticsearch. Problemet er at allerede høstede begreper ble aldri funnet på grunn av at oppslag basert på URI funker veldig dårlig i Elasticsearch. Derfor ble begreper (f.eks "appelsinjus" høstet lik antall ganger som antall av data sources som har våre collections endepunkter.

Selv om problemet er stort sett løst, gjenstår det forstatt en liten sak til. Nemlig at hver gang vi høster våre collections endepunkter, vil alle allerede høstede begreper være oppdatert. Det kan løses ved å innføre filter for akutelle organisajoner som skal høstes.

**Comment by sindresandvik2** [comment]
testet OK i UT1
