### ISSUE TITLE
Søkeord vises feil i frontend uavhengig av språk

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2796]
Frontend tolker felt for søkeord feil. Skal tolkes ift systemspråk.
Title vises korrekt.

![image](https://user-images.githubusercontent.com/39513382/69869427-205f9a80-12ad-11ea-9047-c4491c72e4db.png)

Meldt inn fra Entur v/ Johan Wiklund;

Listen med søkeord som vises til publikum viser søkeordene fra alle språk. Det ser litt forunderlig ut 😊
  
![søkeord.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/8e693ddc-11b0-4baf-87e7-2ab2f90ea883)!

[søkeord2.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/d17360ce-bd5c-4817-be3f-6d4790ed0bfb)

**Comment by sindresandvik2** [comment]
Retestet ok  i UT1
