### ISSUE TITLE
Initiell oppgave for behandlingsaktiviteter

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2797]
- [ ] kobling fra registreringsløsning til egen løsning (katalog-inngangsknapp)

- [ ] Oppsett skjellett for registrering av behandlingsaktiviteter

Se også design:
https://projects.invisionapp.com/share/APUPOL4B4G7#/screens/395260963

Lenke til svg ikon for katalog:
https://www.dropbox.com/s/scfo6ckdzb4xhwt/icon-catalog-protocol-xl.svg?dl=0

**Comment by sindresandvik2** [comment]
OK i regløysing.  Knapp eksisterer (via feature toggle)  Blir uansett testa skikkelig når liste dukker opp!
