### ISSUE TITLE
Registreringsløsning, pålogging: Ved to klikk tilbake i browser får bruker dette bildet

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2819]
Gjenskaper:
1) bruker logger seg på i registreringsløsning (gjelder både skrive og lesebruker)
2) bruker klikker "tilbake" i browser to ganger
3) bruker får da dette bildet:

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/7b9f78e3-84f9-42d6-9e1c-89bc252839d1)

low pri

**Comment by sindresandvik2** [comment]
Retestet OK i UT1
