### ISSUE TITLE
Migrate fellesnginx (ut1/demo) to GitHub Actions

### ISSUE THREAD

**Issue by stigbd** [Altinn/fdk#2875]

**Comment by valosnah** [comment]
Det har blitt foreslått å droppe denne i den nye skyen, og heller bruke it1/prod-ingressen for demo også.

**Comment by valosnah** [comment]
Denne kan lukkes, da vi har bestemt oss for å droppe fellesnginx, og heller bruke ingressen for alle tre miljø i digdir (staging/demo/prod).
Behovet for fellesnginx skyldtes passordbeskyttelsen i ut1, som ikke tas med videre til digdir.
