### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by stigbd** [Altinn/fdk#2876]
This epic keeps track of all the activities that need to completed to migrate from Jenkins to GitHub Actions for CI/CD. The ultimate test is that all our services are deployable after we turn off our Jenkins instance.
Please keep track of progress in the following sheet:
https://docs.google.com/spreadsheets/d/1XEgVck1GPqHUxE5PMkoRDqJQhHU0tR3AarzcJfFDRcg/edit#gid=0

- [x] Test Design er OK.. Avklart med Han Olav at her er utprøving og bruk av funksjonene test god nok!

**Comment by lillelars** [comment]
All migrering ferdigstilt.
