### ISSUE TITLE
NAP: Feil tekst i brødsmulesti

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2878]
For: https://nap.fellesdatakatalog.brreg.no/

Her bør det stå:
"Søk i Transportportal.no"

Nå viser vi til fellesdatakatalog
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/219eca20-b8d7-4fd3-a053-62c5e7ff67df)

**Comment by sindresandvik2** [comment]
Tekstendringen var ikke på plass i UT1

**Comment by lillelars** [comment]
testet ok iut1
