### ISSUE TITLE
Datasettregistrering: Tittel på distribusjon mangler

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2887]
Vi må legge til støtte for å registrere tittel på hver enkelt distribusjon.

Må sjekke om dette ligger i modellen også.

Registreirng:
![image](https://user-images.githubusercontent.com/39513382/70323103-37156c80-182c-11ea-94bc-52da4cf0d8c1.png)

NB!
Dette må vises i portal også:
![image](https://user-images.githubusercontent.com/39513382/70323057-1a793480-182c-11ea-920f-c21d7900e3a7.png)

**Comment by oyvindis** [comment]
Tittel er støttet i dcat: https://doc.difi.no/dcat-ap-no/#distribusjon-tittel

**Comment by lillelars** [comment]
fungerer i registrering, men må også vises i portal:
![image](https://user-images.githubusercontent.com/39513382/73245263-1c1c0480-41ac-11ea-97fd-51aa9c08d8a2.png)

**Comment by lillelars** [comment]
Finner den forsåvidt her, så den blir høstet... så da er det bare frontendvisningen som gjenstår:
![image](https://user-images.githubusercontent.com/39513382/73245333-4968b280-41ac-11ea-9cff-ab8219609e28.png)

**Comment by lillelars** [comment]
Fungerer som det skal i demo.
