### ISSUE TITLE
Søkeportalen:  Sortering på sist publisert feiler

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2891]
Når en velger Sortering på sist publiserte for begrep forsvinner data i visningen: 
![image.png](https://images.zenhubusercontent.com/5c5d4c79df0733a3055604a6/07142b76-9ee5-42c6-b591-2b4b61fbe2b5)

Eksempel på begrep som feiler: https://fellesdatakatalog.brreg.no/api/concepts/75ed5aa2-9735-48f3-a71c-397f12abe427

**Comment by joachim-me** [comment]
Feilen er at når det høstes fra en dcat datasource, så høster vi tomme begrep. Blir fikset med #2832

**Comment by lillelars** [comment]
@joebrreg jeg klarer ikke gjenskape dette nå... Er dette fortsatt en issue?

**Comment by lillelars** [comment]
lukke denne ettersom det ikke vil være t problem lenger.
