### ISSUE TITLE
Støtte markdown på lenker i kildefeltet til begrepskatalogen ved høsting fra virksomhetene

### ISSUE THREAD

**Issue by marittor** [Altinn/fdk#2895]
Ønsker støtte for markdown på lenker i kildefeltet, også ved høsting av begrepsbeskrivelser fra virksomhetene. Det er støtte før dette idag for det som kommer ut i portal gjennom registreringsløsningen for begrep, men ser ikke ut til å være det for det som kommer inn via høsting.. 

Se eksempel på hvordan kildefeltet til begreper som kommer fra registreringsløsningen ser ut: https://fellesdatakatalog.brreg.no/concepts/0d0ec0b9-abb4-4344-8a31-d1e8fe673043 

Kan vi få det som høstes til også å se slik ut? 

Forretningsverdi: Mindre viktig

**Comment by stigbd** [comment]
Issue moved to [Informasjonsforvaltning/fdk-concept-harvester #17](https://github.com/Informasjonsforvaltning/fdk-concept-harvester/issues/17) via [**ZenHub**](https://www.zenhub.com/)
