### ISSUE TITLE
Duplikater av publiserte begrep

### ISSUE THREAD

**Issue by hanber** [Altinn/fdk#2900]
Hei!
Det ser ut som alle begrep publisert av Arkivverket er blitt duplisert. Det skal være 25 begrep, men det vises 50 både i filteret i venstre kolonne og i søkeresultatet. De er ikke duplisert i registreringsløsningen. Begrepene har forskjellig identifikator.

Her er en skjermdump av en side i søkeløsningen:

![image](https://user-images.githubusercontent.com/1415536/70539217-a8725980-1b63-11ea-951b-e2dfca779361.png)

Vennlig hilsen
Hans Fredrik

**Comment by frodegill** [comment]
@hanber Nå skal duplikater være borte
