### ISSUE TITLE
Datasettregistrering lesebruker: Detaljbildet for datasett som ikke er publisert vises ikke

### ISSUE THREAD

**Issue by sindresandvik2** [Altinn/fdk#2951]
Følgende sekvens feiler: 
1. Logg inn som lesebruker
2. Gå inn på datasettkatalogenfor en virksomhet, alle datasett med alle typer status vises
3. Velg et datasett med status Utkast eller Godkjent som ikke har alle obligatoriske felt fylt ut
4. Klikk for å åpne valgt datasett og detaljbildet dukker ikke opp!

**Comment by lillelars** [comment]
Testet OK i ut1
