### ISSUE TITLE
data.transportportal.no benytter feil tema-skin

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2959]
Search må støtte at NAP_HOST-variabelen er en liste, slik at vi kan legge inn flere verdier.
I tillegg må koden for favicon endres slik at ikke bare nap.*-sider får transportportal-ikonet.

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/a0bb0cb6-5474-4f2a-a5f8-36c82b4e71b1)

**Comment by valosnah** [comment]
Har lagt inn data.transportportal.no i NAP_HOST-variabelen nå, slik at riktig tema-skin vises. Inntil NAP_HOST kan være en liste, medfører det at nap.fellesdatakatalog.brreg.no har standard-skin.

**Comment by lillelars** [comment]
testet OK
