### ISSUE TITLE
Pålogget som lesebruker må Protokoll-katalog gråes ut

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2965]
![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/3c86b436-5016-4221-a7d7-da1bd70005ec)

**Comment by oyvindis** [comment]
Lesebruker får 'Access denied' når gjør request til /records (protokoll)

**Comment by lillelars** [comment]
Testet OK i ut1. Trenger bare code review før den kan closes og prodsettes.
