### ISSUE TITLE
Rapporten mangler info fra behandlingsaktivitetene

### ISSUE THREAD

**Issue by joachim-me** [Altinn/fdk#2968]
Det ser ut som det er bare to felt som kommer med: tittel og daglig behandlingsansvar

I tillegg ser det ut til at tre ja/nei-felt får verdien "nei" uavhengig av hva man registrerer.

**Comment by oyvindis** [comment]
Det mangler foreløpig data for en Record fra endepunktet '/api/organizations/{organizationId}/records', bortsett fra et par felt som er med.

**Comment by lillelars** [comment]
testet ok i demo
