### ISSUE TITLE
Får ikke legge inn noe informasjon i de tre siste kategorine

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2969]
Testet i ut1:

Gjenskaper:
1) Åpne enten "Behandlingsaktiviteter" "Personopplysninger" eller "overføring av personopplysninger" 

2) legg inn noe informasjon

3) Hele hovedkategorien lukker seg......(?!)

1) ![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/278369a8-5999-4637-811c-91af73266cbd)

2) ![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/14581fdf-7677-48a1-b606-c109ea8a77df)

**Comment by azaxarov** [comment]
@lillelars gjelder denne fortsatt? Får ikke gjenskapt det i ut1.

**Comment by lillelars** [comment]
Klarer ikke gjenskape lenger, så lukker denne.

**Comment by lillelars** [comment]
... and it's back :)

**Comment by lillelars** [comment]
Fungerer som det skal igjen
