### ISSUE TITLE
GUI - fix for representant og personvernombud

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#2984]
Dersom bare den ene boksen er ekspandert skal ikke den andre følge størrelsen.
De trenger bare å være like store når begge boksene er kollapset eller begge boksene er ekspandert.

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/1069f5bd-4555-414c-ae40-d86789a78189)

**Comment by azaxarov** [comment]
Revertert tilbake til opprinnelig løsning

**Comment by lillelars** [comment]
Denne er ikke løst, men vi bare bruker ikke mer tid på dette nå..

**Comment by joachim-me** [comment]
Utført
