### ISSUE TITLE
Opprett deployment til DIGDIR-cloud

### ISSUE THREAD

**Issue by valosnah** [Altinn/fdk#2989]
- [x] Legge inn digdir staging,demo og prod yaml-filer i samtlige workflows
- [x] Legge inn secrets for digdir dev og prod i samtlige repos
- [x] Kopiere og konvertere BRREG GCP-secrets, legge inn i DIGDIR-GCP
- [x] Faktisk deploye til DIGDIR-cloud
Koordinere videre med Michael

**Comment by lillelars** [comment]
Vi er nå over på Digdir domene :) lukker denne.
