### ISSUE TITLE
Retting + forbedring av bolken behandlingsansvarlig i protokoll-gui - førsteside

### ISSUE THREAD

**Issue by marittor** [Altinn/fdk#3005]
Det er ikke helt samsvar mellom designskissen som er laget og slik feltene her ser ut i produksjon, se vedlagte bilder. Jeg har gått gjennom dette med PVO i BR og vi tror at det blir forvirrende å kalle begge felter "behandlingsansvarliges representant". Det ene feltet (øverst) vil alltid fylles ut, og feltet under vil sjelden brukes, men er obligatorisk å fylle ut dersom det er akutelt. I tillegg er hjelpetekstene identiske, dette bør også skilles på. 

Vårt forslag: Kall bolken "Behandlingsansvarlig" og første felt/overskrift "behandlingsansvarlig" med følgende hjelpetekst: 
"Behandlingsansvarliges representant er ofte virksomhetens øverste leder. En “behandlingsansvarlig” er en fysisk eller juridisk person, en offentlig myndighet, en institusjon eller ethvert annet organ som alene eller sammen med andre bestemmer formålet med behandlingen av personopplysninger og hvilke midler som skal benyttes; når formålet med og midlene for behandlingen er fastsatt i unionsretten eller i medlemsstatenes nasjonale rett, kan den behandlingsansvarlige, eller de særlige kriteriene for utpeking av vedkommende, fastsettes i unionsretten eller i medlemsstatenes nasjonale rett, jfr. Artikkel 4 nr 7." 

Forslag til endring av felt 2 som idag heter "representant for behandlingsansvarlig": Dette bør nok løses på en annen måte - vi ønsker at dette skulle vært et spørsmål: Er behandlingsansvarlige eller databehandlere ikke er etablert i Unionen? JA/NEI. Hvis Ja hukes av, kan feltet med overskrift (som i skissene) "Behandlingsansvarliges representant i EU/EØS" dukke opp, med følgende hjelpetekst:  
"Dersom den behandlingsansvarlige er etablert utenfor EØS-området, skal den utpeke en representant.
En “representant” en fysisk eller juridisk person som er etablert i Unionen, som den behandlingsansvarlige eller databehandleren har utpekt skriftlig i henhold til artikkel 27, og som representerer den behandlingsansvarlige eller databehandleren med hensyn til de forpliktelser de har i henhold til personvernforordningen. Les mer på Datatilsynets nettsider" (med lenke til den faktiske siden: https://www.datatilsynet.no/rettigheter-og-plikter/virksomhetenes-plikter/  - ikke bare til DTs førsteside, dette hjelper lite - Se ellers hjelpetekstdokumentet for direkte lenker).

**Comment by lillelars** [comment]
Dette er ferdigstilt og prodsatt. Testet i chrome og safari. @marittor
