### ISSUE TITLE
Datasett vises flere ganger (gjelder kun datasett fra Statens vegvesen?)

### ISSUE THREAD

**Issue by hildea** [Altinn/fdk#3011]
Mange (alle?) av Statens vegvesen sine datasett har to identiske oppføringer.

https://fellesdatakatalog.brreg.no/?q=sykkel :
Ruteplan for sykkel, høstet fra Dataportalen:
https://fellesdatakatalog.brreg.no/datasets/5f667aca-9c28-4bd6-9be8-6f5257035320
https://fellesdatakatalog.brreg.no/datasets/6ad200ee-135b-43d1-845a-64bfd7e0826a 

https://fellesdatakatalog.brreg.no/?q=vegregulering :
https://fellesdatakatalog.brreg.no/datasets/00422f40-fd78-4858-bbdb-3767582180cf
https://fellesdatakatalog.brreg.no/datasets/962771d5-6b6d-4205-b652-f2a43e8933bf

Dupliseringa gjelder også datasett som ikke er med i transportportal, se f.eks. https://fellesdatakatalog.brreg.no/?q=kj%C3%B8ret%C3%B8y
https://fellesdatakatalog.brreg.no/datasets/1b4d8a57-008a-4988-803a-fde4a024eae5
https://fellesdatakatalog.brreg.no/datasets/ac6f8834-72f0-41e7-baae-d5303cb9bfa4

I transportportalen har vi ikke denne dupliseringa, se f.eks. https://data.transportportal.no/?q=sykkel 

I tillegg ser jeg at innhøstinga av Statens vegvesen datasett fra data.norge.no er satt i gang igjen, se https://fellesdatakatalog.brreg.no/?q=vegvesendata 
(Vi har satt inn setningen "For nyheter, driftsmeldinger og tips om data fra Statens vegvesen, følg oss på twitter.com/VegvesenData." i alle oppføringer på data.norge.no, det har vi ikke med i oppføringene på dataportalen.)

**Comment by valosnah** [comment]
Vi jobber med å slette duplikater nå.
Det er litt uklart for oss hvilke vi skal beholde, og hvilke vi skal slette.
Vi har gjort en liten test for datasettet "Ruteplan for sykkel", som det finnes 3 av.
Av disse tror vi at vi sletter følgende:
Basert på kriteriet at vi beholder de som kommer fra https://prod.nora.links.com.au/catalog.ttl
```
[
    {
        "doc": {
            "id": "fd398a39-ca5e-4e4b-a607-e1bdc19c0781",
            "title": {
                "nb": "Ruteplan for sykkel"
            },
            "catalog": "https://dataut.vegvesen.no"
        }
    },
    {
        "doc": {
            "id": "507f3837-3c86-4d21-a114-e198115ca91d",
            "title": {
                "nb": "Ruteplan for sykkel"
            },
            "catalog": "https://data.norge.no/api/dcat2/971032081/data.jsonld"
        }
    }
]
```
Vennligst bekreft om dette er riktig.

**Comment by hildea** [comment]
Hei!
Ja, det er riktig å beholde de som kommer fra https://prod.nora.links.com.au/catalog.ttl

Hilsen Hilde


Fra: Hans Olav Sund <notifications@github.com>
Sendt: onsdag 12. februar 2020 14:41
Til: Informasjonsforvaltning/fdk <fdk@noreply.github.com>
Kopi: Austlid Hilde <hilde.austlid@vegvesen.no>; Author <author@noreply.github.com>
Emne: Re: [Informasjonsforvaltning/fdk] Datasett vises flere ganger (gjelder kun datasett fra Statens vegvesen?) (#3011)


Vi jobber med å slette duplikater nå.
Det er litt uklart for oss hvilke vi skal beholde, og hvilke vi skal slette.
Vi har gjort en liten test for datasettet "Ruteplan for sykkel", som det finnes 3 av.
Av disse tror vi at vi sletter følgende:
Basert på kriteriet at vi beholder de som kommer fra https://prod.nora.links.com.au/catalog.ttl

[



    {



        "doc": {



            "id": "fd398a39-ca5e-4e4b-a607-e1bdc19c0781",



            "title": {



                "nb": "Ruteplan for sykkel"



            },



            "catalog": "https://dataut.vegvesen.no"



        }



    },



    {



        "doc": {



            "id": "507f3837-3c86-4d21-a114-e198115ca91d",



            "title": {



                "nb": "Ruteplan for sykkel"



            },



            "catalog": "https://data.norge.no/api/dcat2/971032081/data.jsonld"



        }



    }



]



Vennligst bekreft om dette er riktig.

**Comment by valosnah** [comment]
Hei.
Duplikatene fra dataut.vegvesen har nå blitt slettet.

@hildea : Kan du bekrefte at det ser ut som forventet nå?

**Comment by hildea** [comment]
Beklager seint svar! 
Den doble importen fra dataportalen er borte, så den delen ser OK ut.

Men: Det er stadig import både fra Dataportalen vår og fra data.norge.no, se f.eks.:
https://fellesdatakatalog.brreg.no/datasets/6774ec5a-4018-4fec-8b1c-272dd03b823d fra http://data.norge.no/data/statens-vegvesen/ruteplan-sykkel

https://fellesdatakatalog.brreg.no/datasets/6ad200ee-135b-43d1-845a-64bfd7e0826a fra https://prod.nora.links.com.au/dataset/ruteplan-for-sykkel

Da vi startet opp med import fra Dataportalen avtalte vi at dere skulle slå av import fra data.norge.no for våre datasett, det ser ut som den importen har blitt slått på igjen.

**Comment by hildea** [comment]
...og etter litt mer avklaring har jeg fått vite at importen fra data.norge.no alltid har vært der, jeg la bare ikke merke til den tidligere.

Så da er det greit å ha doble oppføringer inntil data.norge.no blir slått sammen med felles datakatalog.
