### ISSUE TITLE
Oppdatering i fdk-admin-gui feiler

### ISSUE THREAD

**Issue by azaxarov** [Altinn/fdk#3013]
Hvis man nvavigerer til data sources og forsøker å editere en data source, så vil PUT kallet feile pga undefined data source ID.

![Capture.PNG](https://images.zenhubusercontent.com/5d402ba1ca7b4e0001322ad3/466f2126-7c1a-40ca-a8d3-d2410f3a3a70)

**Comment by lillelars** [comment]
Testet OK
