### ISSUE TITLE
Viser feil ansvarlig

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#3035]
her skal det stå "Digitaliseringsdirektoratet" og ikke "Direktoratet for forvaltning og ikt".
![image](https://user-images.githubusercontent.com/39513382/75982090-1968a980-5ee6-11ea-92da-5cf4291cb107.png)

Hvis vi slår opp orgnummeret så blir det riktig, så legger vi på noe feil her?

**Comment by valosnah** [comment]
Ser dette må gjøres for samtlige. Har fikset datasett.

**Comment by lillelars** [comment]
Dette fungerer som forventet nå. Lukker derfor denne.
