### ISSUE TITLE
Feilretting: Samme endringsdato vises på alle modeller

### ISSUE THREAD

**Issue by ToHelland** [Altinn/fdk#3045]
Alle modeller i modellkatalogen vises med den samme endringsdatoene. Modeller generert på bakgrunn av høstede json-filer fra SERES eller modeller generert ut fra API-spesifikasjon. Endringsdato (og overskriften status) skal ikke vises for disse modellene, siden det ikke finnes data på dette. Kun modeller høstet i henhold til spesifikasjon for informasjonsmodeller kan ha endringsdato.
<img width="575" alt="Endringsdato" src="https://user-images.githubusercontent.com/17720749/76977989-67de6500-6936-11ea-9771-fd84267e7fe1.png">

**Comment by ToHelland** [comment]
Så litt feil på denne. Person- og enhet-modellen hadde opprinnelig endringsdato 26.02.2016, som vi etterhvert fjernet. Men jeg ser nå at modellene har 26.02.2020:-) Men hva slags dato er dette? Er det datoen da de ble høstet? I så fall blir ikke det riktig. Endringsdatoen er datoen da modellen sist ble endret.

**Comment by azaxarov** [comment]
Dette ble fikset i følgende issue:

https://app.zenhub.com/workspaces/fdk---felles-datakatalog-5c61461c801d5a1030316315/issues/informasjonsforvaltning/fdk/3077

Fikser bare en liten front-end bug med visning.

**Comment by lillelars** [comment]
Testet og godkjent av Tore. Lukker denne.
