### ISSUE TITLE
Oppdatere apiVersion i helm deployment.yaml

### ISSUE THREAD

**Issue by valosnah** [Altinn/fdk#3046]
Samtlige deployment.yaml filer benytter seg av apiversion: extensions/v1beta1
Denne versjonen utgår i neste versjon av K8s, og vi må oppdatere samtlige filer til gjeldende versjon (apps/v1) før clusteret blir oppdatert, som skjer en gang til høsten. I tillegg må selector defineres (deploy med apps/v1 feiler hvis den ikke er definert). Alle andre yaml-filer (storage, service, etc) bruker allerede v1, og er uberørt av oppdateringen.

Har testet oppdatering med hell på a-backend-service helm template.

Info fra Google nedenfor:
We are writing to let you know that upstream Kubernetes open source is removing deprecated APIs in v1.16. Once Google Kubernetes Engine (GKE) upgrades your clusters to v1.16, you will no longer be able to use the deprecated API versions.
What do I need to know?
GKE will gradually upgrade clusters to Kubernetes v1.16:
•	clusters subscribed to the regular release channel will begin upgrades on or after April 9, 2020
•	clusters subscribed to the stable release channel and non-release-channel clusters will be upgraded later this year; a reminder will be sent before these clusters are upgraded to v1.16
For more control over when an auto-upgrade can occur (or must not occur), you can configure maintenance windows and exclusions.
The v1.16 release won’t serve deprecated versions of the following APIs, in favor of newer and more stable API versions:
Deployment versions extensions/v1beta1, apps/v1beta1, and apps/v1beta2 are deprecated
•	use apps/v1, available since Kubernetes 1.9

**Comment by valosnah** [comment]
Siden jeg uansett går igjennom helm-templatene ifbm minnebruk, gjør jeg denne i samme slengen

**Comment by valosnah** [comment]
- [x] a-backend-service
- [x] concept-catalogue
- [x] concept-catalogue-gui
- [x] dataservice-catalog
- [x] dataservice-catalog-gui
- [x] dataservice-publisher
- [x] dataset-catalogue
- [x] dataset-catalogue-gui
- [x] elasticsearch5
- [x] elasticsearch7
- [x] fdk-admin-gui
- [x] fdk-api-harvester
- [x] fdk-concept-harvester
- [x] fdk-dataservice-harvester
- [x] fdk-dataset-api
- [x] ~~fdk-dataset-harvester~~
- [x] fdk-dataset-harvester-gui
- [x] fdk-fulltext-search
- [x] fdk-fuseki-service
- [x] fdk-harvest-admin
- [x] fdk-harvest-scheduler
- [x] fdk-informationmodel-harvester
- [x] fdk-ingress-config
- [x] fdk-nginx-altinn-proxy
- [x] fdk-nginx-altinn-proxy-mock
- [x] fdk-nginx-dataservices
- [x] fdk-enhetsregisteret-proxy
- [x] fdk-enhetsregisteret-proxy-mock
- [x] fdk-nginx-organization
- [x] fdk-nginx-records
- [x] fdk-nginx-registration
- [x] fdk-nginx-search
- [x] fdk-organization-bff
- [x] fdk-portal
- [x] ~~fuseki~~
- [x] fdk-fuseki-service (ny)
- [x] model-publisher
- [x] mongodb
- [x] new-dataset-harvester
- [x] organization-catalogue
- [x] postgresql
- [x] rabbitmq
- [x] records-of-processing-activities
- [x] records-of-processing-activities-gui
- [x] reference-data
- [x] sso
- [x] terms-and-conditions
- [x] terms-and-conditions-gui
- [x] user-api

**Comment by lillelars** [comment]
Ferdigstilt.
