### ISSUE TITLE
Ny (og endring av) behandlingsaktivitet - skal være default lukket

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3053]
Første seksjon er åpnet. Dette ønskes å være default lukket.

Ønsker default lukket (slik):
![image](https://user-images.githubusercontent.com/39513382/82803519-f9131000-9e80-11ea-8011-e38e3c0f94ff.png)

**Comment by azaxarov** [comment]
Issue moved to [Informasjonsforvaltning/records-of-processing-activities-gui #92](https://github.com/Informasjonsforvaltning/records-of-processing-activities-gui/issues/92) via [**ZenHub**](https://www.zenhub.com/)
