### ISSUE TITLE
Endring: Endre tittel på skjema og brødsmulesti  "Protokoll over behandlingsaktiviteter" til "Registrer ny behandlingsaktivitet" 

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3054]
Endre tittel på skjema og brødsmulesti  "Protokoll over behandlingsaktiviteter" til "Behandlingsoversikt" 
![Skjermbilde protokoll over behandlingsaktiviteter tittel](https://user-images.githubusercontent.com/32771488/77552603-08430500-6eb4-11ea-8a77-80859c18d259.JPG)

**Comment by lillelars** [comment]
denne er ferdigstilt. Lukker saken.
