### ISSUE TITLE
Endring: endre feltnavn og hjelpetekst på "formålet med behandlingsaktivitetene".

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3055]
I bolken Behandlingsaktiviteter, skal tittel på feltet "Formålet med behandlingsaktivitetene" endres til  “Formålene med behandlingen”. 

Endre setning i hjelpetekst fra 
"Det betyr at ethvert formål med behandling av personopplysninger skal identifiseres og beskrives presist."
 til 
“Det betyr at formålet med behandlingen må identifiseres og beskrives presist.”

**Comment by lillelars** [comment]
testet i demo. ferdigstilt
