### ISSUE TITLE
Feilretting: Identifikator vises ikke på modellelementer

### ISSUE THREAD

**Issue by ToHelland** [Altinn/fdk#3057]
I modellene Felles informasjonsmodell for Person og Enhet og Felles informasjonsmodell for Adresse, brukes IRI i turtle-filen som høstes som identifikatorer. 

Spesifikasjonen for informasjonsmodeller har en egenskap for dette: dcatnoinfo:elementIdentifier

![image](https://user-images.githubusercontent.com/17720749/78015710-14aede00-734a-11ea-8e6c-5f06d2632fb4.png)

Det er ikke lagt inn id'er i turtle-filen. Har prøvd dette, men de vises ikke i portalen.

Det må tas en diskusjon på om FDK skal generere disse identifikatorene.

**Comment by ToHelland** [comment]
Saken skal avsluttes. IRI'ene skal vises som i dag.

**Comment by lillelars** [comment]
Saken lukkes fra diskusjon #informasjonsmodeller på slack.
