### ISSUE TITLE
Feil: hjelpetekst Daglig behandlingsansvar

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3060]
Bolk Behandlingsansvar og Databehandler, tema Daglig behandlingsansvar: 
hjelpetekst "Behandlingsansvarliges representant kan delegere oppgaver...
Skal kun stå "Behandlingsansvarlig kan delegere oppgaver.... Se oppdatert hjelpetekst.

**Comment by lillelars** [comment]
testet i demo. ferdigstilt
