### ISSUE TITLE
Endre: overskrift i inputfelt Virksomheter som har felles databehandlingsansvar

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3066]
bolk Behandlingsansvar og databehandler - Felles databehandlingsansvar - inputfelt Virksomheter som har felles databehandlingsansvar: endre databehandlingsansvar til behandlingsansvar

**Comment by lillelars** [comment]
Håndtert i https://github.com/Informasjonsforvaltning/records-of-processing-activities-gui/issues/83

@RogerSOlsen 
Lukker denne.
