### ISSUE TITLE
Registrering av API: Samme fil feiler ved opplasting men funker ved import av lenke

### ISSUE THREAD

**Issue by sskagemo** [Altinn/fdk#3067]
Forsøkte å importere vedlagte testfil via opplasting, men fikk feilmelding. Når jeg la den nett og importerte via lenke, fungerte det fint.
(filnavnet er endret fra openapi.json til openapi_json.txt for å aksepteres av Github)
Lenke til samme fil: https://raw.githubusercontent.com/sskagemo/openAPI/master/specs/test.json 
[openapi_json.txt](https://github.com/Informasjonsforvaltning/fdk/files/4415341/openapi_json.txt)

Forsøkte flere ganger med litt ulike filer den siste timen, sikkert noen spor i loggen ... :-)

**Comment by valosnah** [comment]
Jeg ser i loggen at cloud-armor stoppet en del tilfeller av api-registrering. Kunne du forsøkt på nytt?

**Comment by sskagemo** [comment]
Jepp, nå fungerer det -- tusen takk!

**Comment by lillelars** [comment]
Lukker denne.
