### ISSUE TITLE
endre tekst i spørsmål og veiledning om behandlingsansvarliges representant

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3070]
Bolk Behandlingsansvarlig, spørsmål "Er behandlingsansvarlig eller databehandler etablert utenfor EU/EØS?": 
fjerne "eller databehandler" slik at nytt spørsmål blir ""Er behandlingsansvarlig etablert utenfor EU/EØS?"

Bolk Behandlingsansvarlig, "les mer" hjelpetekst under "Representant for behandlingsansvarlig": 
fjerne "eller databehandler" to steder i hjelpetekst. Se masterfil.

**Comment by lillelars** [comment]
Håndtert i https://github.com/Informasjonsforvaltning/records-of-processing-activities-gui/issues/83.

@RogerSOlsen 
Lukker derfor denne.
