### ISSUE TITLE
Endre feltoverskrift Behandlingsgrunnlag

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3073]
Bolk Behandlingaktiviteter, endre feltoverskrift "Behandlingsgrunnlag etter artikkel 9 eller 10" til "Behandlingsgrunnlag artikkel 9 og 10"

**Comment by lillelars** [comment]
Håndtert i : https://github.com/Informasjonsforvaltning/records-of-processing-activities-gui/issues/83

@RogerSOlsen 
Lukker denne.
