### ISSUE TITLE
Endre tekst om artikkel 9

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3074]
Bolk Behandlingsaktiviteter, Behandlingsgrunnlag etter artikkel 9 eller 10, tekst som kommer fram ved avkryssing i felt som  heter "Artikkel 9 - Behandling av særlige kategorier av personopplysninger", endres fra "Henvisning til annen lovgiving, dersom relevant", til "Henvisning til annen lovgiving" (slette "dersom relevant"). 
Endre det samme også inne i registreringsfeltet

**Comment by lillelars** [comment]
Håndtert i: 
https://github.com/Informasjonsforvaltning/records-of-processing-activities-gui/issues/83
@RogerSOlsen 
Lukker denne.
