### ISSUE TITLE
Små-justeringer for data.transportportal

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#3076]
Farger for løsningen på transportportal oppdateres. Fargelegging følger designet for Felles datakatalog, og har samme fargeodesystem. Det vil si at:
dataset-dark endres til transport-dataset-dark
dataset-light endres til transport-dataset-light
dataset lighter endres til transport-dataset-lighter

[Se fargekoder](https://eggedosis.github.io/fdk-design/redirects/designsystem/colors-all.html)

- [x] Endre farge på tittelseksjoner

- [x] Endre farge på _Åpne data_-tags

- [x] Endre farge på tema-tags

- [x] Detaljside: Endre bakgrunnsfarge

- [x] Detaljside: Endre farge på alle klikkbare tekster (transport-dark)

- [x] Dealjside: Endre farge på åpne-/lukke-ikon

**Comment by lillelars** [comment]
Mangler:

- [x] farge på filteret + pilen skal være transport-neutral-darker

- [x] farge på pil opp/ned på distribusjoner skal være transport-neutral-darker

- [x] Fontfarge på teksten over søkefeltet må endres fra hvit til transport-neutral-darker

@oyvindis kan vi fikse dete før vi ferdigstiller? setter denne tilbake til deg i arbeid.

**Comment by oyvindis** [comment]
@lillelars 'farge på pil opp/ned på distribusjoner skal være transport-neutral-darker': det må være samme farge-variabel som i fdk så da kan det ikke stemme at den skal være 'transport-neutral-darker' her. Det er ikke blått for datasett som skisse viser.

**Comment by lillelars** [comment]
@eggedosis kan du se på dette en gang til ?

**Comment by LeneSundsbo** [comment]
Her har @oyvindis fulgt mer med i timen enn meg. Farge på piler på detaljsiden skal være **transport-dataset-dark**, slik at det harmonerer med FDK-fargekoding.

I filteret skal det være transport-neutral-darker, ettersom vi bruker neutral-darker i FDK.

**Comment by lillelars** [comment]
Dette fungerer nå som det skal. Testet i chrome i demo.
lukker derfor denne.
