### ISSUE TITLE
Feilretting: Endringsdato for modell vises som sist endret-dato i FDK

### ISSUE THREAD

**Issue by ToHelland** [Altinn/fdk#3077]
Legger du inn en endringsdato for en modell, vises denne også som sist endret i FDK. Dette er ulike typer datoer. Endringsdato for modellen, høstes fra lokale modellkataloger. Eksempel hentet fra staging-miljøet:
![image](https://user-images.githubusercontent.com/17720749/78364725-3e703b00-75be-11ea-82f2-27367553fac3.png)
 Felles informasjonsmodell ble først publisert i prod med endringsdato. Det viste seg at modellen ikke skulle ha en endringsdato, så den ble etterhvert fjernet og modellen høstet på nytt. Resultatet ble at datoen sist endret i FDK forsvant.
![image](https://user-images.githubusercontent.com/17720749/78365496-77f57600-75bf-11ea-8e9a-bcd25ba3fa93.png)

Relatert til sak #3045

**Comment by lillelars** [comment]
Testet og godkjent av Tore. Lukker denne.
