### ISSUE TITLE
Endre hjelpetekst i "Behandlingsgrunnlag etter artikkel 9 eller 10"

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3078]
Bolk Behandlingsaktiviteter,  Behandlingsgrunnlag etter artikkel 9 eller 10: oppdater hjelpetekst:

Sammendrag (kort):
Det må foreligge et særskilt grunnlag i tillegg til behandlingsgrunnlag for å behandle denne typen opplysninger. Skriv inn henvisning også til annen lovgivning, dersom relevant.

Ved klikk på pil for å vise mer, skal dette vises:
Les mer på [Datatilsynets sider 
](https://www.datatilsynet.no/rettigheter-og-plikter/virksomhetenes-plikter/behandlingsgrunnlag/veileder-om-behandlingsgrunnlag/?id=10832)

**Comment by lillelars** [comment]
Håndtert i :
https://github.com/Informasjonsforvaltning/records-of-processing-activities-gui/issues/83
lukke denne.
