### ISSUE TITLE
Endre tekstfelt som dukker opp når artikkel 10 er huket av

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3079]
Bolk Behandlingsaktiviteter,  Behandlingsgrunnlag etter artikkel 9 eller 10, tekstfelt som dukker opp når man huker av for "Artikkel 10 - Behandling av personopplysninger om straffedommer og lovovertredelser": 
nåværende tekst som dukker opp i overskrift og tekstfelt er "Henvisning til annen lovgivning, dersom relevant".¨
Bytt tekst i overskrift og tekstfelt med "“Henvisning til aktuell lovgivning”

**Comment by lillelars** [comment]
Håndtert i: https://github.com/Informasjonsforvaltning/records-of-processing-activities-gui/issues/83
@RogerSOlsen 
Lukker derfor denne.
