### ISSUE TITLE
Endre tekst i Kategorier av personopplysninger

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3080]
Bolk Personopplysninger, felt Kategorier av personopplysninger: 
“personopplysninger” i start av hjelpetekst skal starte med stor P

**Comment by lillelars** [comment]
Håndtert i https://github.com/Informasjonsforvaltning/records-of-processing-activities-gui/issues/83.
@RogerSOlsen 
Lukker denne.
