### ISSUE TITLE
endre: flytte feltet "Behandlingen gjelder"

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3081]
Bolk Behandlingsaktiviteter, felt "Behandlingen gjelder": 
flytte feltet "Behandlingen gjelder" til start av registrering slik at feltet registreres før de øvrige bolkene. 
Hensikt er å gjøre det enklere å få oversikt over hva slags behandlingsaktivitet har åpnet når man skal lese eller endre en behandlingsaktivitetet. 

![Flytte behandlingen gjelder](https://user-images.githubusercontent.com/32771488/78551993-f5f78e00-7806-11ea-8683-3c4f202fe449.JPG)

**Comment by lillelars** [comment]
Håndteres av https://github.com/informasjonsforvaltning/records-of-processing-activities-gui/issues/115

**Comment by lillelars** [comment]
Denne er nå løst.
