### ISSUE TITLE
feil: felt vises ved feil valg under Behandlingsgrunnlag etter artikkel 6

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3082]
bolk Behandlingsaktiviteter, felt Behandlingsgrunnlag etter artikkel 6, nedtrekksliste Behandlingens lovlighet: 
ved valgene c, e eller f i nedtrekkslisten, skal registreringsfeltet "Henvisning til rettslig forpliktelse..." vises. Det skjer ikke nå. I stedet vises registreringsfeltet når a, b eller d er valgt, men da skal registreringsfeltet ikke vises.

Se bilde:
![image](https://user-images.githubusercontent.com/39513382/82803376-b3564780-9e80-11ea-8728-6af0cb39dd95.png)

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha): Kritisk

**Comment by azaxarov** [comment]
Issue moved to [Informasjonsforvaltning/records-of-processing-activities-gui #94](https://github.com/Informasjonsforvaltning/records-of-processing-activities-gui/issues/94) via [**ZenHub**](https://www.zenhub.com/)
