### ISSUE TITLE
endre: tittel i registreringsfelt for "Henvisning til rettslig forpliktelse..."

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3083]
Bolk Behandlingsaktiviteter, felt Behandlingsgrunnlag etter artikkel 6, nedtrekksliste Behandlingens lovlighet: 
overskrift på  registreringsfelt "Henvisning til rettslig forpliktelse, berettighet, interesse mv" som skal komme fram når man trykker på valg c, e eller f i nedtrekkslisten, 
endres til ""Henvisning til rettslig forpliktelse, berettiget interesse med videre"

**Comment by lillelars** [comment]
Håndtert i https://github.com/Informasjonsforvaltning/records-of-processing-activities-gui/issues/83
lukker denne.
@RogerSOlsen
