### ISSUE TITLE
Informasjonsmodeller - telefonnummer vises ikke under "Kontakt oss"

### ISSUE THREAD

**Issue by ToHelland** [Altinn/fdk#3084]
Telefonnummer vises ikke under Kontakt oss, til tross for at det ligger i fil som høstes.

Se f.eks. modell i Staging-miljøet: https://staging.fellesdatakatalog.digdir.no/informationModels/a9c9913a-84d2-4b28-b859-4fd3617bbb0b

Testfil som høstes: https://github.com/Informasjonsforvaltning/fdk-testdata/blob/master/testdata/Elveg_2_0.ttl.

**Comment by lillelars** [comment]
Testet og godkjent av Tore. Lukker denne.
