### ISSUE TITLE
Datasett vil ikke åpne detaljesiden og det vises heller ikke under datasettkatalogen

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#3091]
![image](https://user-images.githubusercontent.com/39513382/80338635-19898380-885d-11ea-8ca3-c4bad76e090e.png)

Datasettet: "Test av bolk Distribusjoner per 24.04.2020"
vises under "alle" fanen, men ikke under datasett..
Det går heller ikke ann å se detaljesiden til dette datasettet...

Hva har skjedd?

**Comment by valosnah** [comment]
Først og fremst ser dette ut til å være et problem kun i demo. Høsteren sliter med å få kontakt med elastic5, så det kan se ut som nytt innhold ikke blir lagret der, kun i e7. Både detaljsiden og datasettkatalogen slår opp i e5, alle-fanen viser e7.

**Comment by valosnah** [comment]
Datasettet fantes ikke i elastic5. 
Noe har skjedd under registrering fredag 24.04, som har ført til at datasettet bare ble registrert i elastic7.
Høsteren begynte etterhvert å klage, og logget følgende 1 gang i sekundet:

[crawler_operations] [fail] Error running crawler job: crawler_id=http://dataset-catalogue:8080/catalogs/555111290, crawler_name=Datakatalog for Høgskolen for IT og arkitektur, crawler_url=http://dataset-catalogue:8080/catalogs/555111290, crawler_user=test_admin, error=NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{4K1forIYR6CUiF2Kd8jg3g}{elasticsearch5}{10.2.15.245:9300}]]

Elastic5 ser ikke ut til å ha noen problemer, så det virker som høsteren slår opp en verdi som ikke er der.

Høstemelding sendt fra registreringsløsningen: 10:38

Tidspunkt registrert på datasettet i elastic7:
firstHarvest: 2020-04-24T11:18:13+0200
lastHarvest: 2020-04-24T11:30:14+0200
changed: 2020-04-24T11:30:14+0200 

Konstante feilmeldinger i fdk-dataset-harvester: 24-04 11:31


Det er uklart for meg hvordan feilen har oppstått, men etter en restart av fdk-dataset-harvester kan jeg ikke gjenskape feilen.

**Comment by lillelars** [comment]
Vises fortsatt ikke i portal.. hverken på alle-fanen eller i datakatalogen... Har forsøkt å republiser emed nye data....

Hva er egentlig feil her..?

**Comment by lillelars** [comment]
ser ikke ut til å være et problem lenger etter at vi oppgraderte ES. lukker denne.
