### ISSUE TITLE
Sette opp infrasstruktur for håndtering av bruksvilkår-applikasjon

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#3101]
- [x] legge inn verdier / secrets (2t)

- [x] ingressen må oppdateres <-- trenger ikke oppdatere ingressen, siden vi skal benytte oss av en underside av registreringsløsningen.

- [x] oppdatere fdk-nginx-registration med location /userterms eller liknende

**Comment by valosnah** [comment]
Klar til å legge inn verdier straks det er klart hva front/backend trenger

**Comment by lillelars** [comment]
Ferdigstilt. Lukker denne.
