### ISSUE TITLE
[Portal] Veiledning -> Norsk lisens for offentlige data (NLOD) gir "tom" side.

### ISSUE THREAD

**Issue by stigbd** [Altinn/fdk#3106]
Når eg trykker på lenka Norsk lisens for offentlige data (NLOD), får eg "tom" side:
![image](https://user-images.githubusercontent.com/1702357/82900188-72336580-9f5c-11ea-8242-6c6668ef6962.png)

Disse sidene er tilgjengelege på norsk og engelsk på hhv:
https://data.norge.no/nlod/no/
https://data.norge.no/nlod/en/

Og vi burde gå til ei av disse avhengig av språkvalg, med norsk som default.

**Comment by lillelars** [comment]
Fikset via CMS-et... håndtert på bokmål.

**Comment by lillelars** [comment]
Testet og verifisert for bokmål
