### ISSUE TITLE
Feil lenke på Om-siden

### ISSUE THREAD

**Issue by joachim-me** [Altinn/fdk#3107]
Den går til https://fellesdatakatalog.digdir.no/about-registration.
Den skal gå til https://data.norge.no/about-registration

![image.png](https://images.zenhubusercontent.com/5c6e939eab9efc3c63334546/fb5de3d9-4a9a-4605-b64b-9f0f4bbc94c5)

**Comment by lillelars** [comment]
testet i staging, i chrome. godkjent
