### ISSUE TITLE
For mange datasett vises i NAP (transportportal.no)

### ISSUE THREAD

**Issue by hildea** [Altinn/fdk#3108]
På https://data.transportportal.no/datasets står det nå "Søk blant 1307 datasett", mao. alle datasettene som er på felles datakatalog. En kikk på forsida viser bl.a. "Vitnemålsportalen", "Helsenorge.no" og andre datasett som ikke har noe med transport å gjøre.

**Comment by joachim-me** [comment]
Vi er på saken. Du kan følge utviklingen her: https://github.com/Informasjonsforvaltning/fdk-portal/issues/366

**Comment by hildea** [comment]
Den er grei :-) 
Jeg kikket på label:NAP for å se om det var noen åpen sak på dette, tenkte ikke på å søke på "transportportal" -- skal gjøre det ved ev. framtidige problemer.

**Comment by joachim-me** [comment]
Nå viser NAP riktig antall datasett.
