### ISSUE TITLE
Stopp i import fra vegvesenet sin dataportal

### ISSUE THREAD

**Issue by hildea** [Altinn/fdk#3110]
Jeg la inn et nytt datasett i dataportalen vår i går, det har ikke kommet inn i felles datakatalog ennå. 

Det gjelder dette datasettet: https://dataut.vegvesen.no/dataset/bomstasjoner-i-nvdb
Jeg har sjekket at det er med i eksporten vår på https://dataut.vegvesen.no/catalog.ttl / https://prod.nora.links.com.au/catalog.ttl 
(Begge URLene går til samme sted, men det kan være greit å bytte til vegvesen.no-URLen, siden den er mer sikker på lang sikt.)

**Comment by lillelars** [comment]
@hildea vi begynner å se på dette asap!

**Comment by rannveigskjerve** [comment]
Datasettet er tilgjengelig i søk nå. Ser videre på hvorfor det tok så lang.
