### ISSUE TITLE
Prodfeil: Rapportsiden blir ikke vist

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#3111]
@rannveigskjerve og @oyvindis kan det stemme at en av dere må gjøre noe her? Tror det bare er dere som har arbeidet med denne siden siste tiden.

![image.png](https://images.zenhubusercontent.com/5c5c205bdf0733a30555bab8/ede5b4ef-98f4-4ef6-b97c-4bdd5520384b)

**Comment by lillelars** [comment]
@valosnah @NilsOveTen fuseki issues?

**Comment by valosnah** [comment]
Fuseki hadde en litt svak kobling til disken sin, som ikke ble oppdaget før Google kjørte oppdateringer i vedlikeholdsvinduet på søndag. Ved restart fikk ikke podden kontakt med disken, og nektet å starte opp. Har ryddet i dette, og podden kjører fint nå.

**Comment by lillelars** [comment]
Fikset og testet i chrome, prod.
