### ISSUE TITLE
Effektivisering av GCP

### ISSUE THREAD

**Issue by valosnah** [Altinn/fdk#3125]
Mange helm-templates requester langt mer ressurser enn de behøver. Evt oppskalering av ressursbruk håndterer GCP fint selv.

- [x] Gå igjennom samtlige podder, sett memory-request som harmonerer mer med poddens historiske bruk

- [x] Verifisér at systemet holder seg stabilt

- [x]  Oppdatér helm-chart.

**Comment by valosnah** [comment]
Har gjennomgått dev, der er det potensiale for å redusere med ca 10 GB minne for både staging og demo, så totalt 20GB for digdir-fdk-dev prosjektet.

**Comment by lillelars** [comment]
@valosnah hva blir det ca i kost-reduksjon ?

**Comment by valosnah** [comment]
For staging, ca €175 i mnd, hvis jeg kalkulerer rett

**Comment by valosnah** [comment]
> @valosnah hva blir det ca i kost-reduksjon ?

For staging, ca €175 i mnd, hvis jeg kalkulerer rett

**Comment by valosnah** [comment]
- [x] a-backend-service: 1000->300
- [x] api-catalogue: 1000->750
- [x] concept-catalogue: 1000->500
- [x] concept-catalogue-gui: 1000->10
- [x] dataservice-catalog: 500->400
- [x] dataservice-catalog-gui: 1000->10
- [x] dataservice-publisher: 100->200
- [x] dataset-catalogue: 1000->750
- [x] dataset-catalogue-gui: 1000->10
- [x] elasticsearch5: 3000->4000
- [x] elasticsearch7: 3/5000->3/5000
- [x] fdk-admin-gui: 100->10
- [x] fdk-api-harvester: 1400->750
- [x] fdk-concept-harvester: 1400->800
- [x] fdk-dataservice-harvester: 1400->750
- [x] fdk-dataset-api: 1500->750
- [x] fdk-dataset-harvester: 1300->
- [x] fdk-dataset-harvester-gui: 1000->600
- [x] fdk-fulltext-search: 1000->1000 
- [x] fdk-fuseki-service: 850->850
- [x] fdk-harvest-admin: 100->100
- [x] fdk-harvest-scheduler: 1000->10
- [x] fdk-informationmodel-harvester: 1400->1400 
- [x] fdk-nginx-altinn-proxy: 5->5
- [x] fdk-nginx-altinn-proxy-mock: 5->5
- [x] fdk-nginx-dataservices: 5->5
- [x] fdk-enhetsregisteret-proxy: 5->5
- [x] fdk-enhetsregisteret-proxy-mock: 5->5
- [x] fdk-nginx-organization: 5->5
- [x] fdk-nginx-records: 5->5
- [x] fdk-nginx-registration: 1000->10
- [x] fdk-nginx-search: 1000->10
- [x] fdk-organization-bff: 500-> ?? 
- [x] fdk-portal: 100->100 
- [x] fuseki: 850->850
- [x] model-publisher: 100->150
- [x] mongodb: 1000->500
- [x] new-dataset-harvester: 1400->1400
- [x] organization-catalogue: 1000->750
- [x] postgresql: --- 
- [x] rabbitmq: 150->150
- [x] records-of-processing-activities: mangler request, bruker <100
- [x] records-of-processing-activities-gui: mangler request, bruker <10
- [x] reference-data: 900->900
- [x] sso: 1000->1000
- [x] terms-and-conditions: 1000->500
- [x] terms-and-conditions-gui: 100->10
- [x] user-api: 1000->500
