### ISSUE TITLE
Endre: hjelpetekst for Planlagte tidsfrister for sletting

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3130]
Bolk Personopplysninger, felt Planlagte tidsfrister for sletting:
Hjelpetekst "For de forskjellige kategorier av personopplysninger, dersom mulig." byttes med ny hjelpetekst "Dersom mulig, angi frist for sletting for de forskjellige kategorier av personopplysninger."

**Comment by lillelars** [comment]
testet i demo. ferdigstilt.
