### ISSUE TITLE
Feil: ingen eller treg respons i registreringsløsning i demo og prod

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3132]
Jeg får blank side når jeg åpner registreringsløsningen i demo og prod. 

I prod er det noen sekunder venting før katalogene dukker opp. I demo skjer det ofte ingenting. Der må jeg gjerne klikke på "Datasettkatalog" en eller flere ganger før jeg får mulighet til å gå 

![image](https://user-images.githubusercontent.com/32771488/85275764-1be51400-b481-11ea-9018-2cf0df223908.png)

**Comment by valosnah** [comment]
Skyldes sannsynligvis reference-data. Caching i fdk-nginx-search er potensielt en løsning
