### ISSUE TITLE
Mangler i visning av datatjenester

### ISSUE THREAD

**Issue by joachim-me** [Altinn/fdk#3144]
Følgende felter er forventet å finne igjen i portal. Tomme celler betyr at det ikke vises. Oppdatert tabellen med hvilke felter som finnes i [dcat:](https://teams.microsoft.com/l/file/DA2EED13-23AF-40ED-9592-613A85ABA0E8?tenantId=008e560f-08af-4cec-a056-b35447503991&fileType=xlsx&objectUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FFDKUtviklingsteam%2FDelte%20dokumenter%2FGeneral%2Ftest%20datatjeneste.xlsx&baseUrl=https%3A%2F%2Fdigdir.sharepoint.com%2Fsites%2FFDKUtviklingsteam&serviceName=teams&threadId=19:08cde20dfa4c45c0855d6e41d03038b3@thread.tacv2&groupId=47529ac3-12da-40d3-ba0f-947e6d4cec62)

**Comment by lillelars** [comment]
Da er det bare felter som ikke støttes av DCAT som ikke vises. Lukker derfor saken.
