### ISSUE TITLE
Dataset-catalogue må opprette nye dataset data sources i fdk-admin

### ISSUE THREAD

**Issue by valosnah** [Altinn/fdk#3154]
Det nye admin-grensesnittet blir ikke oppdatert med nye datasett-kilder slik det gamle ble.

- [ ] Endre slik at dataset-catalogue går mot nye admin
- [ ] Se til at nye admin håndterer opprettelse av nye dataset-sources

**Comment by lillelars** [comment]
Issue moved to [Informasjonsforvaltning/dataset-catalogue #63](https://github.com/Informasjonsforvaltning/dataset-catalogue/issues/63) via [**ZenHub**](https://www.zenhub.com/)
