### ISSUE TITLE
Peke mot korrekte artikler ved nynorsk og engelsk systemspråk

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#3156]
Dersom bruker har valgt et annet språk enn "Bokmål" for løsningen skal:

https://data.norge.no/guidance 

Bruk: https://cms-fellesdatakatalog.digdir.no/api/content/node/page
til å hente ut alle statiske sider.

40cb9799-4f53-482c-8075-417f70bcd483 <-- er til "Rettleiing"
95430944-2177-48d1-9e1e-f589defd262c <--- er til "Guidance" 

og 

https://data.norge.no/about

vises på valgte språk.

**Comment by lillelars** [comment]
@oyvindis får ikke denne til å fungere som forventet..? Er det noe jeg må gjøre fra CMS'et eller om vi må prodsette portal?
Testet forsåvidt i staging...

**Comment by oyvindis** [comment]
@lillelars det er bare gjort for side "Veiledning", og ikke prodsatt så må testes i staging.

På denne siden: https://www.staging.fellesdatakatalog.digdir.no/guidance kan jeg endre språk og se artikkel på valgt språk.

Kan du teste en gang til?

**Comment by lillelars** [comment]
@oyvindis  Dette fungerer fint i staging. Er det noe som hindrer oss i å dytte det helt ut? Hva må prodsettes - jeg trodde dette var fdk-portal?

**Comment by lillelars** [comment]
Denne fungerer nå som den skal og er prodsatt :) lukker denne.
