### ISSUE TITLE
Mangler i visning av innholdsleverandør

### ISSUE THREAD

**Issue by joachim-me** [Altinn/fdk#3159]
Virksomheter som ikke finne i organization-catalog vises ikke: https://staging.fellesdatakatalog.digdir.no/reports

I følge @azaxarov er dette noe som bør fikses i fdk-parser. Det gjøres tydeligvis ikke oppslag mot enheter som ikke finnes i organization-catalogue.

**Comment by lillelars** [comment]
Har lagt til disse for datasettbeskrivelsen "Test innholdsleverandører":
![image](https://user-images.githubusercontent.com/39513382/91015741-f775f700-e5eb-11ea-8be9-7b54ec1b6378.png)

De vises ikke ut i portaL:
![image](https://user-images.githubusercontent.com/39513382/91015670-d1505700-e5eb-11ea-9d74-f6ab0ea0fa0f.png)

**Comment by NilsOveTen** [comment]
@azaxarov @lillelars Jeg kan gjøre endringer i rdf-parser slik at portal får en orgPath når den får orgcat, men den vil ikke dukke opp i organization-catalogue.

Så lenge orgnr ikke er tilgjengelig i enhetsregisteret-mock, så vil det ikke dukke opp i orgcat

**Comment by NilsOveTen** [comment]
Vi har en del publishere som aldri vil dukke opp i organization-catalogue, siden de ikke har orgnr, blir derfor feil om reports kun støtter seg på organization-catalogue

**Comment by lillelars** [comment]
@joebrreg testet du forresten denne i prod?

Det vil ikke fungere i staging og demo når vi i portal går mot enhetsregisteret mock, mens vi i valglisten for innholdsleverandører går mot opprinnelig enhetsregisteret. Da må du i så fall velge en organisasjon som finnes i begge listene (f.eks digitaliseringsdirektoratet) Jeg testet dette og da funker det: https://staging.fellesdatakatalog.digdir.no/datasets/e5fd6fe6-7ce2-39c7-baff-cb2ee35d08a0

**Comment by lillelars** [comment]
Denne fungerer som forventet.
