### ISSUE TITLE
Høsting av datasett hver time fungere ikke

### ISSUE THREAD

**Issue by joachim-me** [Altinn/fdk#3160]
Testet i demomiljø. Antar at det samme gjelder for prod. Roger rapporterer:
"Jeg gjorde en endring i datasettbeskrivelsen "API-katalog i Felles datakatalog" i demomiljø 0855 og publiserte da. Nå kl 0909 finner jeg den fortsatt ikke i demomiljøet. Har søkt på den i søkefeltet, og sortert etter sist publisert, men finner den ikke i demo-portalen.
kl 0759 la jeg inn relasjoner i datasettbeskrivelsen "Felles datakatalog" som var publisert fra før i prod. Nå kl 0930 vises relasjonene fortsatt ikke i prod-portal. Vet dere når jeg kan forvente at publisering i demo og pord fungerer igjen?"

**Comment by lillelars** [comment]
@Chlenix Kan du starte med å se på dette?

**Comment by lillelars** [comment]
Løses av ulike PRs for Rabbit delen

**Comment by lillelars** [comment]
Denne fungerer nå som den skal. lukker denne.
