### ISSUE TITLE
Endre: "Kontaktperson" i «Behandlingsansvarlig og databehandler», felt «Felles behandlingsansvarlig» til "Kontaktpunkt"

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3162]
Bolk «Behandlingsansvarlig og databehandler», tema «Felles behandlingsansvarlig», felt "Kontaktperson : 
bytte «Kontaktperson» med  «Kontaktpunkt»:

![image](https://user-images.githubusercontent.com/32771488/90874340-de790600-e39f-11ea-8a28-e98e4f1c6f33.png)

**Comment by lillelars** [comment]
Denne er fikset. Lukker saken.
