### ISSUE TITLE
Endre Aktuell lovgiving til annen lovgiving i artikkel 9 og 10

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3163]
Bolk Behandlingsaktiviteter, Behandlingsgrunnlag artikkel 9 og 10: 
endre "aktuell lovgiving" til "annen lovgiving"

![image](https://user-images.githubusercontent.com/32771488/90881977-66b0d880-e3ab-11ea-927b-71ab6e7738ff.png)

**Comment by lillelars** [comment]
Denne er ferdigstilt. Lukker saken.
