### ISSUE TITLE
Endre tittel på "Funksjonsområde behandlingen faller inn under"

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3165]
Bolk Behandlingsaktiviteter, tema Funksjonsområde behandlingen faller inn under. 

Endringsønske:
Endre tittel fra "Funksjonsområde behandlingen faller inn under" til " Funksjons- eller virksomhetsområde"

Bakgrunn: 
dette er en tilnærming til måten Datatilsynet behandler temaet på i  celle 1b i arket “Artikkel 40 protokoll” i Datatilsynets  fil over protokoll for behandlingsansvarlig (https://www.datatilsynet.no/rettigheter-og-plikter/virksomhetenes-plikter/protokoll-over-behandlingsaktiviteter/). Et annet eksempel er Bergen kommune som oppgir både funksjonsområde og virksomhetsområde (se filen “Protokoll BEHF” på https://www.bergen.kommune.no/styrende-dokument/#/SD-19-138 , ark “Etat for hjemmebasert_tjenester”, celle 1B).

**Comment by lillelars** [comment]
denne gjelder ikke lenger.
