### ISSUE TITLE
Endre overskrift på “Overføres personopplysningene til tredjeland?” og “Oppgi hvilke(t) tredjeland personopplysningene overføres til”

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3166]
Bolk Overføring av personopplysningene, tema Overføres personopplysningene til tredjeland.

Endringsønske: 
endre overskrift "Overføres personopplysingene til tredjeland" til "Overføres personopplysingene til tredjeland eller internasjonale organisasjoner". 
Under feltet kan man klikke på ja eller nei. Klikker man på ja, kommer det et nytt felt frem. 
Her må overskriften “Oppgi hvilke(t) tredjeland personopplysningene overføres til” 
endres til “Oppgi hvilke(t) tredjeland eller internasjonal organisasjon personopplysningene overføres til”

**Comment by lillelars** [comment]
Denne ble revurdert og fikset.
