### ISSUE TITLE
Endre overskrifter i “Er det gjennomført risikovurdering?” 

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3168]
bolk Personopplysninger, tema Er det gjennomført risikovurdering?

Endring: 
endre overskrift "Er det gjennomført risikovurdering" til "Er det gjennomført personvernkonsekvensvurdering (DPIA)?".

endre tittel på registreringsfeltet “Lenke til risikovurdering” til “"Sak-/arkivreferanse eller lenke til  personvernkonsekvensvurdering (DPIA)".

 Må sees i sammenheng med [BRUKERHISTORIE] bolk for Risikovurdering og sikkerhet # 482

**Comment by lillelars** [comment]
Denne ble endret og lagt inn i ny bolk. Lukker saken.
