### ISSUE TITLE
Slette "Kan behandlingen innebære høy personvernrisiko?"

### ISSUE THREAD

**Issue by RogerSOlsen** [Altinn/fdk#3169]
Bolk Personopplysninger, tema "Kan behandlingen innebære høy personvernrisiko?":

slett hele temaet. 

NB: endringene i issue “Endre overskrifter i “Er det gjennomført risikovurdering?” #3168” (https://github.com/Informasjonsforvaltning/fdk/issues/3168) må være gjennomført før #3169 gjennomføres
 Må sees i sammenheng med [BRUKERHISTORIE] bolk for Risikovurdering og sikkerhet # 482

**Comment by LeneSundsbo** [comment]
@RogerSOlsen Vi det si at feltet utgår?

**Comment by lillelars** [comment]
Feltet er fjernet. Lukker saken.
