### ISSUE TITLE
Boogers for rapportsiden 

### ISSUE THREAD

**Issue by lillelars** [Altinn/fdk#3170]
- [x] Feil CSS ved "0 siste" - gjelder BÅDE NAP og data.norge.no
![image](https://user-images.githubusercontent.com/39513382/91843899-cda97980-ec56-11ea-82f5-2fe3d2513efa.png)

- [x] NAP: Får med seg en datasettbeskrivelse fra justis og beredskapsdepartementet? dermed blir også totalen feil.
![image](https://user-images.githubusercontent.com/39513382/91843769-96d36380-ec56-11ea-8466-778ad11d3a76.png)

GRAF FOR ANTALL DATASETTBESKRIVELSER (gjelder både NAP og data.norge.no:
Se design: https://eggedosis.github.io/fdk-design/redirects/portal/report/all.html
- [x] Mangler undertekst "Antall datasettbeskrivelser siden første publisering"

- [x] Grafen skal vise antall datasettbeskrivelser siden første publisering, slik at grafen blir stigende. Nå viser den antall nye datasett per enkelte datoer...

- [x] Antall datopunkter i X-aksen er for mange. Kan man fjerne hvertfall en del av teksten her?
![image](https://user-images.githubusercontent.com/39513382/91844074-182af600-ec57-11ea-8894-52b3b1158ec1.png)

- [x] Antall tellinger for "Åpne data" er feil
![image](https://user-images.githubusercontent.com/39513382/91844464-d189cb80-ec57-11ea-9474-db95e819b8c0.png)
Skal være 820 (se datasett-fanen). 

"MEST BRUKTE TEMAER OG EMNER":

- [x] Skal bare vise de 10 mest brukte temaene (nå vises alle):
![image](https://user-images.githubusercontent.com/39513382/91845693-dea7ba00-ec59-11ea-875a-ee24f14e132a.png)

- [ ] For SVV sin Transportportal skal vi bare vise de 4 underkategoriene og antall som er tagget med disse. Altså IKKE hele temalisten:
![image](https://user-images.githubusercontent.com/39513382/91848671-195e2200-ec5b-11ea-9655-15632e324664.png)

- [x] Skal ikke vise "MISSING":
![image](https://user-images.githubusercontent.com/39513382/91845405-63de9f00-ec59-11ea-829c-56c1e27b3a32.png)

- [x] Klarer ikke å vise tagging av Emneord? "Personnavn", "Sykkel" osv...
![image](https://user-images.githubusercontent.com/39513382/91845477-87a1e500-ec59-11ea-8c40-bdf688375af3.png)

- [x] Emneordene bør bare vise emneordet og ikke hele stien etter filtrering/trykk:
![image](https://user-images.githubusercontent.com/39513382/91845539-9d170f00-ec59-11ea-9789-5bd750c78088.png)

ANTALL KATALOGER I LØSNINGEN:

- [x] Dette går nå mot OrgPath.. Dette er FEIL. det skal bare vise antall kataloger m/ navn på disse og antall datasettbeskrivelser hver katalog inneholder. (NB! Tallet "125" her skal da reflektere unike antall datasett publishere.)
![image](https://user-images.githubusercontent.com/39513382/91845954-58d83e80-ec5a-11ea-80cc-f99b58ae9707.png)

GRAF OVER FORMATER (lavest prioritet):
- [x] CSS for tallene må forbedres (synliggjøre at tallene er klikkbare) og forbedre hvordan de ser ut
![image](https://user-images.githubusercontent.com/39513382/91845229-13674180-ec59-11ea-87fb-ad29b86189e2.png)

**Comment by rannveigskjerve** [comment]
Frontend:
- [x] endre filteret til å bruke "orgPaths" istedet for catalogs
- [x] For organisasjoner uten treff i organizationcatalog vises hele orgpath under kataloger

**Comment by rannveigskjerve** [comment]
![image](https://user-images.githubusercontent.com/55136985/92581955-a3783d00-f290-11ea-93b3-a04a7951ff02.png)

- [x] Feil i opptelling, skal være antall **virksomheter**, ikke _kataloger_

- [ ] Design: uklar sammenheng; kan oppfattes som at listen under er pr _virksomhet_, bør tydeligjøres at listen er  pr **katalog**

@eggedosis @oyvindis

**Comment by lillelars** [comment]
Denne fungerer nå. Håndterer siste designoppgave i eget issue.
