### ISSUE TITLE
Feil lenke til SVV-datasett

### ISSUE THREAD

**Issue by valosnah** [Altinn/fdk#3173]
SVV datasett Data source ligger inne i admin med prod.nora-linken. Den riktige er https://dataut.vegvesen.no/catalog.ttl

ETL kan unngås hvis den eksisterende grafen slettes fra fuseki, og vi høster på nytt med den riktige linken

**Comment by valosnah** [comment]
Graf slettet, link endret til dataut, og høstet på nytt. Skal ha løst problemet.

**Comment by lillelars** [comment]
Ser ut til at vi ikke har problemet lenger. Lukker saken.
